input_boolean:
  scene_delivery:
    name: 'Scene: Delivery'
    icon: mdi:truck-delivery
    initial: false

input_datetime:
  scene_delivery_started:
    name: 'Scene Delivery: Started'
    has_time: true
    has_date: true
    icon: mdi:exit-run

  scene_delivery_scheduled_from:
    name: 'Scene Delivery: Scheduled from'
    has_time: true
    has_date: true
    icon: mdi:calendar-arrow-right

  scene_delivery_scheduled_to:
    name: 'Scene Delivery: Scheduled to'
    has_time: true
    has_date: true
    icon: mdi:calendar-arrow-left

automation:
  - id: scene_delivery_turn_on
    alias: 'Scene Delivery: Turn on'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Заказана еда

      - id: event
        trigger: event
        event_type: living_room_heater_button_hold_down
    actions:
      - if:
          - condition: state
            entity_id: input_boolean.scene_delivery
            state: 'on'
        then:
          - service: script.yandex_station_tts
            data:
              target: >
                {{ 'media_player.living_room_station' if trigger.id == 'event' else trigger.event.data.get('entity_id', 'last') }}
              text: >
                {% set elapsed_seconds = as_timestamp(now()) - state_attr('input_datetime.scene_delivery_started', 'timestamp') %}
                {{ 'Еда заказана' if trigger.id == 'event' else ['Ага,', 'Я знаю,', 'Наверняка,']|random }} уже как {{ (elapsed_seconds / 60)|int }}мин назад
                {% if elapsed_seconds > 40 * 60 * 60 %}
                  и я немного волнуюсь
                {% endif %}

      - condition: state
        entity_id: input_boolean.scene_delivery
        state: 'off'

      - service: input_boolean.turn_on
        entity_id: input_boolean.scene_delivery

      - service: input_datetime.set_datetime
        entity_id: input_datetime.scene_delivery_started
        data:
          datetime: >
            {{ now().strftime('%Y-%m-%d %H:%M:%S') }}

      - if:
          - condition: trigger
            id: event
        then:
          - action: script.turn_on
            entity_id: script.living_room_tv_status_light_ack_flash

          - service: script.yandex_station_tts
            data:
              target: >
                {{ 'media_player.living_room_station' if trigger.id == 'event' else trigger.event.data.get('entity_id', 'last') }}
              text: >
                {{ [
                    'Еда заказана. Очень хочется кушать',
                    'Еда заказана. Скорей бы привезли кушать',
                    'Еда заказана. Ждём с нетерпением',
                    'Ждем курьера, но почему бы не приготовить самому?',
                    'Ждем курьера, но почему бы не приготовить самому?',
                    'Еда заказана. Не забудь всё подготовить.',
                  ]|random
                }}
        else:
          - service: script.yandex_station_tts
            data:
              target: >
                {{ 'media_player.living_room_station' if trigger.id == 'event' else trigger.event.data.get('entity_id', 'last') }}
              text: >
                {{ [
                    'Хорошо, ждём. Очень хочется кушать',
                    'Хорошо, скорей бы привезли кушать',
                    'Отлично, ждём с нетерпением',
                    'Ждем курьера, но почему бы не приготовить самому?',
                    'Ждем курьера, но почему бы не приготовить самому?',
                    'Хорошая новость. Не забудь всё подготовить.',
                  ]|random
                }}

  - id: scene_delivery_30min_passed
    alias: 'Scene Delivery: 30min passed'
    trigger:
      - platform: state
        entity_id: input_boolean.scene_delivery
        to: 'on'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation
    action:
      - service: script.yandex_station_tts
        data:
          target: all
          type: attention
          text: >
            {{ [
                'Уже прошло полчаса, курьер может уже выехал?',
                'Тридцать минут прошло, голод только стал сильнее',
                'Полчаса минуло, надеюсь курьер в пути'
               ]|random
            }}

  - id: scene_delivery_60min_passed
    alias: 'Scene Delivery: 60min passed'
    trigger:
      - platform: state
        entity_id: input_boolean.scene_delivery
        to: 'on'
        for:
          minutes: 60
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation
    action:
      - service: script.yandex_station_tts
        data:
          target: all
          type: attention
          text: Тем временем еды уже нет целый час. Это вообще никуда не годится! Я буду жаловаться!

  - id: scene_delivery_turn_off
    alias: 'Scene Delivery: Turn off'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.scene_delivery
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.scene_delivery

      - delay:
          seconds: 8

      - service: script.yandex_station_tts
        data:
          target: all
          type: attention
          text: >
            {% set elapsed_seconds = as_timestamp(now()) - state_attr('input_datetime.scene_delivery_started', 'timestamp')  %}
            А вот и еда! {{ ['Еду привезли за', 'Еда доставлена за', 'Мы смогли продержаться эти']|random }} {{ (elapsed_seconds / 60)|int }}мин

  - id: scene_delivery_turn_off_fallback
    alias: 'Scene Delivery: Turn off (fallback)'
    trigger:
      - platform: state
        entity_id: input_boolean.scene_delivery
        to: 'on'
        for:
          hours: 6
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.scene_delivery
