input_boolean:
  # Побочные действия:
  # 1. Запрещает отключение путевых светильников
  scene_sleepy_mood:
    name: 'Scene: Sleepy Mood'
    icon: mdi:alarm-snooze
    initial: false

automation:
  - id: scene_sleepy_mood_turn_on
    alias: 'Scene Sleepy Mood: Turn on'
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Хочется спать
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.scene_sleepy_mood
          - input_boolean.bedroom_airing_cold

      - service: media_player.turn_off
        entity_id: media_player.tv

      - service: light.turn_on
        entity_id:
          - light.bedroom_bed
          - light.bedroom_moon
        data:
          rgb_color: >
            {{ [
              [255, 71, 51],
              [202, 255, 10],
              [10, 255, 173],
              [10, 255, 243],
              [10, 214, 255],
              [229, 233, 255],
              [133, 10, 255],
              [173, 10, 255],
              [255, 10, 231],
            ]|random }}
          brightness_pct: 100

      - service: light.turn_on
        entity_id:
          - light.bedroom_cat
          - light.bedroom_string
        data:
          kelvin: 2700
          brightness_pct: 12

      - delay:
          milliseconds: 500

      - service: light.turn_on
        entity_id:
          - light.hallway_path
          - light.kitchen_path
        data:
          rgbw_color: >
            {{ state_attr('light.bedroom_bed', 'rgb_color')|list + [0] }}
          brightness_pct: 15

      - service: light.turn_on
        entity_id:
          - light.bathroom_sink_path
          - light.bathroom_toilet_path
        data:
          rgbw_color: >
            {{ state_attr('light.bedroom_bed', 'rgb_color')|list + [0] }}
          brightness_pct: 75

      - service: light.turn_on
        entity_id: light.living_room_backlight
        data:
          rgb_color: >
            {{ state_attr('light.bedroom_bed', 'rgb_color')|list }}
          brightness_pct: 40

      - service: light.turn_on
        entity_id: light.bathroom_main
        data:
          brightness_pct: 10

      - service: light.turn_on
        entity_id: light.kitchen_worktop
        data:
          brightness_pct: 25

      - if:
          - condition: state
            entity_id: light.wardrobe
            state: 'on'
        then:
          - service: light.turn_on
            entity_id: light.wardrobe
            data:
              brightness_pct: 20

      - if:
          - condition: state
            entity_id: binary_sensor.porch_motion
            state: 'off'
        then:
          - service: light.turn_off
            entity_id: light.porch

      - service: light.turn_off
        entity_id:
          - group.workshop_lights
          - light.bathroom_bathtub
          - light.bathroom_mirror
          - light.bedroom_main
          - light.closet
          - light.entrance
          - light.hallway
          - light.kitchen_main
          - light.kitchen_mood
          - light.living_room_main
          - light.living_room_tv

      - service: cover.close_cover
        entity_id:
          - cover.bedroom
          - cover.kitchen
          - cover.living_room
          - cover.workshop

      - service: script.yandex_station_tts
        data:
          target: >
            {{ trigger.event.data.get('entity_id', 'last') }}
          text: >
            {{ ['Хорошая мысль', 'Готовимся к погружению в мир грёз', 'Ммм, подушка душистая и одеяло пустишое', 'Постелька уже ждет', 'Пойдём в кроватку', 'Сон - это хорошо']|random }}.

            {% if states('sensor.chores')|length > 0 %}
              Только не забудь {{ states('sensor.chores') }}
            {% endif %}

      - if:
          - condition: state
            entity_id: climate.bedroom_ac
            state:
              - 'off'
              - heat_cool
              - cool
              - heat
              - dry

          - condition: numeric_state
            entity_id: sensor.outside_temperature
            above: 17
        then:
          - service: climate.set_temperature
            entity_id: climate.bedroom_ac
            data:
              hvac_mode: cool
              temperature: 24

      - if:
          - condition: state
            entity_id: lock.front_door
            state: unlocked
        then:
          - service: lock.lock
            entity_id: lock.front_door

      - if:
          - condition: state
            entity_id: binary_sensor.porch_door
            state: 'off'

          - condition: state
            entity_id: lock.porch_door
            state: unlocked
        then:
          - service: lock.lock
            entity_id: lock.porch_door

  - id: scene_sleepy_mood_turn_off
    alias: 'Scene Sleepy Mood: Turn off'
    trigger:
      - platform: state
        entity_id: light.bedroom_bed
        from: 'on'
        to: 'off'

      - platform: state
        entity_id:
          - light.bedroom_main
          - light.living_room_main
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.scene_sleepy_mood
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.scene_sleepy_mood
