input_boolean:
  scene_wait_guests:
    name: 'Scene: Wait guests'
    icon: mdi:account-star-outline
    initial: false

automation:
  - id: scene_wait_guests_turn_on
    alias: 'Scene Wait Guests: Turn on'
    triggers:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Ждём гостей
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.scene_wait_guests

      - action: script.yandex_station_tts
        data:
          target: >
            {{ trigger.event.data.get('entity_id', 'last') }}
          text: >
            {{ [
                'Хорошо, открою им двери когда придут',
                'Поняла, с нетерпением ждем',
                'Отлично, хоть какие-то новые лица'
               ]|random
            }}

  - id: scene_wait_guests_turn_on_light
    alias: 'Scene Wait Guests: Turn on lights'
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.front_door
    conditions:
      - condition: state
        entity_id: input_boolean.scene_wait_guests
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: light.is_off
        target:
          entity_id: light.entrance
    actions:
      - action: light.turn_on
        entity_id: light.entrance

  - id: scene_wait_guests_turn_off
    alias: 'Scene Wait Guests: Turn off'
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.front_door

      - trigger: state
        entity_id: input_boolean.scene_wait_guests
        to: 'on'
        for:
          hours: 1
    conditions:
      - condition: state
        entity_id: input_boolean.scene_wait_guests
        state: 'on'
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.scene_wait_guests
