# Тут стрёмное дублирование, но мне так лень это как-то унифицировать
input_boolean:
  workshop_humidifier_control:
    name: 'Workshop Humidifier: Control'
    icon: mdi:refresh-auto

template:
  binary_sensor:
    - unique_id: binary_sensor.workshop_humidifier_1_water_tank
      name: 'Workshop Humidifier 1 Water Tank'
      icon: mdi:car-coolant-level
      device_class: connectivity
      state: >
        {{ states('sensor.workshop_humidifier_1_water_level_raw')|int(127) != 127 }}
      availability: >
        {{ states('humidifier.workshop_humidifier_1') not in ['unknown', 'unavailable'] }}

    - unique_id: binary_sensor.workshop_humidifier_2_water_tank
      name: 'Workshop Humidifier 2 Water Tank'
      icon: mdi:car-coolant-level
      device_class: connectivity
      state: >
        {{ states('sensor.workshop_humidifier_2_water_level_raw')|int(127) != 127 }}
      availability: >
        {{ states('humidifier.workshop_humidifier_2') not in ['unknown', 'unavailable'] }}

  sensor:
    - unique_id: binary_sensor.workshop_humidifier_1_water_level
      name: 'Workshop Humidifier 1 Water Level'
      icon: mdi:water-check
      unit_of_measurement: '%'
      state: >
        {% set v = states('sensor.workshop_humidifier_1_water_level_raw')|int(0) %}
        {% if v > 125 %}
          0
        {% else %}
          {{ int(min(v / 1.2, 100)) }}
        {% endif %}
      availability: >
        {{ states('humidifier.workshop_humidifier_1') not in ['unknown', 'unavailable'] }}

    - unique_id: binary_sensor.workshop_humidifier_2_water_level
      name: 'Workshop Humidifier 2 Water Level'
      icon: mdi:water-check
      unit_of_measurement: '%'
      state: >
        {% set v = states('sensor.workshop_humidifier_2_water_level_raw')|int(0) %}
        {% if v > 125 %}
          0
        {% else %}
          {{ int(min(v / 1.2, 100)) }}
        {% endif %}
      availability: >
        {{ states('humidifier.workshop_humidifier_2') not in ['unknown', 'unavailable'] }}

    - unique_id: sensor.workshop_humidifier_target_mode
      name: 'Workshop Humidifier: Target mode'
      icon: mdi:target-variant
      state: >
        {% set mode = 'Level3' %}
        {% set target_humidity = states('input_number.home_target_humidity')|int(40) %}
        {% set outdoor_temperature = states('sensor.outside_temperature')|float(0) %}

        {% if outdoor_temperature < -15 %}
          {% set target_humidity = 42 %}
        {% endif %}

        {% if states('sensor.workshop_humidity')|int(0) >= target_humidity %}
          {% set mode = 'Level2' %}
        {% endif %}

        {% if states('sensor.workshop_humidity')|int(0) >= target_humidity + 2 %}
          {% set mode = 'off' %}
        {% elif states('sensor.workshop_humidifier_1_water_level')|int(0) <= 50 or
                states('sensor.workshop_humidifier_2_water_level')|int(0) <= 50 %}
          {% set mode = 'off' %}
        {% endif %}

        {% if is_state('input_select.home_mode', 'Vacation') %}
          {% set mode = 'off' %}
        {% endif %}

        {{ mode }}

automation:
  - id: workshop_humidifier_1_update
    alias: 'Workshop Humidifier 1: Update'
    mode: queued
    max: 4
    max_exceeded: silent
    trigger:
      - platform: time_pattern
        minutes: '/7'

      - platform: state
        entity_id:
          - input_number.home_target_humidity
          - input_select.home_mode
    condition:
      - condition: template
        value_template: >
          {{ states('humidifier.workshop_humidifier_1') not in ['unavailable', 'unknown'] }}

      - condition: state
        entity_id:
          - input_boolean.climate_control
          - input_boolean.workshop_humidifier_control
        state: 'on'
    action:
      - if:
          - condition: state
            entity_id: sensor.workshop_humidifier_target_mode
            state: 'off'
        then:
          - if:
              - condition: state
                entity_id: humidifier.workshop_humidifier_1
                state: 'on'
            then:
              - service: humidifier.turn_off
                entity_id: humidifier.workshop_humidifier_1
        else:
          - if:
              - condition: state
                entity_id: humidifier.workshop_humidifier_1
                state: 'off'
            then:
              - service: humidifier.turn_on
                entity_id: humidifier.workshop_humidifier_1

              - wait_template: >
                  {{ is_state('humidifier.workshop_humidifier_1', 'on') }}
                timeout:
                  seconds: 15
                continue_on_timeout: false

          - if:
              - condition: template
                value_template: >
                  {{ state_attr('humidifier.workshop_humidifier_1', 'mode') != states('sensor.workshop_humidifier_target_mode') }}
            then:
              - service: humidifier.set_mode
                entity_id: humidifier.workshop_humidifier_1
                data:
                  mode: >-
                    {{ states('sensor.workshop_humidifier_target_mode') }}

  - id: workshop_humidifier_2_update
    alias: 'Workshop Humidifier 2: Update'
    mode: queued
    max: 4
    max_exceeded: silent
    trigger:
      - platform: time_pattern
        minutes: '/7'

      - platform: state
        entity_id:
          - input_number.home_target_humidity
          - input_select.home_mode
    condition:
      - condition: template
        value_template: >
          {{ states('humidifier.workshop_humidifier_2') not in ['unavailable', 'unknown'] }}

      - condition: state
        entity_id:
          - input_boolean.climate_control
          - input_boolean.workshop_humidifier_control
        state: 'on'
    action:
      - if:
          - condition: state
            entity_id: sensor.workshop_humidifier_target_mode
            state: 'off'
        then:
          - if:
              - condition: state
                entity_id: humidifier.workshop_humidifier_2
                state: 'on'
            then:
              - service: humidifier.turn_off
                entity_id: humidifier.workshop_humidifier_2
        else:
          - if:
              - condition: state
                entity_id: humidifier.workshop_humidifier_2
                state: 'off'
            then:
              - service: humidifier.turn_on
                entity_id: humidifier.workshop_humidifier_2

              - wait_template: >
                  {{ is_state('humidifier.workshop_humidifier_2', 'on') }}
                timeout:
                  seconds: 15
                continue_on_timeout: false

          - if:
              - condition: template
                value_template: >
                  {{ state_attr('humidifier.workshop_humidifier_2', 'mode') != states('sensor.workshop_humidifier_target_mode') }}
            then:
              - service: humidifier.set_mode
                entity_id: humidifier.workshop_humidifier_2
                data:
                  mode: >-
                    {{ states('sensor.workshop_humidifier_target_mode') }}
