input_boolean:
  bedroom_airing_warm:
    name: Bedroom Airing Warm
    initial: false

  bedroom_airing_cold:
    name: Bedroom Airing Cold
    initial: false

  bedroom_intake_fan_control:
    name: Bedroom Intake Fan Control
    icon: mdi:refresh-auto

template:
  sensor:
    - unique_id: sensor.bedroom_intake_fan_target_temperature
      name: 'Bedroom Intake Fan: Target temperature'
      device_class: temperature
      unit_of_measurement: °C
      state_class: measurement
      state: >
        {% set v = 5 %}

        {% set indoor_temperature = states('sensor.bedroom_temperature')|float(0) %}
        {% set outdoor_temperature = states('sensor.outside_temperature')|float(0) %}

        {% if outdoor_temperature >= 5 %}
          {% set v = 1 %}
        {% endif %}

        {% if is_state('input_select.home_mode', 'Day') %}
          {% if is_state('binary_sensor.bedroom_desk_occupancy', 'on') and outdoor_temperature < 20 %}
            {% set v = 25 %}
          {% endif %}
        {% endif %}

        {% if is_state('input_select.home_mode', 'Night') %}
          {% if indoor_temperature < 21 and outdoor_temperature < 10 %}
            {% set v = 15 %}
          {% endif %}
        {% endif %}

        {% if is_state('input_select.home_mode', 'Vacation') %}
          {% set v = 7 %}
        {% endif %}

        {% if is_state('input_boolean.bedroom_airing_warm', 'on') %}
          {% set v = 20 %}
        {% elif is_state('input_boolean.bedroom_airing_cold', 'on') %}
          {% set v = 1 %}
        {% endif %}

        {% if is_state('input_select.washing_machine_status', 'Running') %}
          {% set v = 1 %}
        {% endif %}

        {{ v }}

    - unique_id: sensor.bedroom_intake_fan_target_fan_speed
      name: 'Bedroom Intake Fan: Target fan speed'
      icon: mdi:fan-auto
      state: >
        {% set v = 1 %}

        {% set co2_level = states('sensor.bedroom_co2')|int(0) %}
        {% set outdoor_temperature = states('sensor.bedroom_intake_fan_outdoor_temperature')|float(0) %}

        {% if is_state('input_select.home_mode', 'Day') %}
          {% if co2_level > 750 %}
            {% set v = 6 %}
          {% elif co2_level > 640 %}
            {% set v = 5 %}
          {% elif co2_level > 620 %}
            {% set v = 4 %}
          {% elif co2_level > 590 %}
            {% set v = 3 %}
          {% elif co2_level > 540 %}
            {% set v = 2 %}
          {% endif %}

          {# очень холодно зимой #}
          {% if outdoor_temperature < -10 and is_state('binary_sensor.bedroom_desk_occupancy', 'on') %}
            {% set v = max(v - 1, 1) %}
          {% endif %}
        {% endif %}

        {% if is_state('input_select.home_mode', 'Night') %}
          {% if co2_level > 600 %}
            {% set v = 4 %}
          {% elif co2_level > 550 %}
            {% set v = 3 %}
          {% elif co2_level > 500 %}
            {% set v = 2 %}
          {% endif %}

          {% if is_state('input_boolean.bedroom_humidifier_control', 'off') %}
            {% set v = v + 1 %}  {# больше шума для жены :) #}
          {% endif %}
        {% endif %}

        {% if is_state('input_select.home_mode', 'Vacation') %}
          {% set v = 1 %}
        {% endif %}

        {% if is_state('switch.bedroom_intake_fan_recirculation', 'on') %}
          {% set v = 1 %}
        {% endif %}

        {% if is_state('input_boolean.bedroom_airing_warm', 'on') or is_state('input_boolean.bedroom_airing_cold', 'on') %}
          {% set v = 6 %}
        {% endif %}

        {% if outdoor_temperature < -12 and is_state('input_select.washing_machine_status', 'Running') %}
          {% set v = 1 %}
        {% endif %}

        {{ min(v, 6) }}

automation:
  - id: bedroom_intake_fan_update
    alias: 'Bedroom Intake Fan: Update'
    mode: single
    max_exceeded: silent
    trigger:
      - platform: time_pattern
        minutes: '/5'

      - platform: state
        entity_id:
          - binary_sensor.bedroom_desk_occupancy
          - input_select.home_mode
          - input_select.washing_machine_status
          - input_boolean.bedroom_intake_fan_control

      - id: room_airing
        platform: state
        entity_id:
          - input_boolean.bedroom_airing_warm
          - input_boolean.bedroom_airing_cold
        to:
          - 'on'
          - 'off'

      - id: recirculation
        platform: state
        entity_id: switch.bedroom_intake_fan_recirculation
        to:
          - 'on'
          - 'off'

      - platform: state
        entity_id: sensor.ups_status
        from: 'On Battery'
        to: 'Online'
        for:
          seconds: 30
    condition:
      - condition: state
        entity_id: climate.bedroom_intake_fan
        state:
          - 'heat'
          - 'fan_only'
          - 'off'

      - condition: state
        entity_id:
          - input_boolean.climate_control
          - input_boolean.bedroom_intake_fan_control
        state: 'on'
    action:
      - if:
          - condition: trigger
            id: recirculation
        then:
          - delay:
              seconds: 20
        else:
          - delay:
              seconds: 1

      - service: climate.set_fan_mode
        entity_id: climate.bedroom_intake_fan
        data:
          fan_mode: >
            {{ states('sensor.bedroom_intake_fan_target_fan_speed') }}

      - delay:
          seconds: 2

      - service: climate.set_temperature
        entity_id: climate.bedroom_intake_fan
        data:
          temperature: >
            {{ states('sensor.bedroom_intake_fan_target_temperature')|float(20) }}
          hvac_mode: heat

  - id: bedroom_airing_swap_modes
    alias: 'Bedroom Airing: Swap modes'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.bedroom_airing_warm
          - input_boolean.bedroom_airing_cold
        to: 'on'
    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {%- if trigger.from_state.entity_id == 'input_boolean.bedroom_airing_warm' -%}
              input_boolean.bedroom_airing_cold
            {%- else -%}
              input_boolean.bedroom_airing_warm
            {%- endif -%}

  - id: bedroom_airing_auto_turn_off
    alias: 'Bedroom Airing: Auto turn off'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.bedroom_airing_warm
          - input_boolean.bedroom_airing_cold
        to: 'on'
        for:
          minutes: 40
    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {{ trigger.from_state.entity_id }}

switch:
  - platform: template
    switches:
      bedroom_airing:
        unique_id: switch.bedroom_airing
        friendly_name: Bedroom Airing
        icon_template: mdi:hair-dryer-outline
        value_template: >
          {{
            is_state('input_boolean.bedroom_airing_cold', 'on') or
            is_state('input_boolean.bedroom_airing_warm', 'on')
          }}
        turn_on:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.bedroom_airing_cold
        turn_off:
          - service: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.bedroom_airing_cold
                - input_boolean.bedroom_airing_warm
