input_boolean:
  workshop_airing_warm:
    name: Workshop Airing Warm
    initial: false

  workshop_airing_cold:
    name: Workshop Airing Cold
    initial: false

  workshop_intake_fan_control:
    name: Workshop Intake Fan Control
    icon: mdi:refresh-auto

timer:
  workshop_intake_fan_restart:
    name: 'Workshop Intake Fan: Restart'
    duration:
      minutes: 60

template:
  sensor:
    - unique_id: sensor.workshop_intake_fan_target_temperature
      name: 'Workshop Intake Fan: Target temperature'
      device_class: temperature
      unit_of_measurement: °C
      state_class: measurement
      state: >
        {% set v = 7 %}

        {% set indoor_temperature = states('sensor.workshop_temperature')|float(0) %}
        {% set outdoor_temperature = states('sensor.outside_temperature')|float(0) %}

        {% if outdoor_temperature >= 7 %}
          {% set v = 0 %}
        {% endif %}

        {% if is_state('binary_sensor.workshop_occupancy', 'on') and outdoor_temperature < 15 %}
          {% if indoor_temperature < 20 %}
            {% set v = 24  %}
          {% elif indoor_temperature < 22 %}
            {% set v = 22 %}
          {% elif indoor_temperature < 24 %}
            {% set v = 20 %}
          {% endif %}
        {% endif %}

        {% if is_state('input_boolean.workshop_airing_warm', 'on') %}
          {% set v = 23 %}
        {% elif is_state('input_boolean.workshop_airing_cold', 'on') %}
          {% set v = 0 %}
        {% endif %}

        {% if outdoor_temperature < 0 %}
          {% if is_state('climate.workshop_ac', 'heat') %}
            {% set v = v - 10 %}
          {% endif %}
        {% endif %}

        {{ v }}

    - unique_id: sensor.workshop_intake_fan_target_fan_speed
      name: 'Workshop Intake Fan: Target fan speed'
      icon: mdi:fan-auto
      state: >
        {% set v = 1 %}

        {% set co2_level = states('sensor.workshop_co2')|int(0) %}
        {% set indoor_temperature = states('sensor.workshop_temperature')|float(0) %}
        {% set outdoor_temperature = states('sensor.outside_temperature')|float(0) %}

        {% if is_state('input_select.home_mode', 'Day') %}
          {% if co2_level > 750 %}
           {% set v = 6 %}
          {% elif co2_level > 700 %}
            {% set v = 5 %}
          {% elif co2_level > 640 %}
            {% set v = 4 %}
          {% elif co2_level > 590 %}
            {% set v = 3 %}
          {% elif co2_level > 540 %}
            {% set v = 2 %}
          {% endif %}

          {% if is_state('binary_sensor.workshop_occupancy', 'off') and outdoor_temperature < 0 %}
            {% set v = 1 %}
          {% endif %}

          {% if not co2_level and is_state('binary_sensor.workshop_occupancy', 'on') %}
            {% set v = 3 %}
          {% endif %}
        {% endif %}

        {% if is_state('input_boolean.workshop_airing_warm', 'on') or is_state('input_boolean.workshop_airing_cold', 'on') %}
          {% set v = 6 %}
        {% endif %}

        {% if is_state('switch.workshop_intake_fan_recirculation', 'on') %}
          {% set v = 1 %}
        {% endif %}

        {% if outdoor_temperature < -5 %}
          {% if is_state('input_select.washing_machine_status', 'Running') %}
            {% set v = 1 %}
          {% endif %}
        {% endif %}

        {% if outdoor_temperature < -12 %}
          {% if is_state('input_select.home_mode', 'Night') or is_state('input_boolean.scene_sleepy_mood', 'on') %}
            {% set v = 0 %}
          {% endif %}
        {% endif %}

        {{ v }}

automation:
  - id: workshop_intake_fan_update
    alias: 'Workshop Intake Fan: Update'
    mode: single
    max_exceeded: silent
    trigger:
      - platform: time_pattern
        minutes: '/5'

      - platform: state
        entity_id:
          - input_select.home_mode
          - input_select.washing_machine_status
          - input_boolean.workshop_intake_fan_control
          - binary_sensor.workshop_occupancy

      - id: room_airing
        platform: state
        entity_id:
          - input_boolean.workshop_airing_warm
          - input_boolean.workshop_airing_cold
        to:
          - 'on'
          - 'off'

      - id: recirculation
        platform: state
        entity_id: switch.workshop_intake_fan_recirculation
        to:
          - 'on'
          - 'off'

      - platform: state
        entity_id: sensor.ups_status
        from: 'On Battery'
        to: 'Online'
        for:
          seconds: 60
    condition:
      - condition: state
        entity_id: climate.workshop_intake_fan
        state:
          - 'heat'
          - 'fan_only'
          - 'off'

      - condition: state
        entity_id:
          - input_boolean.climate_control
          - input_boolean.workshop_intake_fan_control
        state: 'on'
    action:
      - if:
          - condition: trigger
            id: recirculation
        then:
          - delay:
              seconds: 20
        else:
          - delay:
              seconds: 1

      - service: climate.set_fan_mode
        entity_id: climate.workshop_intake_fan
        data:
          fan_mode: >
            {{ max(1, states('sensor.workshop_intake_fan_target_fan_speed')|int(0)) }}

      - delay:
          seconds: 1

      - service: climate.set_temperature
        entity_id: climate.workshop_intake_fan
        data:
          temperature: >
            {{ states('sensor.workshop_intake_fan_target_temperature')|float(20) }}

      - if:
          - condition: state
            entity_id: sensor.workshop_intake_fan_target_fan_speed
            state: '0'

          - condition: state
            entity_id: climate.workshop_intake_fan
            state:
              - heat
              - fan_only

          - condition: state
            entity_id: timer.workshop_intake_fan_restart
            state: idle
        then:
          - delay:
              seconds: 1

          - service: climate.set_hvac_mode
            entity_id: climate.workshop_intake_fan
            data:
              hvac_mode: 'off'

      - if:
          - not:
              - condition: state
                entity_id: sensor.workshop_intake_fan_target_fan_speed
                state: '0'

          - condition: state
            entity_id: climate.workshop_intake_fan
            state: 'off'
        then:
          - delay:
              seconds: 1

          - service: timer.start
            entity_id: timer.workshop_intake_fan_restart

          - service: climate.set_hvac_mode
            entity_id: climate.workshop_intake_fan
            data:
              hvac_mode: 'heat'

  - id: workshop_airing_swap_modes
    alias: 'Workshop Airing: Swap modes'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.workshop_airing_warm
          - input_boolean.workshop_airing_cold
        to: 'on'
    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {%- if trigger.from_state.entity_id == 'input_boolean.workshop_airing_warm' -%}
              input_boolean.workshop_airing_cold
            {%- else -%}
              input_boolean.workshop_airing_warm
            {%- endif -%}

  - id: workshop_airing_auto_turn_off
    alias: 'Workshop Airing: Auto turn off'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.workshop_airing_warm
          - input_boolean.workshop_airing_cold
        to: 'on'
        for:
          minutes: 35
    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {{ trigger.from_state.entity_id }}

switch:
  - platform: template
    switches:
      workshop_airing:
        unique_id: switch.workshop_airing
        friendly_name: Workshop Airing
        icon_template: mdi:hair-dryer-outline
        value_template: >
          {{
            is_state('input_boolean.workshop_airing_cold', 'on') or
            is_state('input_boolean.workshop_airing_warm', 'on')
          }}
        turn_on:
          - if:
              - condition: numeric_state
                entity_id: sensor.workshop_temperature
                above: 25.5
            then:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.workshop_airing_cold
            else:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.workshop_airing_warm
        turn_off:
          - service: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.workshop_airing_cold
                - input_boolean.workshop_airing_warm
