automation:
  - id: bathroom_light_turn_on_motion
    alias: 'Bathroom Light: Turn on (motion)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: light.is_off
        target:
          entity_id: light.bathroom_main
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.dim_light
                state: 'on'
            sequence:
              - action: light.turn_on
                entity_id: light.bathroom_main
                data:
                  brightness_pct: 17

          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Day
            sequence:
              - action: light.turn_on
                entity_id: light.bathroom_main
                data:
                  brightness_pct: 100

  - id: bathroom_light_turn_on_night_fallback
    alias: 'Bathroom Light: Turn on (night fallback)'
    description: Включение света в ванной ночью при недоступности лент подсветки
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.bathroom_motion
          - binary_sensor.hallway_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Night

      - condition: switch.is_off
        target:
          entity_id: input_boolean.waking_up

      - condition: state
        entity_id: group.bathroom_path_lights
        state: unavailable
    actions:
      - action: light.turn_on
        entity_id: light.bathroom_main
        data:
          brightness_pct: 7

  - id: bathroom_light_turn_off_occupancy_cleared
    alias: 'Bathroom Light: Turn off (occupancy cleared)'
    triggers:
      - trigger: occupancy.cleared
        target:
          area_id: bathroom
        options:
          for:
            minutes: 2
          behavior: all
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.bathroom_light_control
          - group.bathroom_lights
        state: 'on'

      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: Bedtime

      - condition: motion.is_not_detected
        note: Костыль для редкого случая, когда одновременно пропадает присутствие и начинается движение
        target:
          entity_id: binary_sensor.bathroom_motion

      - not:
          - condition: state
            entity_id: binary_sensor.bedroom_occupancy
            state: unavailable
    actions:
      - action: light.turn_off
        entity_id: group.bathroom_lights
        data:
          transition: 6

  - id: bathroom_light_turn_off_no_occupancy
    alias: 'Bathroom Light: Turn off (no occupancy)'
    mode: restart
    triggers:
      - trigger: state
        entity_id: group.bathroom_lights
        from: 'off'
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.bathroom_light_control
        state: 'on'
    actions:
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.bathroom_occupancy
            to: 'on'
        timeout:
          minutes: 1

      - condition: state
        entity_id: binary_sensor.bathroom_occupancy
        state: 'off'

      - if:
          - condition: motion.is_detected
            target:
              entity_id: binary_sensor.bathroom_motion
        then:
          - wait_for_trigger:
              - trigger: motion.cleared
                target:
                  entity_id: binary_sensor.bathroom_motion
            timeout:
              minutes: 1

          - condition: state
            entity_id: binary_sensor.bathroom_occupancy
            state: 'off'

      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: Bedtime

      - action: light.turn_off
        entity_id: group.bathroom_lights
        data:
          transition: 6

  - id: bathroom_light_control_turn_on
    alias: 'Bathroom Light Control: Turn on'
    triggers:
      - trigger: state
        entity_id: group.bathroom_lights
        to: 'off'
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_control
        state: 'off'
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.bathroom_light_control

  - id: bathroom_light_control_turn_off
    alias: 'Bathroom Light Control: Turn off'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Не выключай свет в ванной
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_control
        state: 'on'
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.bathroom_light_control

  - id: bathroom_bathtub_light_turn_on
    alias: 'Bathroom Bathtub Light: Turn on'
    triggers:
      - trigger: occupancy.detected
        target:
          entity_id: binary_sensor.bathroom_bathtub_occupancy
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: light.is_off
        target:
          entity_id: light.bathroom_bathtub

      - condition: state
        entity_id: binary_sensor.dim_light
        state: 'off'
    actions:
      - action: light.turn_on
        entity_id: light.bathroom_bathtub

  - id: bathroom_light_turn_off_failsafe
    alias: 'Bathroom Light: Turn off (failsafe)'
    triggers:
      - trigger: state
        entity_id: group.bathroom_lights
        to: 'on'
        for:
          hours: 12
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: group.bathroom_lights

input_boolean:
  bathroom_light_control:
    name: 'Allow automatic light control (bathroom)'
    initial: true
    icon: mdi:home-lightbulb-outline

group:
  bathroom_lights:
    name: Bathroom Lights
    entities:
      - light.bathroom_main
      - light.bathroom_mirror
      - light.bathroom_bathtub
