automation:
  - id: bedroom_light_on_motion_day
    alias: 'Bedroom Light: On (motion, day)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.bedroom_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: or
        conditions:
          - and:
              - condition: time
                after: '13:00:00'
                before: '04:00:00'

              - condition: numeric_state
                entity_id: sensor.illuminance_north_side
                below: 200

          - condition: state
            entity_id: cover.bedroom
            state: closed

      - condition: state
        entity_id:
          - binary_sensor.bedroom_bed_occupancy
          - group.bedroom_lights
        state: 'off'
    actions:
      - action: light.turn_on
        target:
          entity_id:
            - light.bedroom_bed
            - light.bedroom_moon
        data:
          rgb_color: [10, 214, 255]
          brightness_pct: 100

      - action: light.turn_on
        target:
          entity_id:
            - light.bedroom_cat
            - light.bedroom_string
        data:
          color_temp_kelvin: 2700
          brightness_pct: 100

  - id: bedroom_light_off_no_occupancy_day
    alias: 'Bedroom Light: Off (no occupancy, day)'
    mode: restart
    triggers:
      - trigger: state
        entity_id: group.bedroom_lights
        from: 'off'
        to: 'on'
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - wait_for_trigger:
          - trigger: occupancy.detected
            target:
              area_id: bedroom
        timeout:
          minutes: 1

      - condition: state
        entity_id:
          - binary_sensor.bedroom_occupancy
          - binary_sensor.bedroom_bed_occupancy
        state: 'off'

      - action: light.turn_off
        target:
          entity_id: group.bedroom_lights

  - id: bedroom_bed_light_on_motion_night
    alias: 'Bedroom Bed Light: On (motion, night)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.bedroom_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Night

      - condition: light.is_off
        target:
          entity_id: light.bedroom_bed
    actions:
      - action: light.turn_on
        target:
          entity_id: light.bedroom_bed
        data:
          color_name: red
          brightness_pct: 30

  - id: bedroom_main_light_off_occupancy_cleared_day
    alias: 'Bedroom Main Light: Off (occupancy cleared, day)'
    triggers:
      - trigger: occupancy.cleared
        target:
          area_id: bedroom
        options:
          for:
            minutes: 3
          behavior: all
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - light.bedroom_main
        state: 'on'

      - not:
          - and:
              - condition: state
                entity_id: input_select.ironing_board_room
                state: Bedroom

              - condition: state
                entity_id: switch.ironing_board_socket
                state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - action: light.turn_off
        target:
          entity_id: light.bedroom_main

  - id: bedroom_bed_light_off
    alias: 'Bedroom Bed Light: Off'
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        to: Day

      - trigger: occupancy.detected
        target:
          entity_id: binary_sensor.bedroom_bed_occupancy
        options:
          for:
            seconds: 10

      - trigger: motion.cleared
        target:
          entity_id: binary_sensor.bedroom_motion
        options:
          for:
            seconds: 20
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: occupancy.is_not_detected
        target:
          entity_id: binary_sensor.bedroom_occupancy

      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: Bedtime

      - condition: light.is_on
        target:
          entity_id: light.bedroom_bed
    action:
      - action: light.turn_off
        target:
          entity_id: light.bedroom_bed

  - id: bedroom_aux_light_off_day
    alias: 'Bedroom Aux Light: Off (day)'
    triggers:
      - trigger: occupancy.cleared
        target:
          area_id: bedroom
        options:
          for:
            seconds: 15
          behavior: all

      - trigger: light.turned_on
        target:
          entity_id: light.bedroom_main

      - trigger: state
        entity_id: input_select.home_mode
        to: Day
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: light.is_on
        target:
          entity_id:
            - light.bedroom_moon
            - light.bedroom_bed
            - light.bedroom_cat
            - light.bedroom_string

      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - action: light.turn_off
        target:
          entity_id:
            - light.bedroom_moon
            - light.bedroom_bed
            - light.bedroom_cat
            - light.bedroom_string

  - id: bedroom_moon_light_charger_turn_on
    alias: 'Bedroom Moon Light Charger: Turn on'
    triggers:
      - trigger: time
        at: '18:00'
    actions:
      - action: switch.turn_on
        entity_id: switch.bedroom_moon_light_charger

  - id: bedroom_moon_light_charger_turn_off
    alias: 'Bedroom Moon Light Charger: Turn off'
    triggers:
      - trigger: state
        entity_id: switch.bedroom_moon_light_charger
        to: 'on'
        for:
          hours: 1
          minutes: 30

      - trigger: homeassistant
        event: start
    conditions:
      - condition: switch.is_on
        target:
          entity_id: switch.bedroom_moon_light_charger
    actions:
      - action: switch.turn_off
        entity_id: switch.bedroom_moon_light_charger

  - id: bedroom_light_turn_off_failsafe
    alias: 'Bedroom Light: Turn off (failsafe)'
    triggers:
      - trigger: state
        entity_id: group.bedroom_lights
        to: 'on'
        for:
          hours: 12
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: group.bedroom_lights

group:
  bedroom_lights:
    name: Bedroom Lights
    entities:
      - light.bedroom_main
      - light.bedroom_bed
      - light.bedroom_moon
      - light.bedroom_cat
      - light.bedroom_string
