automation:
  - id: closet_light_turn_on
    alias: 'Closet Light: Turn on'
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.closet_door

      - trigger: state
        entity_id: binary_sensor.closet_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.closet_light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: light.is_off
        target:
          entity_id: light.closet

      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Bedtime
    actions:
      - action: light.turn_on
        entity_id: light.closet

  - id: closet_light_turn_off
    alias: 'Closet Light: Turn off'
    triggers:
      - trigger: door.closed
        target:
          entity_id: binary_sensor.closet_door

      - trigger: motion.cleared
        target:
          entity_id: binary_sensor.closet_motion
        options:
          for:
            minutes: 5
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.closet_light_control
          - light.closet
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: light.closet

  - id: closet_light_control_turn_on
    alias: 'Closet Light Control: Turn on'
    trigger:
      - platform: state
        entity_id: light.closet
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.closet_light_control
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.closet_light_control

  - id: closet_light_control_turn_off
    alias: 'Closet Light Control: Turn off'
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Не выключай свет в кладовке
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.closet_light_control

  - id: closet_light_turn_off_failsafe
    alias: 'Closet Light: Turn off (failsafe)'
    triggers:
      - trigger: state
        entity_id: light.closet
        to: 'on'
        for:
          hours: 3
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: light.closet

input_boolean:
  closet_light_control:
    name: 'Allow automatic light control (closet)'
    initial: true
    icon: mdi:home-lightbulb-outline
