automation:
  - id: entrance_light_turn_off
    alias: 'Entrance Light: Turn off'
    triggers:
      - trigger: motion.cleared
        target:
          entity_id: binary_sensor.entrance_motion
        options:
          for:
            minutes: 15
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - light.entrance
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: light.entrance

  - id: hallway_light_turn_off_failsafe
    alias: 'Hallway Light: Turn off (failsafe)'
    triggers:
      - trigger: state
        entity_id:
          - light.entrance
          - light.hallway
        to: 'on'
        for:
          hours: 6
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id:
          - light.entrance
          - light.hallway

template:
  - light:
      - unique_id: light.entrance
        default_entity_id: light.entrance
        name: Entrance Light
        icon: bha:ceiling-lamp
        state: >
          {{ is_state('switch.hallway_light_switch_left', 'on') }}
        availability: >
          {{ states('switch.hallway_light_switch_left') in ['on', 'off'] }}
        turn_on:
          - action: switch.turn_on
            entity_id: switch.hallway_light_switch_left
        turn_off:
          - action: switch.turn_off
            entity_id: switch.hallway_light_switch_left

      - unique_id: light.hallway
        default_entity_id: light.hallway
        name: Hallway Light
        icon: bha:ceiling-lamp
        state: >
          {{ is_state('switch.hallway_light_switch_right', 'on') }}
        availability: >
          {{ states('switch.hallway_light_switch_right') in ['on', 'off'] }}
        turn_on:
          - action: switch.turn_on
            entity_id: switch.hallway_light_switch_right
        turn_off:
          - action: switch.turn_off
            entity_id: switch.hallway_light_switch_right
