automation:
  - id: hallway_light_turn_off_welcome_home
    alias: 'Hallway Light: Turn off (welcome home)'
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_motion
        to: 'off'
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id:
          - light.hallway
          - light.entrance
        match: any
        state: 'on'

      - condition: state
        entity_id: timer.scene_welcome_home
        state: active
    action:
      - service: light.turn_off
        entity_id:
          - light.hallway
          - light.entrance

  - id: entrance_light_turn_off
    alias: 'Entrance Light: Turn off'
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_motion
        to: 'off'
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id: light.entrance
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.entrance

template:
  - light:
      - unique_id: light.entrance
        default_entity_id: light.entrance
        name: Entrance Light
        icon: bha:ceiling-lamp
        state: >
          {{ is_state('switch.hallway_light_switch_left', 'on') }}
        availability: >
          {{ states('switch.hallway_light_switch_left') in ['on', 'off'] }}
        turn_on:
          - action: switch.turn_on
            entity_id: switch.hallway_light_switch_left
        turn_off:
          - action: switch.turn_off
            entity_id: switch.hallway_light_switch_left

      - unique_id: light.hallway
        default_entity_id: light.hallway
        name: Hallway Light
        icon: bha:ceiling-lamp
        state: >
          {{ is_state('switch.hallway_light_switch_right', 'on') }}
        availability: >
          {{ states('switch.hallway_light_switch_right') in ['on', 'off'] }}
        turn_on:
          - action: switch.turn_on
            entity_id: switch.hallway_light_switch_right
        turn_off:
          - action: switch.turn_off
            entity_id: switch.hallway_light_switch_right
