automation:
  - id: kitchen_light_turn_on_full
    alias: 'Kitchen Light: Turn on (full)'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id:
          - light.kitchen_main
          - binary_sensor.dim_light
          - input_boolean.scene_sleepy_mood
        state: 'off'

      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation

      - or:
          - condition: state
            entity_id: light.kitchen_mood
            state: 'off'

          - condition: template
            value_template: >
              {{ state_attr('light.kitchen_worktop', 'brightness')|int(0) in (0, 50) }}
    action:
      - service: light.turn_on
        entity_id: light.kitchen_worktop
        data:
          brightness: 255

      - service: light.turn_on
        entity_id: light.kitchen_mood

  - id: kitchen_light_turn_on_dimmed
    alias: 'Kitchen Light: Turn on (dimmed)'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'on'
    condition:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.dim_light
        state: 'on'

      - condition: state
        entity_id: light.kitchen_main
        state: 'off'

      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation

      - condition: state
        entity_id: input_boolean.scene_sleepy_mood
        state: 'off'

      - or:
          - condition: state
            entity_id: light.kitchen_mood
            state: 'off'

          - condition: template
            value_template: >
              {{ state_attr('light.kitchen_worktop', 'brightness')|int(0) in (0, 100) }}
    action:
      - service: light.turn_on
        entity_id: light.kitchen_worktop
        data:
          brightness: 100

      - service: light.turn_on
        entity_id: light.kitchen_mood

  - id: kitchen_light_dim_worktop
    alias: 'Kitchen Light: Dim worktop'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupancy
        from: 'on'
        to: 'off'
        for:
          minutes: 4
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - or:
          - condition: state
            entity_id: light.kitchen_main
            state: 'on'

          - condition: template
            value_template: >
              {{ state_attr('light.kitchen_worktop', 'brightness')|int(0) > 250 }}
    action:
      - service: light.turn_on
        entity_id: light.kitchen_worktop
        data:
          brightness: 50

      - service: light.turn_off
        entity_id: light.kitchen_main

  - id: kitchen_light_turn_off
    alias: 'Kitchen Light: Turn off'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupancy
        from: 'on'
        to: 'off'
        for:
          minutes: 10

      - platform: state
        entity_id: binary_sensor.kitchen_motion
        from: 'on'
        to: 'off'
        for:
          hours: 2
    condition:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - group.kitchen_lights
        state: 'on'

      - condition: state
        entity_id: input_boolean.scene_sleepy_mood
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: group.kitchen_lights

light:
  - platform: template
    lights:
      kitchen_main:
        unique_id: kitchen_main_light
        friendly_name: Kitchen Main Light
        value_template: >
          {{ is_state('switch.kitchen_light_switch_right', 'on') }}
        availability_template: >
          {{ states('switch.kitchen_light_switch_right') in ['on', 'off'] }}
        icon_template: bha:ceiling-lamp
        turn_on:
          - service: switch.turn_on
            entity_id: switch.kitchen_light_switch_right
        turn_off:
          - service: switch.turn_off
            entity_id: switch.kitchen_light_switch_right

      kitchen_mood:
        unique_id: kitchen_mood_light
        friendly_name: Kitchen Mood Light
        value_template: >
          {{ is_state('switch.kitchen_light_switch_left', 'on') }}
        availability_template: >
          {{ states('switch.kitchen_light_switch_left') in ['on', 'off'] }}
        icon_template: bha:dome-light
        turn_on:
          - service: switch.turn_on
            entity_id: switch.kitchen_light_switch_left
        turn_off:
          - service: switch.turn_off
            entity_id: switch.kitchen_light_switch_left

  - platform: group
    unique_id: light.kitchen_worktop
    name: Kitchen Worktop Light
    entities:
      - light.kitchen_worktop_left
      - light.kitchen_worktop_right

group:
  kitchen_lights:
    name: Kitchen Lights
    entities:
      - light.kitchen_main
      - light.kitchen_mood
      - light.kitchen_worktop

script:
  kitchen_worktop_right_light_ack_flash:
    alias: 'Kitchen Worktop Right Light: ACK Flash'
    description: Подтверждает команду через мигание светильником над рабочей зоной
    mode: queued
    sequence:
      - if:
          - condition: state
            entity_id: light.kitchen_worktop_right
            state: 'off'
        then:
          - action: light.turn_on
            entity_id: light.kitchen_worktop_right
            data:
              brightness_pct: >
                {{ 20 if is_state('input_select.home_mode', 'Night') else 50 }}
              transition: 0.5

          - delay:
              milliseconds: 500

          - action: light.turn_off
            entity_id: light.kitchen_worktop_right
        else:
          - service: scene.create
            data:
              scene_id: kitchen_worktop_right_light_ack_flash
              snapshot_entities:
                - light.kitchen_worktop_right

          - action: light.turn_on
            entity_id: light.kitchen_worktop_right
            data:
              brightness: >
                {% set brightness = state_attr('light.kitchen_worktop_right', 'brightness')|int(255) %}
                {% if brightness > 127 %}
                  {{ brightness - 100 }}
                {% else %}
                  {{ brightness + 100 }}
                {% endif %}
              transition: 0.5

          - delay:
              milliseconds: 500

          - service: scene.turn_on
            entity_id: scene.kitchen_worktop_right_light_ack_flash
            data:
              transition: 0.5

      - delay:
          milliseconds: 500
