automation:
  - id: living_room_tv_light_turn_on
    alias: 'Living Room TV Light: Turn on'
    trigger:
      - platform: state
        entity_id: media_player.tv
        to: 'on'
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation

      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id: light.living_room_tv
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.living_room_tv
        data:
          brightness_pct: 45

  - id: living_room_tv_light_turn_off
    alias: 'Living Room TV Light: Turn off'
    trigger:
      - platform: state
        entity_id: media_player.tv
        to: 'off'
    condition:
      - condition: numeric_state
        entity_id: sensor.illuminance_south_side
        above: 500

      - condition: state
        entity_id: binary_sensor.winter_bright_light
        state: 'off'

      - condition: state
        entity_id:
          - input_boolean.light_control
          - light.living_room_tv
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.living_room_tv
