automation:
  - id: living_room_main_light_turn_on_day
    alias: 'Living Room Main Light: Turn on (day)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: time
        after: '8:00:00'
        before: '17:00:00'

      - condition: state
        entity_id:
          - binary_sensor.living_room_occupancy
          - binary_sensor.dim_light
          - group.living_room_lights
        state: 'off'

      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.illuminance_south_side
            below: 8500

          - condition: state
            entity_id: cover.living_room
            state: closed

          - condition: state
            entity_id: input_select.season
            state: Winter
    actions:
      - action: light.turn_on
        entity_id: light.living_room_main

  - id: living_room_light_turn_on_ironing
    alias: 'Living Room Light: Turn on (ironing)'
    triggers:
      - trigger: state
        entity_id: switch.ironing_board_socket
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: state
        entity_id: input_select.ironing_board_room
        state: Living Room

      - condition: time
        after: '10:00:00'
        before: '21:00:00'

      - condition: state
        entity_id:
          - binary_sensor.living_room_motion
          - binary_sensor.living_room_occupancy
          - binary_sensor.ironing_board_occupancy
        state: 'on'
        match: any
    actions:
      - action: light.turn_on
        entity_id: light.living_room_main

      - action: light.turn_on
        entity_id: light.living_room_backlight
        data:
          brightness_pct: 100
          color_temp_kelvin: 4200

  - id: living_room_light_turn_off_occupancy_cleared
    alias: 'Living Room Light: Turn off (occupancy cleared)'
    triggers:
      - id: room_occupancy
        trigger: occupancy.cleared
        target:
          entity_id: binary_sensor.living_room_occupancy
        options:
          for:
            minutes: 10

      - id: ironing_board_occupancy
        trigger: occupancy.cleared
        target:
          entity_id: binary_sensor.ironing_board_occupancy
        options:
          for:
            minutes: 5
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - group.living_room_lights
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Night

      - condition: state
        entity_id: binary_sensor.living_room_occupancy
        state: 'off'

      - or:
          - not:
              - condition: trigger
                id: ironing_board_occupancy

          - and:
              - condition: trigger
                id: ironing_board_occupancy

              - not:
                  - and:
                      - condition: state
                        entity_id: input_select.ironing_board_room
                        state: Living Room

                      - condition: state
                        entity_id: switch.ironing_board_socket
                        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: group.living_room_lights

  - id: living_room_light_turn_off_no_occupancy
    alias: 'Living Room Light: Turn off (no occupancy)'
    mode: restart
    triggers:
      - trigger: state
        entity_id: group.living_room_lights
        from: 'off'
        to: 'on'
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - wait_for_trigger:
          - trigger: occupancy.detected
            target:
              entity_id: binary_sensor.living_room_occupancy
        timeout:
          minutes: 1

      - condition: state
        entity_id: binary_sensor.living_room_occupancy
        state: 'off'

      - action: light.turn_off
        entity_id: group.living_room_lights

  - id: living_room_light_turn_off_failsafe
    alias: 'Living Room Light: Turn off (failsafe)'
    triggers:
      - trigger: state
        entity_id: group.living_room_lights
        to: 'on'
        for:
          hours: 16
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: group.living_room_lights

light:
  - platform: group
    unique_id: living_room_backlght
    name: Living Room Backlight
    entities:
      - light.living_room_backlight_1
      - light.living_room_backlight_2
      - light.living_room_backlight_3
      - light.living_room_backlight_4
      - light.living_room_backlight_5
      - light.living_room_backlight_6

group:
  living_room_lights:
    name: Living Room Lights
    entities:
      - light.living_room_main
      - light.living_room_backlight
      - light.living_room_tv
