automation:
  - id: living_room_tv_light_turn_on
    alias: 'Living Room TV Light: Turn on'
    trigger:
      - platform: state
        entity_id: media_player.tv
        to: 'on'
    condition:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: state
        entity_id: light.living_room_tv
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.living_room_tv
        data:
          brightness_pct: 45

  - id: living_room_tv_light_turn_on_pre_meal
    alias: 'Living Room TV Light: Turn on (pre-meal)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_dinner_table_parked
        from: 'off'
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: state
        entity_id: input_boolean.scene_sleepy_mood
        state: 'off'

      - or:
          - condition: time
            after: '12:00:00'
            before: '14:00:00'

          - condition: time
            after: '18:00:00'
            before: '19:30:00'
    actions:
      - service: light.turn_on
        entity_id: light.living_room_tv
        data:
          brightness_pct: 60
