automation:
  - id: porch_light_turn_on_front_door
    alias: 'Porch Light: Turn on (front door)'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id:
          - light.porch
          - light.porch_path_light
        state: 'off'
    action:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Night
        then:
          - service: light.turn_on
            entity_id: light.porch_path_light
            data:
              rgbw_color: [255, 0, 0, 0]
              brightness_pct: 45
        else:
          - service: light.turn_on
            entity_id: light.porch

  - id: porch_light_turn_on
    alias: 'Porch Light: Turn on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.porch_motion
          - binary_sensor.porch_door
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id:
          - light.porch
          - light.porch_path_light
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.porch

  - id: porch_light_turn_off
    alias: 'Porch Light: Turn off'
    trigger:
      - platform: state
        entity_id: binary_sensor.porch_motion
        to: 'off'
        for:
          minutes: 10

      - platform: state
        entity_id: binary_sensor.porch_motion
        to: 'off'
        for:
          minutes: 20
    condition:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: state
        entity_id:
          - light.porch
          - light.porch_path_light
        match: any
        state: 'on'
    action:
      - service: light.turn_off
        entity_id:
          - light.porch
          - light.porch_path_light

light:
  - platform: template
    lights:
      porch:
        unique_id: porch_light
        friendly_name: Porch Light
        value_template: >
          {{ is_state('switch.porch_light_switch', 'on') }}
        availability_template: >
          {{ states('switch.porch_light_switch') in ['on', 'off'] }}
        icon_template: bha:ceiling-lamp
        turn_on:
          - service: switch.turn_on
            entity_id: switch.porch_light_switch
        turn_off:
          - service: switch.turn_off
            entity_id: switch.porch_light_switch
