automation:
  - id: wardrobe_light_turn_on
    alias: 'Wardrobe Light: Turn on'
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.wardrobe_door

      - trigger: state
        entity_id: binary_sensor.wardrobe_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'

      - condition: light.is_off
        target:
          entity_id: light.wardrobe
    actions:
      - action: light.turn_on
        entity_id: light.wardrobe
        data:
          brightness_pct: >
            {%- if is_state('binary_sensor.dim_light', 'on') -%}
              20
            {%- elif is_state('input_select.home_mode', 'Night') -%}
              5
            {%- else -%}
              100
            {%- endif -%}

  - id: wardrobe_light_turn_off
    alias: 'Wardorbe Light: Turn off'
    triggers:
      - trigger: door.closed
        target:
          entity_id: binary_sensor.wardrobe_door
        options:
          for:
            milliseconds: 500

      - id: no_motion
        trigger: motion.cleared
        target:
          entity_id: binary_sensor.wardrobe_motion
        options:
          for:
            minutes: 5
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.wardrobe_light_control
          - light.wardrobe
        state: 'on'
    actions:
      - if:
          - condition: trigger
            id: no_motion
        then:
          - action: light.turn_off
            entity_id: light.wardrobe
            data:
              transition: 10
        else:
          - action: light.turn_off
            entity_id: light.wardrobe

  - id: wardrobe_light_control_turn_on
    alias: 'Wardrobe Light Control: Turn on'
    trigger:
      - platform: state
        entity_id: light.wardrobe
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.wardrobe_light_control
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.wardrobe_light_control

  - id: wardrobe_light_control_turn_off
    alias: 'Wardrobe Light Control: Turn off'
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Не выключай свет в гардеробе
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.wardrobe_light_control

  - id: wardrobe_light_turn_off_failsafe
    alias: 'Wardrobe Light: Turn off (failsafe)'
    triggers:
      - trigger: state
        entity_id: light.wardrobe
        to: 'on'
        for:
          hours: 12
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: light.wardrobe

input_boolean:
  wardrobe_light_control:
    name: 'Allow automatic light control (wardrobe)'
    initial: true
    icon: mdi:home-lightbulb-outline
