automation:
  - id: workshop_main_light_state_update
    alias: 'Workshop Main Light: State update'
    description: Включает правую ленту при включении левой, жене лень нажимать две кнопки
    mode: queued
    triggers:
      - trigger: state
        entity_id: light.workshop_main_1_1
        from:
          - 'on'
          - 'off'
        to:
          - 'on'
          - 'off'
    actions:
      - delay:
          milliseconds: 500

      - condition: template
        value_template: >
          {{ not is_state('light.workshop_main_2_1', trigger.to_state.state) }}

      - if:
          - condition: template
            value_template: >
              {{ trigger.to_state.state == 'on' }}
        then:
          - action: light.turn_on
            entity_id:
              - light.workshop_main_2_1
              - light.workshop_main_2_2
            data:
              transition: 2
              brightness_pct: 100
        else:
          - action: light.turn_off
            entity_id:
              - light.workshop_main_2_1
              - light.workshop_main_2_2

  - id: workshop_light_turn_on
    alias: 'Workshop Light: Turn on'
    max_exceeded: silent
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.workshop_door

      - trigger: state
        entity_id: binary_sensor.workshop_motion
        to: 'on'
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.workshop_light_control
          - binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id:
          - light.workshop_main
          - binary_sensor.workshop_light_suppress_auto_on
        state: 'off'
    actions:
      - if:
          - or:
              - condition: state
                entity_id: binary_sensor.dim_light
                state: 'on'

              - condition: state
                entity_id: input_select.home_mode
                state: Night
        then:
          - action: light.turn_on
            entity_id:
              - light.workshop_main_2_1
              - light.workshop_main_2_2
            data:
              brightness_pct: 1
              transition: 0
        else:
          - action: light.turn_on
            entity_id: light.workshop_main
            data:
              brightness_pct: 100

  - id: workshop_light_turn_off_occupancy_cleared
    alias: 'Workshop Light: Turn off (occupancy cleared)'
    mode: restart
    triggers:
      - trigger: occupancy.cleared
        target:
          entity_id: binary_sensor.workshop_occupancy
        options:
          for:
            minutes: 10

      - id: early
        trigger: occupancy.cleared
        target:
          entity_id: binary_sensor.workshop_occupancy
        options:
          for:
            seconds: 20
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.workshop_light_control
          - light.workshop_main
        state: 'on'

      - or:
          - not:
              - condition: trigger
                id: early

          - and:
              - condition: trigger
                id: early

              - condition: template
                value_template: >
                  {{ (now() - states.light.workshop_main.last_changed).total_seconds() < 300 }}
    actions:
      - if:
          - condition: motion.is_detected
            target:
              entity_id: binary_sensor.workshop_motion
        then:
          - wait_for_trigger:
              - trigger: motion.cleared
                target:
                  entity_id: binary_sensor.workshop_motion
            timeout:
              minutes: 2
            continue_on_timeout: false

      - action: light.turn_off
        entity_id: light.workshop_main
        data:
          transition: 10

  - id: workhop_light_turn_off_no_occupancy
    alias: 'Workshop Light: Turn off (no occupancy)'
    mode: restart
    triggers:
      - trigger: light.turned_on
        target:
          entity_id: light.workshop_main
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.workshop_light_control
        state: 'on'
    actions:
      - wait_for_trigger:
          - trigger: occupancy.detected
            target:
              entity_id: binary_sensor.workshop_occupancy
        timeout:
          minutes: 1

      # если поймали присутствие - то автоматика выключения будет по другому триггеру
      - if:
          - condition: occupancy.is_detected
            target:
              entity_id: binary_sensor.workshop_occupancy
        then:
          stop: Occupancy detected

      - condition: state
        note: Доступность датчика присутствия
        entity_id: binary_sensor.workshop_occupancy
        state: 'off'

      - if:
          - condition: motion.is_detected
            target:
              entity_id: binary_sensor.workshop_motion
        then:
          - wait_for_trigger:
              - trigger: motion.cleared
                target:
                  entity_id: binary_sensor.workshop_motion
            timeout:
              minutes: 2
            continue_on_timeout: false

      - action: light.turn_off
        entity_id: light.workshop_main
        data:
          transition: 10

  - id: workshop_light_turn_off_door_closed
    alias: 'Workshop Light: Turn off (door closed)'
    triggers:
      - trigger: door.closed
        target:
          entity_id: binary_sensor.workshop_door
    conditions:
      - condition: state
        entity_id:
          - input_boolean.light_control
          - input_boolean.workshop_light_control
          - light.workshop_main
        state: 'on'
    actions:
      - if:
          - condition: numeric_state
            entity_id: light.workshop_main
            attribute: brightness
            below: 40
        then:
          - action: light.turn_off
            entity_id: light.workshop_main
            data:
              transition: 0
        else:
          - action: light.turn_off
            entity_id: light.workshop_main
            data:
              transition: 4

  - id: workshop_light_control_turn_on
    alias: 'Workshop Light Control: Turn on'
    trigger:
      - platform: state
        entity_id: light.workshop_main
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.workshop_light_control
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.workshop_light_control

  - id: workshop_light_control_turn_off
    alias: 'Workshop Light Control: Turn off'
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Не выключай свет в мастерской
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.workshop_light_control

  - id: workshop_light_turn_off_failsafe
    alias: 'Workshop Light: Turn off (failsafe)'
    triggers:
      - trigger: state
        entity_id: light.workshop_main
        to: 'on'
        for:
          hours: 16
    conditions:
      - condition: state
        entity_id: input_boolean.light_control
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: light.workshop_main

input_boolean:
  workshop_light_control:
    name: 'Allow automatic light control (workshop)'
    initial: true
    icon: mdi:home-lightbulb-outline

light:
  - platform: group
    unique_id: workshop_main_light
    name: Workshop Main Light
    entities:
      - light.workshop_main_1_1
      - light.workshop_main_1_2
      - light.workshop_main_2_1
      - light.workshop_main_2_2

group:
  workshop_lights:
    name: Workshop Lights
    entities:
      - light.workshop_main

template:
  - triggers:
      - id: night_ended
        trigger: state
        entity_id: input_select.home_mode
        from: Night

      - trigger: state
        entity_id: binary_sensor.workshop_door
        from: 'off'
        to: 'on'
        for:
          seconds: 3

      - trigger: state
        entity_id: binary_sensor.workshop_motion
        to: 'on'
    binary_sensor:
      name: Workshop Light Suppress Auto On
      unique_id: binary_sensor.workshop_light_suppress_auto_on
      state: >-
        {{ is_state('binary_sensor.workshop_door', 'off') and trigger.id == 'night_ended' }}
      auto_off:
        hours: 1
