# https://www.elektroda.com/rtvforum/topic4091325.html
packages:
  base: !include ../common/ln882x.yaml
  bl0937: !include ../common/bl0937.yaml

substitutions:
  relay_restore_mode: RESTORE_DEFAULT_OFF
  power_led: 'true'
  bl0937_sel_pin: PB6
  bl0937_sel_pin_inverted: 'true'
  bl0937_cf_pin: PB4
  bl0937_cf1_pin: PB5
  bl0937_current_resistor: 0.00102
  bl0937_voltage_divider: 1502.5

esphome:
  friendly_name: BSD33 Smart Plug
  name: bsd33-plug
  model: BSD33 Smart Plug (LN882H)

  on_boot:
    priority: -100.0
    then:
      - if:
          condition:
            - switch.is_on: relay
            - lambda: return ${power_led};
          then:
            - light.turn_on: push_button_led

logger:
  baud_rate: 0 # иначе будет тускло светиться диодик

binary_sensor:
  - id: push_button
    platform: gpio
    pin: PA7
    on_press:
      switch.toggle: relay

light:
  - id: push_button_led
    platform: status_led
    pin:
      number: PA6
      inverted: true

switch:
  - id: relay
    name: ''
    platform: gpio
    pin: PB3
    device_class: outlet
    restore_mode: $relay_restore_mode
    on_turn_on:
      - if:
          condition:
            - lambda: return ${power_led};
          then:
            - light.turn_on: push_button_led
    on_turn_off:
      - light.turn_off: push_button_led
