packages:
  base: !include ../common/base.yaml

esphome:
  name: midea-ac
  model: MSAG1-??N8C2 / ESP8266

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:
  baud_rate: 0

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

remote_transmitter:
  pin: 4
  carrier_duty_percent: 50%

climate:
  - platform: midea
    name: $device_name
    autoconf: true
    beeper: false
    supported_swing_modes:
      - VERTICAL
    outdoor_temperature:
      name: $device_name Outdoor Temperature

button:
  - platform: template
    name: $device_name Display Toggle
    on_press:
      - midea_ac.display_toggle:

sensor:
  - id: temperature
    platform: homeassistant
    entity_id: $temperature_sensor
    internal: true
    filters:
      - throttle: 10s
      - heartbeat: 30s
      - debounce: 1s
    on_value:
      midea_ac.follow_me:
        temperature: !lambda |-
          return x;
        beeper: false
