packages:
  base: !include ../common/base.yaml

esphome:
  name: midea-ac
  model: MSAG1-??N8C2 / ESP8266

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:
  baud_rate: 0

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

climate:
  - platform: midea
    name: $device_name
    autoconf: true
    beeper: false
    supported_swing_modes:
      - VERTICAL
    outdoor_temperature:
      name: $device_name Outdoor Temperature
