packages:
  base: !include ../common/base.yaml
  senseair_s9: !include ../common/senseair_s8.yaml

esphome:
  name: senseair-s8

esp8266:
  board: esp01_1m
  restore_from_flash: true

substitutions:
  device_name: Senseair S8
  senseair_s8_sensor_name: Senseair S8
  senseair_s8_rx_pin: '4'
  senseair_s8_tx_pin: '0'
