packages:
  base: !include ../common/base.yaml

esphome:
  name: sonoff-mini
  model: Sonoff Mini

esp8266:
  board: esp8285
  restore_from_flash: true

logger:
  baud_rate: 0

binary_sensor:
  - id: button
    platform: gpio
    internal: true
    pin:
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      then:
        light.toggle: light_w

light:
  - id: light_w
    platform: binary
    name: $device_name
    output: light_relay

output:
  - id: status_led
    platform: gpio
    pin: 13
    inverted: true

  - id: light_relay
    platform: gpio
    pin: 12
