packages:
  base: !include ../common/base.yaml

substitutions:
  relay_restore_mode: ALWAYS_OFF

esphome:
  name: sonoff-basic-r2
  model: Sonoff Basic R2

esp8266:
  board: esp8285
  restore_from_flash: true

logger:
  baud_rate: 0

binary_sensor:
  - id: button
    platform: gpio
    internal: true
    pin:
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      then:
        switch.toggle: relay

switch:
  - id: relay
    platform: gpio
    pin: 12
    name: $device_name
    restore_mode: $relay_restore_mode

output:
  - id: status_led
    platform: gpio
    pin: 13
    inverted: true
