packages:
  base: !include ../common/esp8266.yaml

esphome:
  name: sonoff-basic-r3
  model: Sonoff Basic R3

esp8266:
  board: esp8285

logger:
  baud_rate: 0

binary_sensor:
  - id: push_button
    platform: gpio
    pin:
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      switch.toggle: relay

switch:
  - id: relay
    platform: gpio
    pin: 12
    name: ''

output:
  - id: status_led
    platform: gpio
    pin: 13
    inverted: true
