# Как t34_plug, но зелёная плата, чуть отличаются пины, и UART доступен
# https://www.wildberries.ru/catalog/730475484/detail.aspx?size=1032772134

packages:
  base: !include ../common/base.yaml
  bl0937: !include ../common/bl0937.yaml

substitutions:
  relay_restore_mode: RESTORE_DEFAULT_OFF
  bl0937_sel_pin: P8
  bl0937_sel_pin_inverted: 'true'
  bl0937_cf_pin: P6
  bl0937_cf_pin_inverted: 'true'
  bl0937_cf1_pin: P7
  bl0937_cf1_pin_inverted: 'true'
  bl0937_current_resistor: 0.00106
  bl0937_voltage_divider: 793

esphome:
  friendly_name: Tuya T34 Smart Plug
  name: t34-plug
  model: Tuya T34 Smart Plug (Green PCB)

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:
  baud_rate: 0

binary_sensor:
  - id: push_button
    platform: gpio
    pin: P26
    on_press:
      switch.toggle: relay

status_led:
  pin:
    number: P28
    inverted: true

switch:
  - id: relay
    name: ''
    platform: gpio
    pin: P24
    device_class: outlet
    restore_mode: $relay_restore_mode
