# https://www.elektroda.com/rtvforum/topic4099021.html
# https://www.elektroda.com/news/news4112776.html
# Обычная туевая розетка с маркетплейса (https://www.wildberries.ru/catalog/142695350/detail.aspx?size=241147262)
# Версия без доступного UART, перешивал с выпаиванием феном

packages:
  base: !include ../common/base.yaml
  bl0937: !include ../common/bl0937.yaml

substitutions:
  relay_restore_mode: RESTORE_DEFAULT_OFF
  bl0937_sel_pin: P8
  bl0937_sel_pin_inverted: 'true'
  bl0937_cf_pin: P6
  bl0937_cf_pin_inverted: 'true'
  bl0937_cf1_pin: P7
  bl0937_cf1_pin_inverted: 'true'
  bl0937_current_resistor: 0.00103
  bl0937_voltage_divider: 810

esphome:
  friendly_name: Tuya T34 Smart Plug
  name: t34-plug
  model: Tuya T34 Smart Plug

bk72xx:
  board: generic-bk7231n-qfn32-tuya

binary_sensor:
  - id: push_button
    platform: gpio
    pin: P26
    on_press:
      switch.toggle: relay

status_led:
  pin: P24

switch:
  - id: relay
    name: ''
    platform: gpio
    pin: P14
    device_class: outlet
    restore_mode: $relay_restore_mode
