packages:
  base: !include ../common/base.yaml

esphome:
  name: tuya-cover
  model: Tuya Cover

esp8266:
  board: nodemcuv2

logger:
  baud_rate: 0

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

tuya:

cover:
  - platform: tuya
    name: Motor
    control_datapoint: 1
    position_datapoint: 2
    position_report_datapoint: 3
