packages:
  base: !include ../common/base.yaml

esphome:
  name: workshop-main-light
  model: H801 LED Dimmer
  on_boot:
    - switch.turn_off: led_green

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:
  baud_rate: 0

binary_sensor:
  - id: light_switch
    platform: gpio
    internal: true
    pin:
      number: 2 # TX
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 50ms
    on_press:
      - if:
          condition:
            lambda: |-
              return id(light_w1).remote_values.is_on();
          then:
            - light.turn_off: light_w1
            - light.turn_off: light_w2
          else:
            - light.turn_on:
                id: light_w1
                brightness: 100%

            - light.turn_on:
                id: light_w2
                brightness: 100%

light:
  - id: light_w1
    platform: monochromatic
    name: Light W1
    output: pwm_w1
    default_transition_length: 2s

  - id: light_w2
    platform: monochromatic
    name: Light W2
    output: pwm_w2
    default_transition_length: 2s

output:
  - id: pwm_b
    platform: esp8266_pwm
    pin: 12

  - id: pwm_g
    platform: esp8266_pwm
    pin: 13

  - id: pwm_r
    platform: esp8266_pwm
    pin: 15

  - id: pwm_w1
    platform: esp8266_pwm
    pin: 14

  - id: pwm_w2
    platform: esp8266_pwm
    pin: 04

switch:
  - id: led_green
    platform: gpio
    internal: true
    pin:
      number: 1
      inverted: true

status_led:
  pin:
    number: 5
    inverted: true
