automation:
  - id: bathroom_bathtub_region_enter
    alias: 'Bathroom Bath: Region enter'
    trigger:
      - platform: device
        domain: mqtt
        device_id: dfc039d7f269372836ab2b62aaf4401b
        type: action
        subtype: region_1_enter
        discovery_id: 0x54ef441000585ebc action_region_1_enter
    action:
      - service: timer.cancel
        entity_id: timer.bathroom_bathtub_region_free

      - service: input_boolean.turn_on
        entity_id: input_boolean.bathroom_bathtub_occupancy

  - id: bathroom_bathtub_region_leave
    alias: 'Bathroom Bath: Region leave'
    trigger:
      - platform: device
        domain: mqtt
        device_id: dfc039d7f269372836ab2b62aaf4401b
        type: action
        subtype: region_1_leave
        discovery_id: 0x54ef441000585ebc action_region_1_leave
    action:
      - service: timer.start
        entity_id: timer.bathroom_bathtub_region_free

  - id: bathroom_bathtub_region_free
    alias: 'Bathroom Bath: Region free'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bathroom_bathtub_region_free
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bathroom_bathtub_occupancy

input_boolean:
  bathroom_bathtub_occupancy:
    name: Bathroom Bathtub Occupancy
    initial: false

template:
  binary_sensor:
    - name: Bathroom Bathtub Occupancy
      unique_id: binary_sensor.bathroom_bathtub_occupancy
      state: >
        {{ is_state('input_boolean.bathroom_bathtub_occupancy', 'on') }}
      availability: >
        {{ states('binary_sensor.bathroom_occupancy') in ['on', 'off'] }}
      device_class: occupancy

timer:
  bathroom_bathtub_region_free:
    name: 'Bathrom Bathtub: Region free'
    duration:
      minutes: 1
