binary_sensor:
  - platform: group
    unique_id: binary_sensor.bedroom_any_occupancy
    name: Bedroom Any Occupancy
    device_class: occupancy
    entities:
      - binary_sensor.bedroom_motion
      - binary_sensor.bedroom_occupancy
      - binary_sensor.bedroom_desk_occupancy
      - binary_sensor.bedroom_bed_any_occuppancy

  - platform: group
    unique_id: binary_sensor.bedroom_bed_any_occupancy
    name: Bedroom Bed Any Occupancy
    device_class: occupancy
    entities:
      - binary_sensor.bed_presence_layma
      - binary_sensor.bed_presence_dextor

  - platform: group
    unique_id: binary_sensor.bedroom_bed_full_occupancy
    name: Bedroom Bed Full Occupancy
    device_class: occupancy
    all: true
    entities:
      - binary_sensor.bed_presence_layma
      - binary_sensor.bed_presence_dextor
