binary_sensor:
  - platform: group
    unique_id: binary_sensor.bedroom_any_occupancy
    name: Bedroom Any Occupancy
    device_class: occupancy
    entities:
      - binary_sensor.bedroom_motion
      - binary_sensor.bedroom_occupancy
      - binary_sensor.bedroom_bed_occupancy
