automation:
  - id: nelma5_restart
    alias: Nelma5 Restart
    triggers:
      - trigger: state
        entity_id:
          - sensor.cb_branch_circuit_power
          - sensor.kitchen_branch_circuit_power
          - sensor.sockets_branch_circuit_power
        to: unknown
        for:
          minutes: 5
    actions:
      - action: button.press
        entity_id: button.nelma5_restart

template:
  - trigger:
      - platform: time_pattern
        seconds: /1
    sensor:
      # потребляемая мощность по линии Ванная/Климат, которая потребляется кондиционерами
      - unique_id: sensor.cb_branch_circuit_power_for_ac
        name: CB Branch Circuit Power For AC
        state: >
          {% set power = states('sensor.cb_branch_circuit_power') | int(0) %}
          {% set power = power - states('sensor.bedroom_desk_plug_power') | int(0) %}
          {% set power = power - states('sensor.bedroom_intake_fan_power') | int(0) %}
          {% set power = power - states('sensor.dryer_power') | int(0) %}
          {% set power = power - states('sensor.vacuum_charger_power') | int(0) %}
          {% set power = power - states('sensor.washing_machine_power') | int(0) %}
          {% set power = power - states('sensor.water_heater_power') | int(0) %}
          {% set power = power - states('sensor.workshop_intake_fan_power') | int(0) %}

          {{ [power, 0] | max }}
        state_class: measurement
        unit_of_measurement: W
        device_class: power
