input_boolean:
  waiting_guests:
    name: Waiting guests
    icon: mdi:account-star-outline
    initial: false

  overnight_guests:
    name: Overnight guests
    icon: mdi:wizard-hat
    initial: false

automation:
  - id: waiting_guests_on_by_voice
    alias: 'Waiting Guests: On (by voice)'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Ждём гостей
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.waiting_guests

      - action: script.yandex_station_tts
        data:
          target: >
            {{ trigger.event.data.get('entity_id', 'last') }}
          text: >
            {{ [
                'Хорошо, открою им двери когда придут',
                'Поняла, с нетерпением ждем',
                'Отлично, хоть какие-то новые лица'
               ]|random
            }}

  - id: waiting_guests_turn_on_light
    alias: 'Waiting Guests: Turn on lights'
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.front_door
    conditions:
      - condition: switch.is_on
        target:
          entity_id: input_boolean.waiting_guests

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - condition: light.is_off
        target:
          entity_id: light.entrance
    actions:
      - action: light.turn_on
        entity_id: light.entrance

  - id: waiting_guests_off
    alias: 'Waiting Guests: Off'
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.front_door

      - trigger: switch.turned_on
        target:
          entity_id: input_boolean.waiting_guests
        options:
          for:
            hours: 1
    conditions:
      - condition: switch.is_on
        target:
          entity_id: input_boolean.waiting_guests
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.waiting_guests

  - id: overnight_guests_off_by_timeout
    alias: 'Overnight Guests: Off (by timeout)'
    triggers:
      - trigger: switch.turned_on
        target:
          entity_id: input_boolean.overnight_guests
        options:
          for:
            hours: 14
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.overnight_guests
