automation:
  - id: kitchen_ovens_status_update
    alias: Kichen Ovens Status Update
    triggers:
      - trigger: state
        entity_id: sensor.kitchen_ovens_socket_power
    conditions:
      - condition: template
        value_template: >
          {{ trigger.to_state.state | int(0) >= 100 }}
    actions:
      - action: timer.start
        entity_id: timer.kitchen_ovens_running

  - id: kitchen_appliance_left_on_alert
    alias: Kitchen Appliance Left On Alert
    triggers:
      - trigger: state
        entity_id: binary_sensor.kitchen_occupancy
        from: 'on'
        to: 'off'
        for:
          minutes: 10

      - trigger: state
        entity_id: binary_sensor.anyone_home
        to: 'off'

      - trigger: state
        entity_id: input_boolean.scene_meal
        to: 'on'
        for:
          minutes: 5
    conditions:
      - condition: state
        entity_id:
          - binary_sensor.stove
          - binary_sensor.kitchen_ovens
        match: any
        state: 'on'

      # TODO: тут должно быть исключающее правило, если что-то долго готовится в духовке
    action:
      - action: notify.send_message
        data:
          entity_id: notify.dextor
          message: >
            ⚡️ Похоже кто-то забыл выключить плиту или печку

template:
  - binary_sensor:
      - name: Kitchen Ovens
        unique_id: binary_sensor.kitchen_ovens
        state: >
          {{ is_state('timer.kitchen_ovens_running', 'active') }}
        device_class: running

timer:
  kitchen_ovens_running:
    name: 'Kitchen Ovens: Running'
    duration:
      minutes: 2
