automation:
  - id: kitchen_applicances_status_update
    alias: Kichen Applicances Status Update
    trigger:
      - platform: state
        entity_id: sensor.kitchen_power_supply_power
    condition:
      - condition: template
        value_template: >
          {{ trigger.to_state.state|int(0) >= 700 }}
    action:
      - service: timer.start
        entity_id: timer.kitchen_appliances_running

  - id: appliance_left_on_alert
    alias: Appliance Left On Alert
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupancy
        from: 'on'
        to: 'off'
        for:
          minutes: 20

      - platform: state
        entity_id: binary_sensor.anyone_home
        to: 'off'

      - platform: state
        entity_id: input_boolean.scene_meal
        to: 'on'
        for:
          minutes: 3
    condition:
      - condition: state
        entity_id:
          - binary_sensor.stove
          - binary_sensor.kitchen_appliances
        match: any
        state: 'on'
        for:
          minutes: 5
    action:
      - service: notify.dextor
        data:
          message: >
            ⚡️ Похоже кто-то забыл выключить плиту или печку

template:
  - binary_sensor:
      - name: Kitchen Appliances
        unique_id: binary_sensor.kitchen_appliances
        state: >
          {{ is_state('timer.kitchen_appliances_running', 'active') }}
        device_class: running

timer:
  kitchen_appliances_running:
    name: 'Kitchen Appliances: Running'
    duration:
      minutes: 2
