automation:
  - id: kitchen_appliance_left_on_alert
    alias: Kitchen Appliance Left On Alert
    triggers:
      - trigger: state
        entity_id: binary_sensor.kitchen_occupancy
        from: 'on'
        to: 'off'
        for:
          minutes: 10

      - trigger: state
        entity_id: binary_sensor.anyone_home
        to: 'off'

      - trigger: state
        entity_id: input_boolean.scene_meal
        to: 'on'
        for:
          minutes: 5
    conditions:
      - condition: state
        entity_id:
          - binary_sensor.stove
          - binary_sensor.kitchen_ovens
        match: any
        state: 'on'

      # TODO: тут должно быть исключающее правило, если что-то долго готовится в духовке
    actions:
      - action: notify.send_message
        data:
          entity_id: notify.dextor
          message: >
            ⚡️ Похоже кто-то забыл выключить плиту или печку

template:
  - binary_sensor:
      - name: Kitchen Ovens
        unique_id: binary_sensor.kitchen_ovens
        state: >
          {{ states('sensor.kitchen_ovens_socket_power') | int(0) > 100 }}
        device_class: running
        delay_off:
          minutes: 2
