automation:
  - id: smoke_detected
    alias: 'Smoke: Detected'
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.kitchen_smoke
          - binary_sensor.hallway_smoke
          - binary_sensor.porch_smoke
        from: 'off'
        to: 'on'

      - id: not_a_drill
        trigger: state
        entity_id:
          - binary_sensor.kitchen_smoke
          - binary_sensor.hallway_smoke
          - binary_sensor.porch_smoke
        from: 'off'
        to: 'on'
        for:
          minutes: 1
    variables: &variables
      _area_: >-
        {{ {
          'binary_sensor.kitchen_smoke': 'на кухне',
          'binary_sensor.porch_smoke': 'на крыльце',
          'binary_sensor.hallway_smoke': 'в коридоре',
        }.get(trigger.from_state.entity_id, '') }}
    action:
      - action: notify.mobile_app_misaka
        data:
          message: >-
            🚨 Обнаружено задымление {{ _area_ }}
          data:
            push:
              sound:
                name: sms-received2.caf
                critical: 1
                volume: 1
        continue_on_error: true

      - action: notify.dextor
        data:
          message: >-
            🚨 Обнаружено задымление {{ _area_ }}
        continue_on_error: true

  - id: smoke_resolved
    alias: 'Smoke: Resolved'
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.kitchen_smoke
          - binary_sensor.hallway_smoke
          - binary_sensor.porch_smoke
        from: 'on'
        to: 'off'
    variables:
      <<: *variables
    actions:
      - action: notify.dextor
        data:
          message: >-
            🎉 Устранено задымление {{ _area_ }}

binary_sensor:
  - platform: group
    unique_id: binary_sensor.smoke
    name: Smoke
    device_class: smoke
    entities:
      - binary_sensor.kitchen_smoke
      - binary_sensor.hallway_smoke
      - binary_sensor.porch_smoke
