automation:
  - id: smoke_detected
    alias: 'Smoke: Detected'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_smoke
          - binary_sensor.hallway_smoke
          - binary_sensor.porch_smoke
        from: 'off'
        to: 'on'

      - platform: state
        id: not_a_drill
        entity_id:
          - binary_sensor.kitchen_smoke
          - binary_sensor.hallway_smoke
          - binary_sensor.porch_smoke
        from: 'off'
        to: 'on'
        for:
          minutes: 1
    action:
      - service: notify.mobile_app_misaka
        data:
          message: >
            🚨 Обнаружено задымление {{ state_attr(trigger.from_state.entity_id, 'alert_text')|default('', True) }}
          data:
            push:
              sound:
                name: sms-received2.caf
                critical: 1
                volume: 1
        continue_on_error: true

      - service: notify.dextor
        data:
          message: >
            🚨 Обнаружено задымление {{ state_attr(trigger.from_state.entity_id, 'alert_text')|default('', True) }}
        continue_on_error: true

  - id: smoke_resolved
    alias: 'Smoke: Resolved'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_smoke
          - binary_sensor.hallway_smoke
          - binary_sensor.porch_smoke
        from: 'on'
        to: 'off'
    action:
      - service: notify.dextor
        data:
          message: >
            🎉 Устранено задымление {{ state_attr(trigger.from_state.entity_id, 'alert_text')|default('', True) }}

binary_sensor:
  - platform: group
    unique_id: binary_sensor.smoke
    name: Smoke
    device_class: smoke
    entities:
      - binary_sensor.kitchen_smoke
      - binary_sensor.hallway_smoke
      - binary_sensor.porch_smoke
