automation:
  - id: water_leak_detected_alert
    alias: 'Water Leak Detected: Alert'
    mode: restart
    triggers:
      - trigger: state
        entity_id: &water_leak_entities_all
          - binary_sensor.closet_water_leak
          - binary_sensor.kitchen_water_inlet_leak
          - binary_sensor.kitchen_water_filter_leak
          - binary_sensor.kitchen_backup_water_leak
          - binary_sensor.bathroom_washing_machine_water_leak
          - binary_sensor.bathroom_sink_water_leak
          - binary_sensor.bathroom_toilet_water_leak
          - binary_sensor.bathroom_hot_water_meter_leak
          - binary_sensor.bathroom_cold_water_meter_leak
          - binary_sensor.living_room_humidifier_water_leak
          - binary_sensor.living_room_humidifier_water_tank_leak
        to: 'on'

      - trigger: state
        entity_id: *water_leak_entities_all
        to: 'on'
        for:
          minutes: 5
    variables: &variables
      _location_: >-
        {{ {
          'binary_sensor.closet_water_leak': 'в кладовке',
          'binary_sensor.kitchen_water_inlet_leak': 'на кухне под мойкой',
          'binary_sensor.kitchen_water_filter_leak': 'на кухне у фильтра',
          'binary_sensor.kitchen_backup_water_leak': 'на кухне под мойкой радио',
          'binary_sensor.bathroom_washing_machine_water_leak': 'за стиралкой',
          'binary_sensor.bathroom_sink_water_leak': 'в ванне под раковиной',
          'binary_sensor.bathroom_toilet_water_leak': 'в ванне за унитазом',
          'binary_sensor.bathroom_hot_water_meter_leak': 'в ванне горячий счетчик',
          'binary_sensor.bathroom_cold_water_meter_leak': 'в ванне холодный счётчик',
          'binary_sensor.living_room_humidifier_water_leak': 'увлажнитель в гостиной',
          'binary_sensor.living_room_humidifier_water_tank_leak': 'под увлажнителем в гостиной',
        }.get(trigger.from_state.entity_id, trigger.from_state.entity_id.split('.')[1]) }}
    actions:
      - action: notify.mobile_app_misaka
        data:
          message: >-
            🚨 Протечка {{ _location_ }}
          data:
            push:
              sound:
                name: sms-received2.caf
                critical: 1
                volume: 1
        continue_on_error: true

      - action: notify.dextor
        data:
          message: >
            🚨 Протечка {{ _location_ }}
        continue_on_error: true

      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - action: script.yandex_station_tts
        data:
          target: all
          type: alert
          text: >
            Протечка {{ _location_ }}

      - if:
          - not:
              - condition: state
                entity_id: person.dextor
                state: home
        then:
          - delay:
              seconds: 25

          - action: script.yandex_station_tts
            data:
              target: all
              type: attention
              text: >
                Протри датчик и скажи Алиса, включи воду.

  - id: water_leak_resolved_alert
    alias: 'Water Leak Resolved: Alert'
    triggers:
      - trigger: state
        entity_id: *water_leak_entities_all
        from: 'on'
        to: 'off'
    variables: *variables
    actions:
      - action: notify.dextor
        data:
          message: >
            🎉 Устранена протечка {{ _location_ }}

  - id: bathroom_water_leak_close_valves
    alias: 'Bathroom Water Leak: Close valves'
    triggers:
      - trigger: state
        entity_id: &water_leak_entities_bathroom
          - binary_sensor.closet_water_leak
          - binary_sensor.bathroom_sink_water_leak
          - binary_sensor.bathroom_toilet_water_leak
          - binary_sensor.bathroom_washing_machine_water_leak
          - binary_sensor.bathroom_hot_water_meter_leak
          - binary_sensor.bathroom_cold_water_meter_leak
        to: 'on'

      - trigger: state
        entity_id: *water_leak_entities_bathroom
        to: 'on'
        for:
          minutes: 5 # на всякий случай, если первый раз что-то пошло не так
    actions:
      - action: valve.close_valve
        target:
          entity_id:
            - valve.bathroom_cold_water
            - valve.bathroom_hot_water
        continue_on_error: true

      - action: switch.turn_off
        target:
          entity_id:
            - switch.bathroom_hot_water_valve
            - switch.bathroom_cold_water_valve
            - switch.washing_machine_plug
            - switch.water_heater_socket

  - id: kitchen_water_leak_close_valves
    alias: 'Kitchen Water Leak: Close valves'
    triggers:
      - trigger: state
        entity_id: binary_sensor.kitchen_water_leak_protection_problem
        to: 'on'
        for:
          seconds: 30 # за это время краны должны штатно закрыться
      - trigger: state
        entity_id: binary_sensor.kitchen_backup_water_leak
        to: 'on'
    actions:
      - action: valve.close_valve
        target:
          entity_id:
            - valve.kitchen_water_inlet
            - valve.kitchen_water_filter_tank
        continue_on_error: true

      - action: switch.turn_off
        target:
          entity_id: switch.dishwasher_plug

  - id: kitchen_water_leak_protection_problem_alert
    alias: 'Kitchen Water Leak Protection: Problem Alert'
    triggers:
      - trigger: state
        entity_id: binary_sensor.kitchen_water_leak_protection_problem
        to: 'on'
    conditions:
      - condition: template
        value_template: >-
          {{ trigger.to_state.attributes.get('description') not in ['line_1_attention', 'line_2_attention'] }}
    actions:
      - action: notify.dextor
        data:
          message: >
            🚨 Проблема с защитой от протечек на кухне: {{ trigger.to_state.attributes.get('description') }}

binary_sensor:
  - platform: group
    unique_id: binary_sensor.water_leak
    name: Water Leak
    device_class: moisture
    entities:
      - binary_sensor.closet_water_leak
      - binary_sensor.kitchen_water_inlet_leak
      - binary_sensor.kitchen_water_filter_leak
      - binary_sensor.kitchen_backup_water_leak
      - binary_sensor.bathroom_washing_machine_water_leak
      - binary_sensor.bathroom_sink_water_leak
      - binary_sensor.bathroom_toilet_water_leak
      - binary_sensor.bathroom_hot_water_meter_leak
      - binary_sensor.bathroom_cold_water_meter_leak
      - binary_sensor.living_room_humidifier_water_leak
      - binary_sensor.living_room_humidifier_water_tank_leak

input_boolean:
  hot_water_supply:
    name: Hot Water Supply
    icon: mdi:water-boiler

template:
  - binary_sensor:
      # https://github.com/dext0r/tuya-local/blob/759b2065ac93ec3efd930f71b222522e58ad083e/custom_components/tuya_local/devices/stahlmann_smart_waterleak.yaml#L25
      - name: Kitchen Water Inlet Leak
        unique_id: binary_sensor.kitchen_water_inlet_leak
        state: >-
          {{ is_state_attr('binary_sensor.kitchen_water_leak_protection_problem',
                           'description', 'line_1_attention') }}
        availability: >-
          {{ is_state('binary_sensor.kitchen_water_leak_protection_problem', ['on', 'off']) }}
        device_class: moisture

      - name: Kitchen Water Filter Leak
        unique_id: binary_sensor.kitchen_water_filter_leak
        state: >-
          {{ is_state_attr('binary_sensor.kitchen_water_leak_protection_problem',
                           'description', 'line_2_attention') }}
        availability: >-
          {{ is_state('binary_sensor.kitchen_water_leak_protection_problem', ['on', 'off']) }}
        device_class: moisture

  - switch:
      # только для управления голосом
      - unique_id: switch.water_supply
        name: Water Supply
        state: >-
          {{
            is_state('valve.bathroom_cold_water', 'open') and
            is_state('valve.bathroom_hot_water', 'open') and
            is_state('valve.kitchen_water_inlet', 'open') and
            is_state('valve.kitchen_water_filter_tank', 'open')
          }}
        turn_on:
          - action: switch.turn_on
            target:
              entity_id:
                - switch.dishwasher_plug
                - switch.washing_machine_plug
            continue_on_error: true

          - action: valve.open_valve
            target:
              entity_id:
                - valve.bathroom_cold_water
                - valve.kitchen_water_inlet
                - valve.kitchen_water_filter_tank
            continue_on_error: true

          - if:
              - condition: switch.is_on
                target:
                  entity_id: input_boolean.hot_water_supply
            then:
              - action: valve.open_valve
                entity_id: valve.bathroom_hot_water
        turn_off:
          - action: none.none

utility_meter:
  kitchen_filter_drink_water_daily:
    unique_id: sensor.kitchen_filter_drink_water_daily
    name: Kitchen Filter Drink Water Daily
    source: sensor.kitchen_filter_drink_water
    cycle: daily

  kitchen_filter_drink_water_monthly:
    unique_id: sensor.kitchen_filter_drink_water_monthly
    name: Kitchen Filter Drink Water Monthly
    source: sensor.kitchen_filter_drink_water
    cycle: monthly

  kitchen_filter_feed_water_daily:
    unique_id: sensor.kitchen_filter_feed_water_daily
    name: Kitchen Filter Feed Water Daily
    source: sensor.kitchen_filter_feed_water
    cycle: daily

  kitchen_filter_feed_water_monthly:
    unique_id: sensor.kitchen_filter_feed_water_monthly
    name: Kitchen Filter Feed Water Monthly
    source: sensor.kitchen_filter_feed_water
    cycle: monthly
