binary_sensor:
  - platform: group
    unique_id: binary_sensor.workshop_motion
    name: Workshop Motion
    device_class: motion
    entities:
      - binary_sensor.workshop_entrance_motion
      - binary_sensor.workshop_desk_motion

template:
  - binary_sensor:
      # "Я всегда включаю свет в мастерской когда там сижу"
      - name: Workshop Occupancy
        state: >
          {{ is_state('light.workshop_main', 'on') }}
        device_class: occupancy
