input_select:
  dishwasher_status:
    name: Dishwasher Status
    icon: mdi:dishwasher
    options:
      - Dirty
      - Idle
      - Running
      - Done
    initial: Idle

automation:
  - id: dishwasher_cycle
    alias: 'Dishwasher: Cycle'
    mode: restart
    trigger:
      platform: state
      entity_id: sensor.dishwasher_progress
      from: Idle
      to:
        - Pre-wash
        - Wash
    action:
      - service: input_select.select_option
        entity_id: input_select.dishwasher_status
        data:
          option: Running

      - wait_for_trigger:
          - platform: state
            entity_id: sensor.dishwasher_progress
            to:
              - Complete
              - Idle
        timeout:
          hours: 4
        continue_on_timeout: true

      - if:
          - condition: state
            entity_id: binary_sensor.dishwasher_door
            state: 'off'
        then:
          - service: input_select.select_option
            entity_id: input_select.dishwasher_status
            data:
              option: Done
        else:
          - service: input_select.select_option
            entity_id: input_select.dishwasher_status
            data:
              option: Idle

  - id: dishwasher_free
    alias: 'Dishwasher: Free'
    trigger:
      platform: state
      entity_id: binary_sensor.dishwasher_door
      to: 'on'
      for:
        seconds: 10
    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Done
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.dishwasher_door
            to: 'off'
        timeout:
          minutes: 10
        continue_on_timeout: true

      - service: input_select.select_option
        entity_id: input_select.dishwasher_status
        data:
          option: Idle

  - id: dishwasher_dirty
    alias: 'Dishwasher: Dirty'
    trigger:
      platform: state
      entity_id: binary_sensor.dishwasher_door
      to: 'on'
      for:
        seconds: 30
    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Idle
    action:
      - service: input_select.select_option
        entity_id: input_select.dishwasher_status
        data:
          option: Dirty

  - id: dishwasher_status
    alias: 'Dishwasher: Status'
    trigger:
      platform: event
      event_type: yandex_intent
      event_data:
        text: Что с посудомойкой
    action:
      - service: script.yandex_station_tts
        data:
          target: >
            {{ trigger.event.data.get('entity_id', 'last') }}
          text: >
            Посудомойка
            {% if is_state('input_select.dishwasher_status', 'Dirty') %}
              с грязной посудой, в ожидании запуска.
            {% elif is_state('input_select.dishwasher_status', 'Running') %}
              {% if is_state('sensor.dishwasher_progress', 'Pre-wash') %}
                в процессе предварительной мойки
              {% elif is_state('sensor.dishwasher_progress', 'Wash') %}
                в процессе основной мойки
              {% elif is_state('sensor.dishwasher_progress', 'Rinse') %}
                вспаласкивает тарелочки
              {% elif is_state('sensor.dishwasher_progress', 'Dry') %}
                сушит кружечки
              {% else %}
                делает бурлык-бурлык, посуда скоро будет чистой
              {% endif %}
            {% elif is_state('input_select.dishwasher_status', 'Done') %}
              закончила, можно доставать посуду
            {% elif is_state('input_select.dishwasher_status', 'Idle') %}
              простаивает без дела
            {% else %}
              в каком-то непонятном состоянии, что я даже хз
            {% endif %}

            {% if states('sensor.dishwasher_time_remaining') | float(0) > 0 %}
              . Осталось {{ states('sensor.dishwasher_time_remaining') }} мин.
            {% endif %}

  - id: dishwasher_status_light_update
    alias: 'Dishwasher: Status light update'
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - input_select.dishwasher_status
          - input_select.home_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state:
                  - Day
                  - Vacation

              - condition: state
                entity_id: input_select.dishwasher_status
                state: Running
            sequence:
              - service: light.turn_on
                entity_id: light.dishwasher_status
                data:
                  brightness_pct: 100
                  rgbw_color: [255, 0, 0, 0]

          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state:
                  - Day
                  - Vacation

              - condition: state
                entity_id: input_select.dishwasher_status
                state: Done
            sequence:
              - service: light.turn_on
                entity_id: light.dishwasher_status
                data:
                  brightness_pct: 30
                  rgbw_color: [0, 255, 0, 0]
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state:
                  - Day
                  - Vacation

              - condition: state
                entity_id: input_select.dishwasher_status
                state: Dirty
            sequence:
              - service: light.turn_on
                entity_id: light.dishwasher_status
                data:
                  brightness_pct: 40
                  rgbw_color: [255, 0, 215, 0]
        default:
          - service: light.turn_off
            entity_id: light.dishwasher_status

template:
  binary_sensor:
    - name: Dishwasher Door
      unique_id: binary_sensor_dishwasher_door
      state: >
        {{ is_state('binary_sensor.dishwasher_door_contact', 'off') }}
      availability: >
        {{ states('binary_sensor.dishwasher_door_contact') in ['on', 'off'] }}
      device_class: door
