input_select:
  dryer_status:
    name: Dryer Status
    icon: mdi:tumble-dryer
    options:
      - Idle
      - Running
      - Done
    initial: Idle

input_number:
  dryer_done_alert_count:
    name: 'Dryer: Done alert count'
    min: 0
    max: 5
    step: 1

automation:
  - id: dryer_cycle
    alias: 'Dryer: Cycle'
    max_exceeded: silent
    triggers:
      - trigger: numeric_state
        entity_id: sensor.dryer_power
        above: 0
        for:
          seconds: 10

      # если кратковременно открывали розетка не успеет скинуть потребление на 0
      # поэтому попытка поймать ещё раз другим изменением
      - trigger: numeric_state
        entity_id: sensor.dryer_power
        above: 200
        for:
          seconds: 10
    conditions:
      - condition: state
        entity_id: input_select.dryer_status
        state:
          - Idle
          - Done # повторный цикл без открытия дверцы
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.dryer_status
        data:
          option: Running

      - wait_for_trigger:
          - trigger: numeric_state
            entity_id: sensor.dryer_power
            below: 1
            for:
              minutes: 2

          - trigger: door.opened
            target:
              entity_id: binary_sensor.dryer_door
        timeout:
          hours: 6
        continue_on_timeout: true

      - condition: state
        entity_id: input_select.dryer_status
        state: Running

      - if:
          - condition: door.is_open
            target:
              entity_id: binary_sensor.dryer_door
        then:
          - action: input_select.select_option
            target:
              entity_id: input_select.dryer_status
            data:
              option: Idle
        else:
          - action: input_select.select_option
            target:
              entity_id: input_select.dryer_status
            data:
              option: Done

  - id: dryer_door_opened
    alias: 'Dryer: Door opened'
    triggers:
      - trigger: door.opened
        target:
          entity_id: binary_sensor.dryer_door
    conditions:
      - condition: state
        entity_id: input_select.dryer_status
        state: Done
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.dryer_status
        data:
          option: Idle

  - id: dryer_idle
    alias: 'Dryer: Idle'
    triggers:
      - trigger: state
        entity_id: input_select.dryer_status
        to: Idle
    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.dryer_done_alert_count
        data:
          value: 0

  - id: dryer_done_alert
    alias: 'Dryer: Done alert'
    triggers:
      - trigger: time_pattern
        minutes: '/45'

      - trigger: state
        entity_id: input_select.dryer_status
        from: Running
        to: Done
    conditions:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - or:
          - condition: state
            entity_id:
              - binary_sensor.living_room_light_alert_available
              - binary_sensor.kitchen_light_alert_available
            state: 'off'

          - condition: template
            value_template: >
              {{ (now() - states.input_select.dryer_status.last_changed) > timedelta(hours=1) }}

      - condition: state
        entity_id: input_select.dryer_status
        state: Done

      - condition: numeric_state
        entity_id: input_number.dryer_done_alert_count
        below: 4

      - condition: template
        value_template: >
          {{ (now() - states.input_number.dryer_done_alert_count.last_changed) > timedelta(minutes=20) }}
    actions:
      - wait_template: >
          {{ not is_state('media_player.atv', ['playing', 'pause']) }}
        timeout:
          minutes: 33
        continue_on_timeout: true

      - action: script.yandex_station_tts
        data:
          target: all
          type: attention
          text: >
            {{ states.sensor.alert_greeting.state }}
            {{ [
                'Сушилка ждёт тебя, пора раскладывать бельё по полочкам.',
                'Сушилка ждет тебя, в ней тебя ждёт что-то особенное.',
                'Сушилка закончила, пора достать из неё мягонькое бельё.',
                ] | random
            }}
            {% if states('input_number.dryer_done_alert_count') | int(0) == 2 %}
              Если я ошиблась - закрой дверцу машины и открой снова.
            {% endif %}
            {% if states('input_number.dryer_done_alert_count') | int(0) == 3 %}
              Это последнее предупреждение! Мятое белье останется там навсегда!
            {% endif %}

      - action: input_number.increment
        target:
          entity_id: input_number.dryer_done_alert_count

  - id: dryer_status_by_voice
    alias: 'Dryer: Status (by voice)'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Что с сушильной машиной
    actions:
      - action: script.yandex_station_tts
        data:
          target: >-
            {{ trigger.event.data.get('entity_id', 'last') }}
          text: >-
            Сушилка
            {% if is_state('input_select.dryer_status', 'Running') %}
              делает пух-пух. Скоро вещи будут сухими и мягонькими
            {% elif is_state('input_select.dryer_status', 'Done') %}
              закончила, доставай быстрее белье и развешивай в гардеробную
            {% elif is_state('input_select.dryer_status', 'Idle') %}
              простаивает без дела и скучает по мокрому бельёю
            {% endif %}
