automation:
  - id: certificate_renew
    alias: Certificate renew
    trigger:
      - platform: time
        at: '10:00:00'
    action:
      - service: hassio.addon_start
        data:
          addon: core_letsencrypt

template:
  - sensor:
      - unique_id: sensor.hotaru_exhaust_fan_speed
        name: hotaru exhaust fan speed
        icon: mdi:fan
        unit_of_measurement: rpm
        state: >
          {{ states('sensor.hotaru_exhaust_fan_speed_raw')|int|round(-2) }}
        availability: >
          {{ states('sensor.hotaru_exhaust_fan_speed_raw') not in ['unavailable', 'unknown'] }}
