input_datetime:
  humidifiers_last_cleanup:
    name: 'Humidifiers: Last cleanup'
    has_date: true
    icon: mdi:spray-bottle

automation:
  - id: humidifiers_maintenance_alert
    alias: 'Humidifiers: Maintenance Alert'
    trigger:
      - platform: time_pattern
        minutes: '/10'
    condition:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: or
        conditions:
          - and:
              - condition: numeric_state
                entity_id: sensor.bedroom_humidifier_water_level
                below: 25

              - condition: state
                entity_id: input_boolean.bedroom_humidifier_control
                state: 'on'

          - and:
              - condition: state
                entity_id: switch.living_room_humidifier_water_tank_maintenance
                state:
                  - 'off'
                  - 'unavailable'

              - condition: numeric_state
                entity_id: sensor.living_room_humidifier_water_level
                below: 25

              - condition: state
                entity_id: input_boolean.living_room_humidifier_control
                state: 'on'

          - and:
              - condition: numeric_state
                entity_id: sensor.workshop_humidifier_water_level
                below: 25

              - condition: state
                entity_id: binary_sensor.workshop_humidifier_water_tank
                state: 'on'

              - condition: state
                entity_id: input_boolean.workshop_humidifier_control
                state: 'on'

      - condition: state
        entity_id:
          - input_boolean.scene_movie
          - input_boolean.scene_meal
        state: 'off'

      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation

      - condition: template
        value_template: >
          {{ (now() - states.input_select.home_mode.last_changed).total_seconds() > 3600 }}

      - condition: template
        value_template: >
          {{ (now() - state_attr('automation.humidifiers_maintenance_alert',
                                 'last_triggered')|default(now() - timedelta(days=1), true)).total_seconds() > 60 * 60 }}
    action:
      - wait_template: >
          {{ not is_state('media_player.atv', ['playing', 'pause']) }}
        timeout:
          minutes: 28
        continue_on_timeout: true

      - if:
          - condition: state
            entity_id: binary_sensor.humidifier_cleanup_notice
            state: 'on'
        then:
          - service: script.yandex_station_tts
            data:
              target: all
              type: attention
              text: >
                {{ states.sensor.alert_greeting.state }}
                {{ [
                    'Я чувствую новую жизнь! Давай помоем увлажнители',
                    'Пахнет болотом, понимаешь к чем я клоню?',
                    'Не хотела тебе говорить, но увлажнители надо помыть',
                    'Сегодня доливом воды не отделаешься, время мыть увлажнители',
                    'Даже кот не идёт вейпить увлажнитель, там очень пахнет'
                    ]|random
                }}
        else:
          - service: script.yandex_station_tts
            data:
              target: all
              type: attention
              text: >
                {{ states.sensor.alert_greeting.state }}
                {{ [
                    'Добавь водички в увлажнители',
                    'Увлажнители хотят пить',
                    'У увлажнителей пересохло в горле, напои их пожалуйста',
                    'Как-то суховато, может воды?',
                    'Пора размяться и налить в увлажнители воды',
                    'Не любишь сухие губы? Налей воды в увлажнители!',
                    'Увлажните меня!',
                    ]|random
                }}
                {% if not is_state('sensor.humidifier_need_refill', 'unavailable') %}
                  {{ states('sensor.humidifier_need_refill') }}
                {% endif %}

  - id: humidifiers_cleanup
    alias: 'Humidifiers: Cleanup'
    trigger:
      - platform: state
        entity_id: binary_sensor.workshop_humidifier_water_tank
        from: 'on'
        to: 'off'
        for:
          seconds: 30
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.humidifiers_last_cleanup
        data:
          date: '{{ now().strftime("%Y-%m-%d") }}'

group:
  humidifiers_control:
    name: 'Humidifiers: Control'
    entities:
      - input_boolean.bedroom_humidifier_control
      - input_boolean.living_room_humidifier_control
      - input_boolean.workshop_humidifier_control

template:
  - sensor:
      - unique_id: sensor.humidifier_need_refill
        name: 'Humidifier: Need Refill'
        icon: mdi:water-well-outline
        state: >
          {% set data = namespace(humidifiers=[]) %}

          {% if is_state('input_boolean.bedroom_humidifier_control', 'on') and states('sensor.bedroom_humidifier_water_level')|int(100) < 30 %}
            {% set data.humidifiers = data.humidifiers + ['спальне'] %}
          {% endif %}

          {% if is_state('input_boolean.living_room_humidifier_control', 'on') and states('sensor.living_room_humidifier_water_level')|int(100) < 30 %}
            {% set data.humidifiers = data.humidifiers + ['гостиной'] %}
          {% endif %}

          {% if is_state('switch.living_room_humidifier_water_tank_auto_refill', 'on') and states('sensor.living_room_humidifier_water_tank_level')|int(100) < 15 %}
            {% set data.humidifiers = data.humidifiers + ['злой бочке'] %}
          {% endif %}

          {% if is_state('input_boolean.workshop_humidifier_control', 'on') and states('sensor.workshop_humidifier_water_level')|int(100) < 30 %}
            {% set data.humidifiers = data.humidifiers + ['мастерской'] %}
          {% endif %}

          {% if data.humidifiers %}
            в {{ data.humidifiers|join(', ') }}
          {% endif %}

  - binary_sensor:
      - unique_id: binary_sensor.humidifier_cleanup_notice
        name: 'Humidifier: Cleanup notice'
        icon: mdi:bulletin-board
        state: >
          {% set v = (now()|as_timestamp - state_attr('input_datetime.humidifiers_last_cleanup',
                                              'timestamp')) > (60 * 60 * 24 * 5) %}
          {% if not is_state('person.dextor', 'home') %}
            {% set v = false %}
          {% elif now().hour >= 22 or now().hour < 15 %}
            {% set v = false %}
          {% elif is_state('group.humidifiers_control', 'off') %}
            {% set v = false %}
          {% endif %}

          {{ v }}
