input_datetime:
  humidifiers_last_cleanup:
    name: 'Humidifiers: Last cleanup'
    has_date: true
    icon: mdi:spray-bottle

automation:
  - id: humidifiers_maintenance_alert
    alias: 'Humidifiers: Maintenance Alert'
    trigger:
      - platform: time_pattern
        minutes: '/10'
    condition:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id:
          - input_boolean.bedroom_humidifier_on_duty
          - input_boolean.living_room_humidifier_on_duty
          - input_boolean.workshop_humidifier_on_duty
        match: any
        state: 'on'

      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.bedroom_humidifier_water_level
            below: 30

          - condition: numeric_state
            entity_id: sensor.living_room_humidifier_water_level
            below: 30

          - condition: numeric_state
            entity_id: sensor.workshop_humidifier_water_level
            below: 30

      - condition: state
        entity_id:
          - input_boolean.scene_movie
          - input_boolean.scene_meal
        state: 'off'

      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Vacation

      - condition: template
        value_template: >
          {{ (now() - states.input_select.home_mode.last_changed).total_seconds() > 3600 }}

      - condition: template
        value_template: >
          {{ (now() - state_attr('automation.humidifiers_maintenance_alert',
                                 'last_triggered')|default(now() - timedelta(days=1), true)).total_seconds() > 60 * 60 }}
    action:
      - if:
          - condition: state
            entity_id: person.dextor
            state: home

          - condition: template
            value_template: >
              {{ (now()|as_timestamp - state_attr('input_datetime.humidifiers_last_cleanup',
                                                  'timestamp')) > (60 * 60 * 24 * 5) }}
        then:
          - service: script.yandex_station_tts
            data:
              target: all
              type: attention
              text: >
                {{ states.sensor.alert_greeting.state }}
                {{ [
                    'Я чувствую новую жизнь! Давай помоем увлажнители',
                    'Пахнет болотом, понимаешь к чем я клоню?',
                    'Не хотела тебе говорить, но увлажнители надо помыть',
                    'Сегодня доливом воды не отделаешься, время мыть увлажнители',
                    'Даже кот не идёт вейпить увлажнитель, там очень пахнет'
                    ]|random
                }}
        else:
          - service: script.yandex_station_tts
            data:
              target: all
              type: attention
              text: >
                {{ states.sensor.alert_greeting.state }}
                {{ [
                    'Добавь водички в увлажнители',
                    'Увлажнители хотят пить',
                    'У увлажнителей пересохло в горле, напои их пожалуйста',
                    'Как-то суховато, может воды?',
                    'Пора размяться и налить в увлажнители воды',
                    'Не любишь сухие губы? Налей воды в увлажнители!'
                    ]|random
                }}

  - id: humidifiers_cleanup
    alias: 'Humidifiers: Cleanup'
    trigger:
      - platform: state
        entity_id: binary_sensor.workshop_humidifier_water_tank
        from: 'on'
        to: 'off'
        for:
          seconds: 30
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.humidifiers_last_cleanup
        data:
          date: '{{ now().strftime("%Y-%m-%d") }}'
