input_select:
  ironing_board_room:
    name: Ironing Board Room
    icon: mdi:map-marker-radius-outline
    options:
      - Living Room
      - Bedroom

automation:
  - id: ironing_board_turn_off_occupance_living_room
    alias: 'Ironing Board: Turn off (Occupancy / Living Room)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_occupancy
        to: 'off'
        for:
          minutes: 20

      - trigger: state
        entity_id: binary_sensor.ironing_board_occupancy
        to: 'off'
        for:
          minutes: 20
    conditions:
      - condition: state
        entity_id: switch.ironing_board_socket
        state: 'on'

      - condition: state
        entity_id: binary_sensor.ironing_board_occupancy
        state: 'off'

      - condition: state
        entity_id: input_select.ironing_board_room
        state: 'Living Room'
    actions:
      - action: switch.turn_off
        entity_id: switch.ironing_board_socket

  - id: ironing_board_turn_off_occupancy_bedroom
    alias: 'Ironing Board: Turn off (Occupancy / Bedroom)'
    triggers:
      - platform: state
        entity_id: binary_sensor.bedroom_any_occupancy
        to: 'off'
        for:
          minutes: 20

      - trigger: state
        entity_id: binary_sensor.ironing_board_occupancy
        to: 'off'
        for:
          minutes: 20
    conditions:
      - condition: state
        entity_id: switch.ironing_board_socket
        state: 'on'

      - condition: state
        entity_id: binary_sensor.ironing_board_occupancy
        state: 'off'

      - condition: state
        entity_id: input_select.ironing_board_room
        state: Bedroom
    actions:
      - action: switch.turn_off
        entity_id: switch.ironing_board_socket

  - id: ironing_board_turn_off_no_one_home
    alias: 'Ironing Board: Turn off (no one home)'
    trigger:
      - platform: state
        entity_id: switch.ironing_board_socket
        to: 'on'

      - platform: time_pattern
        minutes: '/1'

      - platform: state
        entity_id: binary_sensor.anyone_home
        to: 'off'
    condition:
      - condition: state
        entity_id: switch.ironing_board_socket
        state: 'on'

      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'off'
    action:
      - action: switch.turn_off
        entity_id: switch.ironing_board_socket

  - id: ironing_board_turn_off_overload
    alias: 'Ironing Board: Turn off (overload)'
    mode: restart
    trigger:
      - platform: numeric_state
        entity_id: sensor.ironing_board_socket_power
        above: 2600

      - platform: numeric_state
        entity_id: sensor.ironing_board_socket_power
        above: 2590
    condition:
      - condition: state
        entity_id: switch.ironing_board_socket
        state: 'on'
    action:
      - action: switch.turn_off
        entity_id: switch.ironing_board_socket

      - service: script.turn_on
        entity_id: script.yandex_station_tts
        data:
          variables:
            target: media_player.{{ states('input_select.ironing_board_room')|lower|replace(' ', '_') }}_station
            text: Выключи утюг

  - id: ironing_board_turn_off_idle
    alias: 'Ironing Board: Turn off (idle)'
    triggers:
      - trigger: state
        entity_id: switch.ironing_board_socket
        to: 'on'
        for:
          minutes: 60
    actions:
      - action: switch.turn_off
        entity_id: switch.ironing_board_socket

  - id: ironing_board_occupancy_update
    alias: 'Ironing Board: Occupancy update'
    triggers:
      - trigger: state
        entity_id: binary_sensor.ironing_board_vibration
        to: 'on'
    actions:
      - action: timer.start
        entity_id: timer.ironing_board_occupancy

sensor:
  - platform: integration
    unique_id: sensor.ironing_board_energy
    name: Ironing Board Energy
    source: sensor.ironing_board_socket_power
    unit_prefix: k
    round: 2
    method: trapezoidal
    max_sub_interval:
      seconds: 5

template:
  binary_sensor:
    - name: Ironing Board Occupancy
      unique_id: binary_sensor.ironing_board_occupancy
      state: >
        {{ is_state('timer.ironing_board_occupancy', 'active') }}
      availability: >
        {{ states('binary_sensor.ironing_board_vibration') in ['on', 'off'] }}
      device_class: occupancy

timer:
  ironing_board_occupancy:
    name: 'Ironing Board: Occupancy'
    duration:
      minutes: 4
