automation:
  - id: living_room_heater_turn_off
    alias: 'Living Room Heater: Turn off'
    trigger:
      - platform: state
        entity_id: binary_sensor.anyone_home
        from: 'on'
        to: 'off'

      - platform: state
        entity_id: input_boolean.scene_sleepy_mood
        from: 'off'
        to: 'on'

      - platform: state
        entity_id: input_select.home_mode
        from: Day

      - platform: numeric_state
        entity_id: sensor.living_room_temperature
        above: 25.5

      - platform: state
        entity_id:
          - input_boolean.living_room_airing_warm
          - input_boolean.living_room_airing_cold
        from: 'off'
        to: 'on'

      - platform: state
        entity_id: switch.ironing_board_socket
        to: 'on'

      - platform: numeric_state
        entity_id: sensor.sockets_branch_circuit_power
        above: 3600
    condition:
      - condition: state
        entity_id: switch.living_room_heater
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.living_room_heater

  - id: living_room_heater_turn_off_protect
    alias: 'Living Room Heater: Turn off (protect)'
    trigger:
      - platform: state
        entity_id: switch.living_room_heater
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.ironing_board_socket
        state: 'on'
    action:
      - action: switch.turn_off
        entity_id: switch.living_room_heater

  - id: living_room_heater_turn_off_idle
    alias: 'Living Room Heater: Turn off (idle)'
    trigger:
      - platform: state
        entity_id: switch.living_room_heater
        to: 'on'
        for:
          hours: 6

      - platform: state
        entity_id: switch.living_room_heater
        to: 'on'
        for:
          hours: 7
    condition:
      - condition: state
        entity_id: switch.living_room_heater
        state: 'on'

      - condition: numeric_state
        entity_id: sensor.living_room_temperature
        above: 23
    action:
      - service: switch.turn_off
        entity_id: switch.living_room_heater
