automation:
  - id: scooter_charging
    alias: 'Scooter: Charging'
    max_exceeded: silent
    triggers:
      - trigger: numeric_state
        entity_id: sensor.scooter_charger_socket_power
        above: 30
        for:
          seconds: 15
    actions:
      - wait_for_trigger:
          - trigger: numeric_state
            entity_id: sensor.scooter_charger_socket_power
            below: 1
            for:
              minutes: 1
        timeout:
          hours: 8
        continue_on_timeout: true

      - action: switch.turn_off
        entity_id: switch.scooter_charger_socket

      - action: input_boolean.turn_on
        entity_id: input_boolean.scooter_charged

  - id: scooter_charging_socket_turn_off
    alias: 'Scooter Charging Socket: Turn off'
    triggers:
      - trigger: state
        entity_id: switch.scooter_charger_socket
        to: 'on'
        for:
          hours: 10

      - trigger: state
        entity_id: binary_sensor.porch_smoke
        to: 'on'
    actions:
      - action: switch.turn_off
        entity_id: switch.scooter_charger_socket

  - id: scooter_charged_notify
    alias: 'Scooter Charged: Notify'
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.front_door
        to: 'on'
    conditions:
      - condition: state
        entity_id: switch.scooter_charger_socket
        state: 'off'

      - condition: state
        entity_id: input_boolean.scooter_charged
        state: 'on'

      - condition: time
        before: '10:00:00'
    actions:
      - action: switch.turn_on
        entity_id: switch.scooter_charger_socket

      - wait_for_trigger:
          - platform: state
            entity_id: switch.scooter_charger_socket
            to: 'off'
        timeout:
          minutes: 5
        continue_on_timeout: true

      - action: input_boolean.turn_off
        entity_id: input_boolean.scooter_charged

      - action: switch.turn_off
        entity_id: switch.scooter_charger_socket

input_boolean:
  scooter_charged:
    name: Scooter charged
    initial: false
    icon: mdi:battery-check-outline
