template:
  - trigger:
      - trigger: time_pattern
        seconds: /2
    sensor:
      - name: Kitchen Stove Power
        unique_id: sensor.kitchen_stove_power
        state: >
          {% set power = states('sensor.stove_branch_circuit_power') | int(0) -
                         states('sensor.iot_stove_branch_circuit_power') | float(0) %}

          {% if power < 100 %}
            {# это не похоже на плиту #}
            {% set power = 0 %}
          {% endif %}

          {# при работающей посудомойке невозможно достоверно определять мощность плиты #}
          {% if not is_state('switch.dishwasher_plug', 'off') %}
            {# если розетка выключена - значит посудомойка точно выключена #}

            {% if is_state('input_select.dishwasher_status', 'Running') or
                  is_state('sensor.dishwasher_progress', 'unavailable') %}
              {% set power = 0 %}
            {% endif %}
          {% endif %}

          {{ [1, power] | max }}
        state_class: measurement
        unit_of_measurement: W
        device_class: power

  - binary_sensor:
      - name: Stove
        unique_id: binary_sensor.stove
        state: >
          {{ states('sensor.kitchen_stove_power') | int(0) > 5 }}
        device_class: running
        delay_off:
          minutes: 1

sensor:
  - platform: integration
    unique_id: sensor.kitchen_stove_energy
    name: Kitchen Stove Energy
    source: sensor.kitchen_stove_power
    unit_prefix: k
    round: 2
    method: trapezoidal
    max_sub_interval:
      seconds: 5
