automation:
  - id: stove_status_update
    alias: Stove Status Update
    trigger:
      - platform: state
        entity_id: sensor.kitchen_stove_power
    condition:
      - condition: template
        value_template: >
          {{ trigger.to_state.state|int(0) >= 200 }}
    action:
      - service: timer.start
        entity_id: timer.stove_running

template:
  - trigger:
      - platform: time_pattern
        seconds: /5
    sensor:
      - name: Kitchen Stove Power
        unique_id: sensor.kitchen_stove_power
        state: >
          {% set power = states('sensor.stove_power_supply_power')|int(0) %}
          {% if is_state('input_select.dishwasher_status', 'Running') %}
            {% set power = 0 %}
          {% endif %}

          {{ power }}
        state_class: measurement
        unit_of_measurement: W
        device_class: power

  - binary_sensor:
      - name: Stove
        unique_id: binary_sensor.stove
        state: >
          {{ is_state('timer.stove_running', 'active') }}
        device_class: running

sensor:
  - platform: integration
    unique_id: sensor.kitchen_stove_energy
    name: Kitchen Stove Energy
    source: sensor.kitchen_stove_power
    unit_prefix: k
    round: 2
    method: left

timer:
  stove_running:
    name: 'Stove: Running'
    duration:
      minutes: 2
