automation:
  - id: stove_status_update
    alias: Stove Status Update
    triggers:
      - trigger: state
        entity_id: sensor.kitchen_stove_power
    conditions:
      - condition: template
        value_template: >
          {{ trigger.to_state.state | int(0) >= 200 }}
    actions:
      - action: timer.start
        entity_id: timer.stove_running

template:
  - trigger:
      - platform: time_pattern
        seconds: /2
    sensor:
      - name: Kitchen Stove Power
        unique_id: sensor.kitchen_stove_power
        state: >
          {% set power = states('sensor.stove_branch_circuit_power') | int(0) - 30 %} {# 30 - всякая ерунда на этой линии #}

          {% if is_state('input_select.dishwasher_status', 'Running') or is_state('sensor.dishwasher_power', ['unavailable', 'unknown']) %}
            {# не совсем честно, но адекватно выделить мощность именно плиты не получится #}
            {# и в целом запуск плиты вместе с посудомойкой маловероятен #}
            {% set power = 0 %}
          {% endif %}

          {{ [0, power] | max }}
        state_class: measurement
        unit_of_measurement: W
        device_class: power

  - binary_sensor:
      - name: Stove
        unique_id: binary_sensor.stove
        state: >
          {{ is_state('timer.stove_running', 'active') }}
        device_class: running

sensor:
  - platform: integration
    unique_id: sensor.kitchen_stove_energy
    name: Kitchen Stove Energy
    source: sensor.kitchen_stove_power
    unit_prefix: k
    round: 2
    method: trapezoidal
    max_sub_interval:
      seconds: 5

timer:
  stove_running:
    name: 'Stove: Running'
    duration:
      minutes: 2
