input_select:
  washing_machine_status:
    name: Washing Machine Status
    icon: mdi:washing-machine
    options:
      - Idle
      - Running
      - Done
    initial: Idle

input_number:
  washing_machine_done_alert_count:
    name: 'Washing Machine: Done alert count'
    min: 0
    max: 5
    step: 1

automation:
  - id: washing_machine_cycle
    alias: 'Washing Machine: Cycle'
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: sensor.washing_machine_power
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state:
          - Idle
          - Done # повторный цикл без открытия дверцы

      - condition: template
        value_template: >-
          {{ trigger.to_state.state | int(0) > 5 }}
    action:
      - action: input_select.select_option
        target:
          entity_id: input_select.washing_machine_status
        data:
          option: Running

      - wait_for_trigger:
          - trigger: numeric_state
            entity_id: sensor.washing_machine_power
            below: 1
            for:
              minutes: 2
        timeout:
          hours: 4
        continue_on_timeout: true

      - condition: state
        entity_id: input_select.washing_machine_status
        state: Running

      - action: input_select.select_option
        target:
          entity_id: input_select.washing_machine_status
        data:
          option: Done

  - id: washing_machine_door_opened
    alias: 'Washing Machine: Door opened'
    triggers:
      - platform: door.opened
        target:
          entity_id: binary_sensor.washing_machine_door
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state:
          - Running
          - Done
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.washing_machine_status
        data:
          option: Idle

  - id: washing_machine_idle
    alias: 'Washing Machine: Idle'
    triggers:
      - trigger: state
        entity_id: input_select.washing_machine_status
        to: Idle
    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.washing_machine_done_alert_count
        data:
          value: 0

  - id: washing_machine_done_alert
    alias: 'Washing Machine: Done alert'
    triggers:
      - trigger: time_pattern
        minutes: '/32'

      - trigger: state
        entity_id: input_select.washing_machine_status
        from: Running
        to: Done
    conditions:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day

      - or:
          - condition: state
            entity_id:
              - binary_sensor.living_room_light_alert_available
              - binary_sensor.kitchen_light_alert_available
            state: 'off'

          - condition: template
            value_template: >-
              {{ (now() - states.input_select.washing_machine_status.last_changed) > timedelta(hours=1) }}

      - condition: state
        entity_id: input_select.washing_machine_status
        state: Done

      - condition: numeric_state
        entity_id: input_number.washing_machine_done_alert_count
        below: 4

        value_template: >-
          {{ (now() - states.input_number.washing_machine_done_alert_count.last_changed) > timedelta(minutes=15) }}
    actions:
      - wait_template: >-
          {{ not is_state('media_player.atv', ['playing', 'pause']) }}
        timeout:
          minutes: 28
        continue_on_timeout: true

      - action: script.yandex_station_tts
        data:
          target: all
          type: attention
          text: >-
            {{ states.sensor.alert_greeting.state }}
            {{ [
                'Стиральная машина ждёт тебя, в ней что-то есть.',
                'Стиральная машина закончила, пора достать из неё бельё.',
                'Стиральная машина ждет тебя, у неё для тебя есть подарок.',
                ] | random
            }}
            {% if states('input_number.washing_machine_done_alert_count') | int(0) == 2 %}
              Если я ошиблась - закрой дверцу машины и открой снова.
            {% endif %}
            {% if states('input_number.washing_machine_done_alert_count') | int(0) == 3 %}
              Это последнее предупреждение! Мокрое белье останется там навсегда!
            {% endif %}

      - action: input_number.increment
        target:
          entity_id: input_number.washing_machine_done_alert_count

  - id: washing_machine_status_by_voice
    alias: 'Washing Machine: Status (by voice)'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Что со стиральной машиной
    actions:
      - action: script.yandex_station_tts
        data:
          target: >-
            {{ trigger.event.data.get('entity_id', 'last') }}
          text: >-
            Стиралка
            {% if is_state('input_select.washing_machine_status', 'Running') %}
              делает вжух-вжух. Скоро вещи будут чистыми и пахнуть порошочком
            {% elif is_state('input_select.washing_machine_status', 'Done') %}
              закончила, доставай быстрее из неё белье и закидывай новое
            {% elif is_state('input_select.washing_machine_status', 'Idle') %}
              простаивает без дела. А как там корзина с грязным бельём?
            {% endif %}
