automation:
  - id: water_heater_turn_off
    alias: 'Water Heater: Turn off'
    trigger:
      - platform: state
        entity_id: switch.water_heater_socket
        to: 'on'

      - platform: time_pattern
        minutes: '/1'
    condition:
      - or:
          - condition: state
            entity_id:
              - switch.water_heater_socket
              - input_boolean.hot_water_supply
            state: 'on'

          - condition: state
            entity_id: input_select.washing_machine_status
            state: Running

      - condition: state
        entity_id: switch.water_heater_socket
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.water_heater_socket
