automation:
  - id: bedroom_bed_button_single_press
    alias: 'Bedroom Bed Button: Single press'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 620c20157f0cbf8a0249f3f083a531ff
        type: action
        subtype: single
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Night
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id:
                  - light.bedroom_bed
                  - light.hallway_path
                match: any
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id:
                  - group.living_room_lights
                  - group.workshop_lights
                  - light.bedroom_bed
                  - light.bedroom_moon
                  - light.hallway_path
                  - light.wardrobe

          - conditions:
              - condition: state
                entity_id: switch.bedroom_airing
                state: 'on'
            sequence:
              - service: switch.turn_off
                entity_id: switch.bedroom_airing

              - service: script.yandex_station_tts
                data:
                  target: media_player.bedroom_station
                  text: >
                    <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">

          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Night
            sequence:
              - service: light.turn_off
                entity_id:
                  - group.living_room_lights
                  - group.workshop_lights
                  - light.bedroom_bed
                  - light.hallway_path
                  - light.wardrobe

  - id: bedroom_bed_button_double_press
    alias: 'Bedroom Bed Button: Double press'
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 620c20157f0cbf8a0249f3f083a531ff
        type: action
        subtype: double
    actions:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Bedtime
        then:
          - event: good_night
          - stop:

      - if:
          - or:
              - condition: state
                entity_id: binary_sensor.warm_outside
                state: 'on'

              - condition: state
                entity_id: climate.bedroom_ac
                state: cool
        then:
          - action: timer.start
            entity_id: timer.bedroom_airing
            data:
              duration:
                hours: 1
        else:
          - action: timer.start
            entity_id: timer.bedroom_airing
            data:
              duration:
                minutes: 30

      - action: input_boolean.turn_on
        entity_id: input_boolean.bedroom_airing_cold

      - action: script.yandex_station_tts
        data:
          target: media_player.bedroom_station
          text: >
            <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">

  - id: bedroom_bed_button_hold
    alias: 'Bedroom Bed Button: Hold'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 620c20157f0cbf8a0249f3f083a531ff
        type: action
        subtype: hold
    action:
      - service: script.yandex_station_tts
        data:
          target: media_player.kitchen_station
          text: >
            <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">

  - id: bedroom_light_switch_single_right
    alias: 'Bedroom Light Switch: Single right'
    triggers:
      - trigger: device
        domain: zha
        device_id: c33420ae0c351d525f195fc6dd39d030
        type: button_single
        subtype: button_2
    actions:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Night
        then:
          - action: light.turn_on
            entity_id: light.bedroom_bed
            data:
              color_name: red
              brightness_pct: 100

          - action: light.turn_on
            entity_id: light.bedroom_moon
            data:
              rgb_color: [255, 10, 10]
              brightness_pct: 100
        else:
          - if:
              - condition: state
                entity_id: light.bedroom_bed
                state: 'on'
            then:
              - action: light.turn_off
                entity_id: light.bedroom_bed
            else:
              - action: light.turn_on
                entity_id: light.bedroom_bed
                data:
                  rgb_color: [10, 214, 255]
                  brightness_pct: 100

  - id: bedroom_light_switch_double_right
    alias: 'Bedroom Light Switch: Double right'
    triggers:
      - trigger: device
        domain: zha
        device_id: c33420ae0c351d525f195fc6dd39d030
        type: button_double
        subtype: button_2
    actions:
      - if:
          - condition: state
            entity_id: light.bedroom_moon
            state: 'on'
        then:
          - action: light.turn_off
            entity_id: light.bedroom_moon
        else:
          - action: light.turn_on
            entity_id: light.bedroom_moon
            data:
              rgb_color: [10, 214, 255]
              brightness_pct: 100
