automation:
  - id: bedroom_bed_button_single_press
    alias: 'Bedroom Bed Button: Single press'
    trigger:
      - platform: device
        domain: mqtt
        device_id: 620c20157f0cbf8a0249f3f083a531ff
        type: action
        subtype: single
        discovery_id: 0x00158d00039723b6 action_single
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id:
                  - light.bedroom_bed
                  - light.hallway_path
                match: any
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id:
                  - group.living_room_lights
                  - group.workshop_lights
                  - light.bedroom_bed
                  - light.bedroom_moon
                  - light.hallway_path
                  - light.wardrobe

          - conditions:
              - condition: state
                entity_id: input_boolean.bedroom_airing_cold
                state: 'on'
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.bedroom_airing_cold

              - service: script.yandex_station_tts
                data:
                  target: media_player.bedroom_station
                  text: >
                    <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">

          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Night
            sequence:
              - service: light.turn_off
                entity_id:
                  - group.living_room_lights
                  - group.workshop_lights
                  - light.bedroom_bed
                  - light.hallway_path
                  - light.wardrobe

  - id: bedroom_bed_button_double_press
    alias: 'Bedroom Bed Button: Double press'
    trigger:
      - platform: device
        domain: mqtt
        device_id: 620c20157f0cbf8a0249f3f083a531ff
        type: action
        subtype: double
        discovery_id: 0x00158d00039723b6 action_double
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedroom_airing_cold

      - service: script.yandex_station_tts
        data:
          target: media_player.bedroom_station
          text: >
            <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">

  - id: bedroom_bed_button_hold
    alias: 'Bedroom Bed Button: Hold'
    trigger:
      - platform: device
        domain: mqtt
        device_id: 620c20157f0cbf8a0249f3f083a531ff
        type: action
        subtype: hold
        discovery_id: 0x00158d00039723b6 action_hold
    action:
      - service: script.yandex_station_tts
        data:
          target: media_player.kitchen_station
          text: >
            <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">

  - id: bedroom_light_switch_single_right
    alias: 'Bedroom Light Switch: Single right'
    trigger:
      - platform: device
        domain: mqtt
        device_id: c109a5cffc3ce01835ed7f55ce3b8cbc
        type: action
        subtype: single_right
        discovery_id: 0x54ef441000245d07 action_single_right
    action:
      - if:
          - condition: state
            entity_id: light.bedroom_bed
            state: 'on'
        then:
          - service: light.turn_off
            entity_id: light.bedroom_bed
        else:
          - service: light.turn_on
            entity_id: light.bedroom_bed
            data:
              rgb_color: [10, 214, 255]
              brightness_pct: 100

  - id: bedroom_light_switch_double_right
    alias: 'Bedroom Light Switch: Double right'
    trigger:
      - platform: device
        domain: mqtt
        device_id: c109a5cffc3ce01835ed7f55ce3b8cbc
        type: action
        subtype: double_right
        discovery_id: 0x54ef441000245d07 action_double_right
    action:
      - if:
          - condition: state
            entity_id: light.bedroom_moon
            state: 'on'
        then:
          - service: light.turn_off
            entity_id: light.bedroom_moon
        else:
          - service: light.turn_on
            entity_id: light.bedroom_moon
            data:
              rgb_color: [10, 214, 255]
              brightness_pct: 100
