automation:
  - id: kitchen_worktop_button_turn_on
    alias: 'Kitchen Worktop Button: Turn on'
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_short_press
        subtype: turn_on
    actions:
      - if:
          - condition: state
            entity_id: light.kitchen_worktop
            state: 'off'
        then:
          - action: light.turn_on
            entity_id: light.kitchen_worktop
            data:
              brightness_pct: 100
        else:
          - action: light.turn_off
            entity_id: light.kitchen_worktop

  - id: kitchen_worktop_button_dim_down_short_press_day
    alias: 'Kitchen Worktop Button: Dim down short press (Day)'
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_short_press
        subtype: dim_down
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - action: script.turn_on
        entity_id: script.kitchen_worktop_right_light_ack_flash

      - action: script.yandex_station_tts
        data:
          target:
            - media_player.living_room_station
            - media_player.workshop_station
          type: attention
          pause_atv: true
          text: >
            {{ [
                'требуется помощь на кухне',
                'скорее подойди на кухню',
                'тебя очень ждут на кухне',
                ]|random
            }}

  - id: kitchen_worktop_button_dim_down_short_press_night
    alias: 'Kitchen Worktop Button: Dim down short press (Night)'
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_short_press
        subtype: dim_down
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: Night
    actions:
      - action: light.turn_on
        entity_id: light.kitchen_worktop
        data:
          brightness_pct: 20

  - id: kitchen_worktop_button_dim_up_short_press
    alias: 'Kitchen Worktop Button: Dim up short press'
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_short_press
        subtype: dim_up
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - action: script.turn_on
        entity_id: script.kitchen_worktop_right_light_ack_flash

      - action: script.yandex_station_tts
        data:
          target:
            - media_player.living_room_station
            - media_player.workshop_station
          type: attention
          pause_atv: true
          text: >
            {{ [
                'еда почти готова, время накрывать стол',
                'еда на подходе, скоро будем кушать',
                'бросай всё и давай поедим!',
                ]|random
            }}

  - id: kitchen_worktop_button_dim_up_long_press
    alias: 'Kitchen Worktop Button: Dim up long press'
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_long_press
        subtype: dim_up
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - action: script.turn_on
        entity_id: script.kitchen_worktop_right_light_ack_flash

      - event: kitchen_worktop_button_brightness_up_hold

  - id: kitchen_worktop_button_left_short_press
    alias: 'Kitchen Worktop Button: Left short press'
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_short_press
        subtype: left
    conditions:
      - condition: state
        entity_id: person.dextor
        state: home
    actions:
      - action: input_number.increment
        entity_id: input_number.humidifiers_water_consumption

      - action: script.kitchen_worktop_right_light_ack_flash
      - action: script.kitchen_worktop_right_light_ack_flash

      - delay:
          seconds: 10

  - id: kitchen_worktop_button_left_long_press
    alias: 'Kitchen Worktop Button: Left long press'
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_long_press
        subtype: left
    actions:
      - action: input_select.select_next
        entity_id: input_select.dishwasher_status

  - id: kitchen_worktop_button_right_short_press
    alias: 'Kitchen Worktop Button: Right short press'
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_short_press
        subtype: right
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - if:
          - condition: state
            entity_id: timer.rice_cooking
            state: active
        then:
          - action: timer.pause
            entity_id: timer.rice_cooking

          - action: timer.start
            entity_id: timer.rice_cooking

          - service: script.yandex_station_tts
            data:
              target: media_player.kitchen_station
              text: >
                Осталось примерно {{ state_attr('timer.rice_cooking', 'remaining').split(':')[1] }} мин. до полной готовности риса
        else:
          - action: timer.start
            entity_id:
              - timer.rice_cooking
              - timer.rice_almost_ready

          - action: script.turn_on
            entity_id: script.kitchen_worktop_right_light_ack_flash

  - id: kitchen_worktop_button_right_long_press
    alias: 'Kitchen Worktop Button: Right long press'
    triggers:
      - trigger: device
        domain: zha
        device_id: 7abc62119d4a89a29846de67a65da2f8
        type: remote_button_long_press
        subtype: right
    actions:
      - action: timer.cancel
        entity_id: timer.rice_cooking

      - action: script.turn_on
        entity_id: script.kitchen_worktop_right_light_ack_flash
