automation:
  - id: living_room_dinner_table_button_single_press
    alias: 'Living Room Dinner Table Button: Single press'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 9c3b7479025f7d66f4dd23a779acfd86
        type: action
        subtype: single
    condition:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    action:
      - service: script.tv_press_button
        data:
          button: play

  - id: living_room_dinner_table_button_double_press
    alias: 'Living Room Dinner Table Button: Double press'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 9c3b7479025f7d66f4dd23a779acfd86
        type: action
        subtype: double
    condition:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    action:
      - service: script.tv_press_button
        data:
          button: left

  - id: living_room_dinner_table_button_triple_press
    alias: 'Living Room Dinner Table Button: Triple press'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 9c3b7479025f7d66f4dd23a779acfd86
        type: action
        subtype: triple
    condition:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    action:
      - service: script.tv_press_button
        data:
          button: enter

  - id: living_room_light_switch_single_right
    alias: 'Living Room Light Switch: Single right'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: e0a2386c0fbe8ec9b50b6bc773b4d635
        type: action
        subtype: single_right
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.living_room_backlight
                state: 'on'

              - condition: state
                entity_id: light.living_room_backlight
                attribute: color_mode
                state: color_temp

              - condition: numeric_state
                entity_id: light.living_room_backlight
                attribute: color_temp_kelvin
                below: 4000
            sequence:
              - service: light.turn_off
                entity_id: light.living_room_backlight

          - conditions:
              - condition: state
                entity_id: light.living_room_backlight
                state: 'on'

              - condition: state
                entity_id: light.living_room_backlight
                attribute: color_mode
                state: color_temp

              - condition: numeric_state
                entity_id: light.living_room_backlight
                attribute: color_temp_kelvin
                above: 4000
            sequence:
              - service: light.turn_on
                entity_id: light.living_room_backlight
                data:
                  brightness_pct: 100
                  color_temp_kelvin: 2700
        default:
          - if:
              - condition: state
                entity_id: input_select.home_mode
                state: Night
            then:
              - service: light.turn_on
                entity_id: light.living_room_backlight
                data:
                  brightness_pct: 50
                  rgb_color: [255, 0, 0]
            else:
              - service: light.turn_on
                entity_id: light.living_room_backlight
                data:
                  brightness_pct: >
                    {% if is_state('binary_sensor.dim_light', 'on') %}
                      40
                    {% else %}
                      100
                    {% endif %}
                  color_temp_kelvin: 4200

  - id: living_room_light_switch_double_right
    alias: 'Living Room Light Switch: Double right'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: e0a2386c0fbe8ec9b50b6bc773b4d635
        type: action
        subtype: double_right
    action:
      - if:
          - condition: state
            entity_id: light.living_room_tv
            state: 'off'
        then:
          - service: light.turn_on
            entity_id: light.living_room_tv
            data:
              brightness_pct: 100
        else:
          - service: light.turn_off
            entity_id: light.living_room_tv

  - id: living_room_heater_button_turn_on
    alias: 'Living Room Heater Button: Turn on'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 624d122c903dda63a2c71e9d636f4a0c
        type: action
        subtype: 'on'
    action:
      - action: switch.turn_on
        entity_id: switch.living_room_heater

  - id: living_room_heater_button_turn_off
    alias: 'Living Room Heater Button: Turn off'
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 624d122c903dda63a2c71e9d636f4a0c
        type: action
        subtype: 'off'
    action:
      - action: switch.turn_off
        entity_id: switch.living_room_heater

  - id: living_room_heater_button_hold_down
    alias: 'Living Room Heater Button: Hold down'
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 624d122c903dda63a2c71e9d636f4a0c
        type: action
        subtype: brightness_move_down
    actions:
      - event: living_room_heater_button_hold_down
