automation:
  - id: living_room_dinner_table_button_short_press
    alias: 'Living Room Dinner Table Button: Short press'
    triggers:
      - trigger: device
        domain: zha
        device_id: fec1c0eea33eaec60ec4c2950c5aea57
        type: remote_button_short_press
        subtype: remote_button_short_press
    conditions:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    actions:
      - action: script.tv_press_button
        data:
          button: play

  - id: living_room_dinner_table_button_double_press
    alias: 'Living Room Dinner Table Button: Double press'
    triggers:
      - trigger: device
        domain: zha
        device_id: fec1c0eea33eaec60ec4c2950c5aea57
        type: remote_button_double_press
        subtype: remote_button_double_press
    conditions:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    actions:
      - action: script.tv_press_button
        data:
          button: left

  - id: living_room_dinner_table_button_triple_press
    alias: 'Living Room Dinner Table Button: Triple press'
    triggers:
      - trigger: device
        domain: zha
        device_id: fec1c0eea33eaec60ec4c2950c5aea57
        type: remote_button_triple_press
        subtype: remote_button_triple_press
    conditions:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    actions:
      - action: script.tv_press_button
        data:
          button: enter

  - id: living_room_dinner_table_button_long_press
    alias: 'Living Room Dinner Table Button: Long press'
    triggers:
      - trigger: device
        domain: zha
        device_id: fec1c0eea33eaec60ec4c2950c5aea57
        type: remote_button_long_press
        subtype: button
    actions:
      - event: living_room_dinner_table_button_hold

  - id: living_room_light_switch_single_right
    alias: 'Living Room Light Switch: Single right'
    triggers:
      - trigger: device
        domain: zha
        device_id: f54dc74d494e5deb7041ca0d637812db
        type: button_single
        subtype: button_2
    actions:
      - choose:
          - conditions:
              - condition: light.is_on
                target:
                  entity_id: light.living_room_backlight

              - condition: state
                entity_id: light.living_room_backlight
                attribute: color_mode
                state: color_temp

              - condition: numeric_state
                entity_id: light.living_room_backlight
                attribute: color_temp_kelvin
                below: 4000
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.living_room_backlight

          - conditions:
              - condition: light.is_on
                target:
                  entity_id: light.living_room_backlight

              - condition: state
                entity_id: light.living_room_backlight
                attribute: color_mode
                state: color_temp

              - condition: numeric_state
                entity_id: light.living_room_backlight
                attribute: color_temp_kelvin
                above: 4000
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.living_room_backlight
                data:
                  brightness_pct: 100
                  color_temp_kelvin: 2700
        default:
          - if:
              - condition: state
                entity_id: input_select.home_mode
                state: Night
            then:
              - action: light.turn_on
                target:
                  entity_id: light.living_room_backlight
                data:
                  brightness_pct: 50
                  rgb_color: [255, 0, 0]
            else:
              - action: light.turn_on
                target:
                  entity_id: light.living_room_backlight
                data:
                  brightness_pct: >
                    {% if is_state('binary_sensor.dim_light', 'on') %}
                      40
                    {% else %}
                      100
                    {% endif %}
                  color_temp_kelvin: 4200

  - id: living_room_light_switch_double_right
    alias: 'Living Room Light Switch: Double right'
    triggers:
      - trigger: device
        domain: zha
        device_id: f54dc74d494e5deb7041ca0d637812db
        type: button_double
        subtype: button_2
    actions:
      - action: script.living_room_cozy_light

  - id: living_room_light_switch_double_left
    alias: 'Living Room Light Switch: Double left'
    triggers:
      - trigger: device
        domain: zha
        device_id: f54dc74d494e5deb7041ca0d637812db
        type: button_double
        subtype: button_1
    actions:
      - action: light.turn_off
        target:
          entity_id: group.living_room_lights

  - id: living_room_heater_button_turn_on
    alias: 'Living Room Heater Button: Turn on'
    triggers:
      - trigger: device
        domain: zha
        device_id: 91869928aa57092360ae10b73ed11a5d
        type: remote_button_short_press
        subtype: turn_on
    conditions:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: binary_sensor.living_room_occupancy
        state:
          - 'on'
          - unavailable
    actions:
      - if:
          - condition: state
            entity_id: switch.living_room_heater
            state: unavailable
        then:
          - action: fan.turn_on
            entity_id: fan.portable
        else:
          - action: switch.turn_on
            entity_id: switch.living_room_heater

  - id: living_room_heater_button_turn_off
    alias: 'Living Room Heater Button: Turn off'
    triggers:
      - trigger: device
        domain: zha
        device_id: 91869928aa57092360ae10b73ed11a5d
        type: remote_button_short_press
        subtype: turn_off
    actions:
      - if:
          - condition: state
            entity_id: switch.living_room_heater
            state: unavailable
        then:
          - action: fan.turn_off
            entity_id: fan.portable
        else:
          - action: switch.turn_off
            entity_id: switch.living_room_heater

  - id: living_room_heater_button_hold_down
    alias: 'Living Room Heater Button: Hold down'
    triggers:
      - trigger: device
        domain: zha
        device_id: 91869928aa57092360ae10b73ed11a5d
        type: remote_button_long_press
        subtype: dim_down
    conditions:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: binary_sensor.living_room_occupancy
        state:
          - 'on'
          - unavailable
    actions:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
        then:
          - event: living_room_heater_button_hold_down
