automation:
  - id: living_room_dinner_table_button_single_press
    alias: 'Living Room Dinner Table Button: Single press'
    trigger:
      - platform: device
        domain: mqtt
        device_id: 9c3b7479025f7d66f4dd23a779acfd86
        type: action
        subtype: single
        discovery_id: 0x00158d0003cfe908 action_single
    condition:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    action:
      - service: script.tv_press_button
        data:
          button: play

  - id: living_room_dinner_table_button_double_press
    alias: 'Living Room Dinner Table Button: Double press'
    trigger:
      - platform: device
        domain: mqtt
        device_id: 9c3b7479025f7d66f4dd23a779acfd86
        type: action
        subtype: double
        discovery_id: 0x00158d0003cfe908 action_double
    condition:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    action:
      - service: script.tv_press_button
        data:
          button: left

  - id: living_room_dinner_table_button_triple_press
    alias: 'Living Room Dinner Table Button: Triple press'
    trigger:
      - platform: device
        domain: mqtt
        device_id: 9c3b7479025f7d66f4dd23a779acfd86
        type: action
        subtype: triple
        discovery_id: 0x00158d0003cfe908 action_triple
    condition:
      - condition: state
        entity_id: media_player.tv
        state: 'on'
    action:
      - service: script.tv_press_button
        data:
          button: ok

  - id: living_room_light_switch_single_right
    alias: 'Living Room Light Switch: Single right'
    trigger:
      - platform: device
        domain: mqtt
        device_id: e0a2386c0fbe8ec9b50b6bc773b4d635
        type: action
        subtype: single_right
        discovery_id: 0x54ef441000275552 action_single_right
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.living_room_backlight
                state: 'on'

              - condition: state
                entity_id: light.living_room_backlight
                attribute: color_mode
                state: color_temp

              - condition: numeric_state
                entity_id: light.living_room_backlight
                attribute: color_temp_kelvin
                below: 4000
            sequence:
              - service: light.turn_off
                entity_id: light.living_room_backlight

          - conditions:
              - condition: state
                entity_id: light.living_room_backlight
                state: 'on'

              - condition: state
                entity_id: light.living_room_backlight
                attribute: color_mode
                state: color_temp

              - condition: numeric_state
                entity_id: light.living_room_backlight
                attribute: color_temp_kelvin
                above: 4000
            sequence:
              - service: light.turn_on
                entity_id: light.living_room_backlight
                data:
                  brightness_pct: 100
                  kelvin: 2700
        default:
          - if:
              - condition: state
                entity_id: input_select.home_mode
                state: Night
            then:
              - service: light.turn_on
                entity_id: light.living_room_backlight
                data:
                  brightness_pct: 50
                  rgb_color: [255, 0, 0]
            else:
              - service: light.turn_on
                entity_id: light.living_room_backlight
                data:
                  brightness_pct: >
                    {% if is_state('binary_sensor.dim_light', 'on') %}
                      40
                    {% else %}
                      100
                    {% endif %}
                  kelvin: 4200

  - id: living_room_light_switch_double_right
    alias: 'Living Room Light Switch: Double right'
    trigger:
      - platform: device
        domain: mqtt
        device_id: e0a2386c0fbe8ec9b50b6bc773b4d635
        type: action
        subtype: double_right
        discovery_id: 0x54ef441000275552 action_double_right
    action:
      - if:
          - condition: state
            entity_id: light.living_room_tv
            state: 'off'
        then:
          - service: light.turn_on
            entity_id: light.living_room_tv
            data:
              brightness_pct: 100
        else:
          - service: light.turn_off
            entity_id: light.living_room_tv
