automation:
  - id: workshop_desk_button_turn_on
    alias: 'Workshop Desk Button: Turn on'
    mode: restart
    triggers:
      - trigger: device
        domain: zha
        device_id: 253ac67cab7668b97675475ff6396278
        type: remote_button_short_press
        subtype: turn_on
    actions:
      - action: input_boolean.toggle
        target:
          entity_id: input_boolean.workshop_airing_warm

      - action: script.turn_on
        target:
          entity_id: script.yandex_station_tts
        data:
          variables:
            target: media_player.workshop_station
            text: >
              <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">

  - id: workshop_desk_button_turn_off
    alias: 'Workshop Desk Button: Turn off'
    mode: restart
    triggers:
      - trigger: device
        domain: zha
        device_id: 253ac67cab7668b97675475ff6396278
        type: remote_button_short_press
        subtype: turn_off
    actions:
      - action: input_boolean.toggle
        target:
          entity_id: input_boolean.workshop_airing_cold

      - action: script.turn_on
        target:
          entity_id: script.yandex_station_tts
        data:
          variables:
            target: media_player.workshop_station
            text: >
              <speaker audio="dialogs-upload/31d7ae1e-6af0-40a0-8721-759585b9c331/4e413dc0-8b7c-4604-b7c4-01019abc3814.opus">
