input_boolean:
  meal:
    name: Meal
    icon: mdi:food-variant
    initial: false

automation:
  - id: meal_start
    alias: 'Meal: Start'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Время ужинать

      - trigger: event
        event_type: kitchen_worktop_button_brightness_up_hold

      - id: table_button_hold
        trigger: event
        event_type: living_room_dinner_table_button_hold
    conditions:
      - or:
          - not:
              - condition: trigger
                id: table_button_hold

          - and:
              - condition: trigger
                id: table_button_hold

              - condition: switch.is_off
                target:
                  entity_id: input_boolean.meal
    actions:
      - action: light.turn_on
        target:
          entity_id: light.living_room_tv
        data:
          brightness_pct: 100

      - service: light.turn_on
        target:
          entity_id: light.living_room_backlight
        data:
          brightness_pct: 100
          color_temp_kelvin: 4500

      - action: script.yandex_station_tts
        data:
          target: all
          text: >
            {{ [
                'Приятного аппетита',
                'Кушайте много, кушайте вкусно',
                'Вкуснятина! Давай скорее кушать',
              ]|random
            }}

      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.meal

      - if:
          - condition: state
            entity_id: media_player.tv
            state: 'off'
        then:
          - action: media_player.turn_on
            target:
              entity_id:
                - media_player.tv
                - media_player.atv

      - action: light.turn_off
        target:
          entity_id:
            - light.living_room_main
            - group.aux_lights
            - group.bedroom_lights

  - id: meal_end
    alias: 'Meal: End'
    triggers:
      - trigger: state
        entity_id: media_player.tv
        to: 'off'

      - trigger: switch.turned_on
        target:
          entity_id: input_boolean.meal
        options:
          for:
            minutes: 30

      - trigger: event
        event_type: meal_turn_off
    conditions:
      - condition: switch.is_on
        target:
          entity_id: input_boolean.meal
    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.meal

      - if:
          - condition: state
            entity_id: group.living_room_lights
            state: 'off'
        then:
          stop: Light turned off

      - if:
          - or:
              - condition: numeric_state
                entity_id: sensor.illuminance_south_side
                below: 8500

              - condition: state
                entity_id: cover.living_room
                state: closed

              - condition: state
                entity_id: input_select.season
                state: Winter

          - condition: time
            after: '12:00:00'
            before: '17:00:00'
        then:
          - action: light.turn_on
            target:
              entity_id: light.living_room_main

      - action: script.living_room_cozy_light
        data:
          leave_main_light: true

  - id: meal_end_with_airing
    alias: 'Meal: End (with airing)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_dinner_table_parked
        from: 'on'
        to: 'off'
    conditions:
      - condition: switch.is_on
        target:
          entity_id: input_boolean.meal
    actions:
      - if:
          - condition: state
            entity_id: binary_sensor.warm_outside
            state: 'on'
        then:
          - action: switch.turn_on
            target:
              entity_id: switch.home_airing
        else:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.living_room_airing_cold

      - delay:
          seconds: 1

      - event: meal_turn_off

  - id: rice_cooking_status
    alias: 'Rice Cooking: Status'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Что с рисоваркой
    actions:
      - if:
          - condition: timer.is_active
            target:
              entity_id: timer.rice_cooking
        then:
          - action: timer.pause
            target:
              entity_id: timer.rice_cooking

          - action: timer.start
            target:
              entity_id: timer.rice_cooking

      - action: script.yandex_station_tts
        data:
          target: >-
            {{ trigger.event.data.get('entity_id', 'last') }}
          text: >-
            {% if is_state('timer.rice_cooking', 'idle') %}
              Рисоварка не запущена
            {% else %}
              Осталось примерно {{ state_attr('timer.rice_cooking', 'remaining').split(':')[1] }} мин. до полной готовности
            {% endif %}

  - id: rice_almost_ready_alert
    alias: Rice almost ready alert
    triggers:
      - trigger: timer.finished
        target:
          entity_id: timer.rice_almost_ready
    conditions:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.home_mode
        state: Day
    actions:
      - action: script.yandex_station_tts
        data:
          target: all
          type: attention
          text: >-
            {{ [
                'рис почти готов',
                'рис на подходе, давай накрывать стол',
                'пахнет рисом на всю кухню, он почти готов',
                ] | random
            }}

timer:
  rice_cooking:
    name: Rice Cooking
    duration:
      minutes: 42

  rice_almost_ready:
    name: Rice Almost Ready
    duration:
      minutes: 31
