automation:
  - id: all_left_recently_alert
    alias: 'All left recently alert'
    trigger:
      platform: state
      entity_id: binary_sensor.anyone_home
      from: 'on'
      to: 'off'
      for: '00:03:00'
    condition:
      - condition: state
        entity_id: lock.front_door
        state: unlocked
    action:
      - action: notify.send_message
        entity_id: notify.dextor
        data:
          message: 🔑 Никого нет дома, а дверь не закрыта. Страшно?

  - id: motion_alarm_no_one_home
    alias: 'Motion Alarm: No one home'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_anywhere
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id:
          - binary_sensor.anyone_home
          - binary_sensor.anyone_near_home
        state: 'off'

      # дикая кошка постоянно вызывает сработки некоторых датчиков
      - condition: state
        entity_id: input_select.home_mode
        state: Vacation

      - condition: template
        value_template: >
          {{ (now() - state_attr('automation.motion_alarm_no_one_home',
                                  'last_triggered')|default(now() - timedelta(days=1), true)).total_seconds() > 600 }}
    action:
      - action: notify.send_message
        data:
          entity_id: notify.dextor
          message: 👮 Движение дома, хотя там никого нет? Нас грабют!

  - id: front_door_opened_alert
    alias: 'Front Door: Opened alert'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: 'off'
        to: 'on'
        for:
          minutes: 15

      - platform: state
        entity_id: binary_sensor.front_door
        from: 'off'
        to: 'on'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: lock.front_door
        state: unlocked
    action:
      - service: script.yandex_station_tts
        data:
          target: all
          type: attention
          text: >
            {{ states.sensor.alert_greeting.state }}
            {{ [
                'Входная дверь не защелкнута, сходи проверь',
                'Мы кого-то ждем? Входная дверь не прикрыта',
                'Прикрой входную дверь, а то украдут!'
                ]|random
            }}

  - id: porch_door_opened_alert
    alias: 'Porch Door: Opened alert'
    trigger:
      - platform: state
        entity_id: binary_sensor.porch_door
        to: 'on'
        for:
          hours: 12

      - platform: state
        entity_id: lock.porch_door
        to: 'unlocked'
        for:
          hours: 12
    action:
      - action: notify.send_message
        data:
          entity_id: notify.dextor
          message: 🔑 Дверь на крыльцо долго открыта. Это вообще нормально?!
