automation:
  - id: sensor_unknown_alert
    alias: Sensor unknown alert
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: state_changed
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state:
          - Day
          - Night

      - and:
          - condition: template
            value_template: >
              {{ trigger.event.data.new_state and
                 trigger.event.data.new_state.state == 'unknown' and
                 trigger.event.data.new_state.attributes.get('state_class') == 'measurement' }}

          - condition: template
            value_template: >
              {{ (now() - state_attr('automation.sensor_unknown_alert',
                                      'last_triggered')|default(now() - timedelta(days=1), true)).total_seconds() > 1800 }}
    action:
      - delay:
          minutes: 10

      - condition: template
        value_template: >
          {% set ns = namespace(break = false) %}
          {%- for entity in states if entity.state == 'unknown' and
                                      entity.attributes.get('state_class') == 'measurement' and
                                      entity.entity_id and ns.break == false -%}
            {%- if (now() - entity.last_changed).total_seconds() > 180 and
                    not is_state_attr(entity.entity_id, 'volatile', true) and
                    not is_state_attr(entity.entity_id, 'restored', true) -%}
              {%- set ns.break = true -%}
              true
            {%- endif -%}
          {%- endfor %}

      - action: notify.send_message
        data:
          entity_id: notify.dextor
          message: >
            ⚠️ <b>Некоторые датчики недоступны:</b>{{ '\n' }}
            {%- for entity in states if entity.state == 'unknown' and
                                        entity.attributes.get('state_class') == 'measurement' and
                                        not is_state_attr(entity.entity_id, 'volatile', true) and
                                        not is_state_attr(entity.entity_id, 'restored', true) -%}
            * {{ entity.name }}: {{ entity.last_changed|relative_time }}{{ '\n' }}
            {%- endfor -%}

  - id: sensor_unknown_log
    alias: Sensor unknown log
    mode: parallel
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: state_changed
    condition:
      - condition: template
        value_template: >
          {{ trigger.event.data.new_state and
             trigger.event.data.new_state.state == 'unknown' and
             trigger.event.data.new_state.attributes.get('state_class') == 'measurement' }}
    action:
      - service: notify.send_message
        data:
          entity_id: notify.debug
          message: "Sensor unknown: {{ trigger.event.data.new_state.entity_id }}"
