packages:
  base: !include ../generic/livebest_wb02a_plug.yaml

substitutions:
  relay_restore_mode: ALWAYS_ON
  mac_trailer: 21
  bl0937_current_resistor: 0.00106
  bl0937_voltage_divider: 1615.35

esphome:
  name: livebest-plug-21
  name_add_mac_suffix: false
