esphome:
  name_add_mac_suffix: true
  min_version: 2024.11.0

api:
  reboot_timeout: 0s

captive_portal:

logger:
  level: DEBUG

ota:
  - id: ota_esphome
    platform: esphome
    password: !secret password

safe_mode:
  num_attempts: 5

preferences:
  flash_write_interval: 3min

wifi:
  ssid: !secret ssid
  password: !secret password
  reboot_timeout: 0s
  fast_connect: true
  ap:
    password: !secret password
    ap_timeout: 1min
