esphome:
  name_add_mac_suffix: true
  min_version: 2026.7.1
  merge_warnings: false

external_components:
  - source: lib

api:
  # очень сомнительное значение:
  # компромис между частыми перезагрузками при обслуживании HA
  # и полным повисанием, когда дома долго никого нет
  reboot_timeout: 12h
  on_client_connected:
    - script.stop: go_offline
    - script.execute: go_online
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
            state_subscription_only: true
      then:
        - script.execute: go_offline

captive_portal:

logger:
  level: DEBUG

ota:
  - id: ota_esphome
    platform: esphome
    password: !secret password

safe_mode:
  num_attempts: 3
  reboot_timeout: 15min
  on_safe_mode:
    then:
      - lambda: >-
          id(wifi_).set_ap_timeout(10000);

preferences:
  flash_write_interval: 3min

time:
  - platform: homeassistant
    timezone: Europe/Moscow
    on_time_sync:
      then:
        - logger.log: Synchronized system clock

wifi:
  id: wifi_
  ssid: !secret ssid
  password: !secret password
  reboot_timeout: 0s # перезагрузится по api.reboot_timeout
  fast_connect: true
  ap:
    password: !secret password
    # будет включаться только в safe_mode
    # если включать при каждом недоступности основной точки -
    # эфир будет заспален 50+ левыми AP, которые не очень нужно видеть соседям
    ap_timeout: 0s

sensor:
  - platform: uptime
    name: Boot Time
    type: timestamp

  - platform: uptime
    name: Uptime
    update_interval: 45s
    internal: true

script:
  # выполняется через 1 минуту после отключения всех API клиентов
  # расширяется в конкретном устройстве через !extend go_offline
  - id: go_offline
    mode: restart
    then:
      - delay: 10min
      - logger.log:
          format: Going offline
          level: WARN

  # выполняется при каждом подключении клиента
  - id: go_online
    mode: restart
    then: []
