esphome:
  name_add_mac_suffix: true

api:
  reboot_timeout: 0s

captive_portal:

logger:
  level: DEBUG

ota:
  password: !secret password
  num_attempts: 5

preferences:
  flash_write_interval: 3min

wifi:
  ssid: !secret ssid
  password: !secret password
  reboot_timeout: 0s
  fast_connect: true
  ap:
    password: !secret password
    ap_timeout: 1min
