external_components:
  - source: github://dentra/esphome-tion@18952225d15095a9340d390818557240f0ba62ce # next
  - source: github://dentra/esphome-components@c3f324689a391eccdc82b7edef662e0aaf7aed99
    components:
      - crash_info
      - cgp
      - etl
      - vport

esphome:
  min_version: 2026.2.0

ota:
  - id: !extend ota_esphome
    on_begin:
      then:
        - lambda: id(tion_ble_client).set_enabled(false);

ble_client:
  - mac_address: $tion_mac_address
    id: tion_ble_client
    on_connect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Disconnected from BLE device");

vport:
  - platform: tion_4s_ble
    id: tion_ble_vport
    ble_client_id: tion_ble_client
    persistent_connection: true
    disable_scan: false

tion:
  type: 4s
  vport_id: tion_ble_vport
  update_interval: 20s
  state_timeout: 10s
  force_update: true

climate:
  - platform: tion
    name: $tion_device_name

binary_sensor:
  - platform: tion
    name: $tion_device_name No Response
    type: state

button:
  - platform: tion
    name: $tion_device_name Reset filter
    type: reset_filter

sensor:
  - platform: tion
    name: $tion_device_name Outdoor Temperature
    type: outdoor_temperature
    filters:
      - or:
          - throttle: 30min
          - delta: 2
      - timeout: 35min

  - platform: tion
    name: $tion_device_name Filter Time Left
    type: filter_time_left_days

  - id: tion_heater_power
    platform: tion
    name: $tion_device_name Heater Power
    type: heater_power
    filters:
      - timeout: 1min

  # см. energy.yaml
  - id: tion_heater_power_adj
    name: $tion_device_name Power Adjusted
    platform: template
    internal: true
    update_interval: never
    unit_of_measurement: W
    accuracy_decimals: 0
    filters:
      - clamp:
          min_value: 0

  - platform: total_daily_energy
    name: $tion_device_name Energy
    unit_of_measurement: kWh
    accuracy_decimals: 2
    power_id: tion_heater_power_adj
    method: trapezoid
    filters:
      - multiply: 0.001
      - throttle: 10min

interval:
  - interval: 10s
    then:
      - lambda: |-
            if (std::isnan(id(tion_heater_power).state)) {
                id(tion_heater_power_adj).publish_state(0);
            }

switch:
  - platform: tion
    name: $tion_device_name LED
    type: led

  - platform: tion
    name: $tion_device_name Recirculation
    type: recirculation

text_sensor:
  - platform: tion
    name: $tion_device_name Errors
    type: errors
    icon: mdi:alert-circle-outline
