external_components:
  - source: github://dentra/esphome-tion@00019c4346369ac8dc444bf1fb779002b0350fb6 # next
  - source: github://dentra/esphome-components@43e6fd481f8cb228505120f93b997867bf39ccaf
    components:
      - crash_info
      - cgp
      - etl
      - vport

esphome:
  min_version: 2026.2.0

ota:
  - id: !extend ota_esphome
    on_begin:
      then:
        - lambda: id(tion_ble_client).set_enabled(false);

ble_client:
  - mac_address: $tion_mac_address
    id: tion_ble_client
    on_connect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Disconnected from BLE device");

vport:
  - platform: tion_4s_ble
    id: tion_ble_vport
    ble_client_id: tion_ble_client
    persistent_connection: true
    disable_scan: false

tion:
  type: 4s
  vport_id: tion_ble_vport
  update_interval: 5s
  state_timeout: 3s
  force_update: true

climate:
  - platform: tion
    name: ''
    device_id: $tion_device_id

binary_sensor:
  - platform: tion
    name: No Response
    type: state
    device_id: $tion_device_id

button:
  - platform: tion
    name: Reset filter
    type: reset_filter
    device_id: $tion_device_id

sensor:
  - platform: tion
    name: Outdoor Temperature
    type: outdoor_temperature
    device_id: $tion_device_id
    filters:
      - or:
          - throttle: 30min
          - delta: 2
      - timeout: 35min

  - platform: tion
    name: Filter Time Left
    type: filter_time_left_days
    device_id: $tion_device_id

  - id: tion_power
    name: Power
    platform: tion
    type: power
    device_id: $tion_device_id
    unit_of_measurement: W
    accuracy_decimals: 0
    entity_category: ''
    filters:
      - multiply: 1000
      - round: 0
      - timeout: 20s
    on_value:
      - sensor.template.publish:
          id: tion_power_adj
          state: !lambda return x;

  - id: tion_power_adj
    name: Power Adjusted
    platform: template
    device_id: $tion_device_id
    internal: true
    update_interval: never
    unit_of_measurement: W
    accuracy_decimals: 0
    filters:
      - clamp:
          min_value: 0

  - id: energy
    name: Energy
    platform: integration
    device_id: $tion_device_id
    sensor: tion_power_adj
    time_unit: h
    integration_method: trapezoid
    restore: true
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
      - throttle: 5min

interval:
  - interval: 10s
    then:
      - lambda: |-
          if (std::isnan(id(tion_power).state)) {
              id(tion_power_adj).publish_state(0);
          }

switch:
  - platform: tion
    name: LED
    type: led
    device_id: $tion_device_id

  - platform: tion
    name: Recirculation
    type: recirculation
    device_id: $tion_device_id

text_sensor:
  - platform: tion
    name: Errors
    type: errors
    device_id: $tion_device_id
    icon: mdi:alert-circle-outline
