external_components:
  - source: github://dentra/esphome-tion@2024.1.2
  - source: github://dentra/esphome-components@2023.2.0
    components: [crash_info, etl, vport]

esphome:
  min_version: 2024.11.0

ota:
  - platform: esphome
    on_begin:
      then:
        - lambda: id(tion_ble_client).set_enabled(false);

ble_client:
  - mac_address: $tion_mac_address
    id: tion_ble_client
    on_connect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Disconnected from BLE device");

vport:
  - platform: tion_4s
    id: tion_ble_vport
    ble_client_id: tion_ble_client
    persistent_connection: true
    disable_scan: false

climate:
  - id: tion_ble
    platform: tion_4s
    name: $tion_device_name
    vport_id: tion_ble_vport
    update_interval: 20s
    state_timeout: 10s

    led:
      name: $tion_device_name LED
    recirculation:
      name: $tion_device_name Recirculation
    outdoor_temperature:
      name: $tion_device_name Outdoor Temperature
    heater_power:
      id: tion_heater_power
      name: $tion_device_name Heater Power
    filter_time_left:
      name: $tion_device_name Filter Time Left
    reset_filter:
      name: $tion_device_name Reset filter
    state_warnout:
      name: $tion_device_name No Response
    errors:
      name: $tion_device_name Errors
      icon: mdi:alert-circle-outline

sensor:
  - platform: total_daily_energy
    name: $tion_device_name Energy
    unit_of_measurement: kWh
    accuracy_decimals: 2
    power_id: tion_heater_power
    filters:
      - multiply: 0.001
