external_components:
  - source: github://dentra/esphome-tion@00019c4346369ac8dc444bf1fb779002b0350fb6 # next
  - source: github://dentra/esphome-components@43e6fd481f8cb228505120f93b997867bf39ccaf
    components:
      - crash_info
      - cgp
      - etl
      - vport

esphome:
  min_version: 2026.2.0

ota:
  - id: !extend ota_esphome
    on_begin:
      then:
        - lambda: id(tion_ble_client).set_enabled(false);

ble_client:
  - mac_address: $tion_mac_address
    id: tion_ble_client
    on_connect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGV("tion_ble_client", "Disconnected from BLE device");

vport:
  - platform: tion_4s_ble
    id: tion_ble_vport
    ble_client_id: tion_ble_client
    persistent_connection: true
    disable_scan: false

tion:
  type: 4s
  vport_id: tion_ble_vport
  update_interval: 10s
  state_timeout: 1s
  force_update: true

climate:
  - id: tion_climate
    platform: tion
    device_id: $tion_device_id
    on_state:
      - sensor.template.publish:
          id: tion_current_temperature
          state: !lambda return x.current_temperature;

  - name: ''
    platform: climate_template
    device_id: $tion_device_id
    icon: mdi:air-filter
    optimistic: false
    supported_modes: ['off', 'heat', 'fan_only']
    custom_fan_modes: ['1', '2', '3', '4', '5', '6']
    mode: !lambda return id(tion_climate).mode;
    custom_fan_mode: !lambda return id(tion_climate).get_custom_fan_mode();
    current_temperature: !lambda return id(tion_current_temperature).state;
    target_temperature: !lambda return id(tion_climate).target_temperature;
    set_target_temperature_action:
      - climate.control:
          id: tion_climate
          target_temperature: !lambda return x;
    set_mode_action:
      - climate.control:
          id: tion_climate
          mode: !lambda return x;
    set_custom_fan_mode_action:
      - climate.control:
          id: tion_climate
          custom_fan_mode: !lambda return x;
    visual:
      min_temperature: 1
      max_temperature: 25
      temperature_step: 1

binary_sensor:
  - platform: tion
    name: No Response
    type: state
    device_id: $tion_device_id
    filters:
      - delayed_on: 10s

button:
  - platform: tion
    name: Reset filter
    type: reset_filter
    device_id: $tion_device_id

sensor:
  - id: tion_current_temperature
    platform: template
    update_interval: never
    unit_of_measurement: '°C'
    accuracy_decimals: 0
    filters:
      - or:
          - throttle: 15min
          - delta: 2
      - timeout: 35min

  - platform: tion
    name: Outdoor Temperature
    type: outdoor_temperature
    device_id: $tion_device_id
    filters:
      - or:
          - throttle: 15min
          - delta: 2
      - timeout: 35min

  - platform: tion
    name: Filter Time Left
    type: filter_time_left_days
    device_id: $tion_device_id

switch:
  - platform: tion
    name: LED
    type: led
    device_id: $tion_device_id

  - platform: tion
    name: Recirculation
    type: recirculation
    device_id: $tion_device_id

text_sensor:
  - platform: tion
    name: Errors
    type: errors
    device_id: $tion_device_id
    icon: mdi:alert-circle-outline
