
automation:
  - id: bedroom_ac_display_turn_off
    alias: 'Bedroom AC Display: Turn off'
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        to: Night

      - trigger: state
        entity_id: climate.bedroom_ac
        from: 'off'
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: Night

      - condition: state
        entity_id: climate.bedroom_ac
        state:
          - heat_cool
          - cool
          - heat
          - dry
    actions:
      - delay:
          seconds: 2

      - condition: state
        entity_id: switch.bedroom_ac_display
        state: 'on'

      - action: switch.turn_off
        entity_id: switch.bedroom_ac_display

  - id: bedroom_ac_cool_for_sleep
    alias: 'Bedroom AC: Cool for sleep'
    description: Пытается охладить комнату в морозильник перед сном
    triggers:
      - trigger: time
        at: '23:00:00'
    conditions:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      - condition: state
        entity_id: input_select.season
        state: Summer

      - condition: numeric_state
        entity_id: sensor.outside_temperature
        above: 4 # ну мало ли слишком холодное лето :D

      - not:
        - condition: state
          entity_id: climate.bedroom_ac
          state: unavailable
    actions:
      - action: climate.set_temperature
        entity_id: climate.bedroom_ac
        data:
          hvac_mode: cool
          temperature: 20

      - delay:
          seconds: 5

      - action: climate.set_fan_mode
        entity_id: climate.bedroom_ac
        data:
          fan_mode: high

  - id: bedroom_ac_night_cool
    alias: 'Bedroom AC: Night cool'
    description: Переключает кондиционер в ночное охлаждение
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        to: Night
    conditions:
      - condition: state
        entity_id: climate.bedroom_ac
        state: cool
    actions:
      - action: climate.set_temperature
        entity_id: climate.bedroom_ac
        data:
          hvac_mode: cool
          temperature: 22

      - delay:
          seconds: 5

      - action: climate.set_fan_mode
        entity_id: climate.bedroom_ac
        data:
          fan_mode: auto

  - id: bedroom_ac_turn_off
    alias: 'Bedroom AC: Turn off'
    triggers:
      - trigger: state
        entity_id: binary_sensor.anyone_home
        from: 'on'
        to: 'off'
        for:
          minutes: 20

      - trigger: state
        entity_id: climate.bedroom_ac
        to:
          - heat_cool
          - cool
          - heat
          - dry
        for:
          hours: 24

      - trigger: state
        entity_id: input_select.home_mode
        from: Night
        for:
          minutes: 5

      - trigger: numeric_state
        entity_id: sensor.cb_branch_circuit_power
        above: 3600
    conditions:
      - condition: state
        entity_id: climate.bedroom_ac
        state:
          - heat_cool
          - cool
          - heat
          - dry
    actions:
      - action: climate.turn_off
        entity_id: climate.bedroom_ac

  - id: bedroom_ac_display_update
    alias: 'Bedroom AC Display: Update'
    triggers:
      - id: 'on'
        trigger: state
        entity_id: climate.bedroom_ac
        from: 'off'
        to:
          - heat_cool
          - cool
          - heat
          - dry

      - id: 'off'
        trigger: state
        entity_id: climate.bedroom_ac
        from:
          - heat_cool
          - cool
          - heat
          - dry
        to: 'off'
    actions:
      - if:
          - condition: trigger
            id: 'on'
        then:
          - action: input_boolean.turn_on
            entity_id: input_boolean.bedroom_ac_display
        else:
          - action: input_boolean.turn_off
            entity_id: input_boolean.bedroom_ac_display

  - id: bedroom_ac_turn_off_protect
    alias: 'Bedroom AC: Turn off (protect)'
    triggers:
      - trigger: time_pattern
        seconds: /30

      - trigger: state
        entity_id:
          - climate.bedroom_ac
          - input_select.washing_machine_status
    conditions:
      - or:
          - condition: numeric_state
            entity_id: sensor.outside_temperature
            below: -15

          - and:
              - condition: state
                entity_id: input_select.washing_machine_status
                state: Running

              - condition: state
                entity_id: climate.workshop_ac
                state:
                  - heat_cool
                  - cool
                  - heat
                  - dry

      - condition: state
        entity_id: climate.bedroom_ac
        state:
          - heat_cool
          - cool
          - heat
          - dry
    actions:
      - action: climate.turn_off
        entity_id: climate.bedroom_ac

template:
  - switch:
      - unique_id: switch.bedroom_ac_display
        name: 'Bedroom AC: Display'
        icon: mdi:camera-control
        state: >
          {{ is_state('input_boolean.bedroom_ac_display', 'on') }}
        turn_on:
          - if:
              - condition: state
                entity_id: climate.bedroom_ac
                state:
                  - heat_cool
                  - cool
                  - heat
                  - dry
            then:
              - action: input_boolean.turn_on
                entity_id: input_boolean.bedroom_ac_display

              - action: button.press
                entity_id: button.bedroom_ac_display_toggle
        turn_off:
          parallel:
            - action: input_boolean.turn_off
              entity_id: input_boolean.bedroom_ac_display

            - action: button.press
              entity_id: button.bedroom_ac_display_toggle

input_boolean:
  bedroom_ac_display:
    name: 'Bedroom AC: Display'
    icon: mdi:camera-control
