energy:
config:
frontend:
  extra_module_url:
    - /hacsfiles/ha-yandex-icons/yandex-icons.js
  themes: !include_dir_merge_named themes
history:
homeassistant:
  allowlist_external_dirs:
    - /config
  packages:
    ac_bedroom: !include devices/ac/bedroom.yaml
    ac_workshop: !include devices/ac/workshop.yaml
    activity_cinema: !include activities/cinema.yaml
    activity_meal: !include activities/meal.yaml
    activity_waking_up: !include activities/waking_up.yaml
    alert_devices: !include alerts/devices.yaml
    alert_security: !include alerts/security.yaml
    alert_sensors: !include alerts/sensors.yaml
    alice_tests: !include devices/alice_tests.yaml
    buttons_bathroom: !include devices/buttons/bathroom.yaml
    buttons_bedroom: !include devices/buttons/bedroom.yaml
    buttons_kitchen: !include devices/buttons/kitchen.yaml
    buttons_living_room: !include devices/buttons/living_room.yaml
    buttons_workshop: !include devices/buttons/workshop.yaml
    climate: !include devices/climate.yaml
    covers_bedroom: !include devices/covers/bedroom.yaml
    covers_kitchen: !include devices/covers/kitchen.yaml
    covers_living_room: !include devices/covers/living_room.yaml
    covers_workshop: !include devices/covers/workshop.yaml
    devices_ups: !include devices/ups.yaml
    dishwasher: !include devices/dishwasher.yaml
    dryer: !include devices/dryer.yaml
    doorbell: !include devices/doorbell.yaml
    fridge: !include devices/fridge.yaml
    home_common: !include home/common.yaml
    home_delivery: !include home/delivery.yaml
    home_energy: !include home/energy.yaml
    home_guests: !include home/guests.yaml
    home_kitchen: !include home/kitchen.yaml
    home_pill: !include home/pill.yaml
    home_presence: !include home/presence.yaml
    home_smoke: !include home/smoke.yaml
    home_water: !include home/water.yaml
    home_welcome_home: !include home/welcome_home.yaml
    home_modes: !include home/modes.yaml
    home_mode_night: !include home/modes/night.yaml
    home_mode_morning: !include home/modes/morning.yaml
    home_mode_day: !include home/modes/day.yaml
    home_mode_evening: !include home/modes/evening.yaml
    home_mode_bedtime: !include home/modes/bedtime.yaml
    home_mode_vacation: !include home/modes/vacation.yaml
    hotaru: !include devices/hotaru.yaml
    humidifiers_bedroom: !include devices/humidifiers/bedroom.yaml
    humidifiers_living_room: !include devices/humidifiers/living_room.yaml
    humidifiers_workshop: !include devices/humidifiers/workshop.yaml
    humidifiers: !include devices/humidifiers.yaml
    intake_fans: !include devices/intake_fans.yaml
    intake_fan_bedroom: !include devices/intake_fans/bedroom.yaml
    intake_fan_living_room: !include devices/intake_fans/living_room.yaml
    intake_fan_workshop: !include devices/intake_fans/workshop.yaml
    intercom: !include devices/intercom.yaml
    ironing_board: !include devices/ironing_board.yaml
    ios: !include devices/ios.yaml
    kettle: !include devices/kettle.yaml
    lights_bathroom: !include devices/lights/bathroom.yaml
    lights_bedroom: !include devices/lights/bedroom.yaml
    lights_closet: !include devices/lights/closet.yaml
    lights_hallway: !include devices/lights/hallway.yaml
    lights_kitchen: !include devices/lights/kitchen.yaml
    lights_living_room_cozy: !include devices/lights/living_room_cozy.yaml
    lights_living_room_tv: !include devices/lights/living_room_tv.yaml
    lights_living_room: !include devices/lights/living_room.yaml
    lights_path: !include devices/lights/path.yaml
    lights_porch: !include devices/lights/porch.yaml
    lights_status: !include devices/lights/status.yaml
    lights_wardrobe: !include devices/lights/wardrobe.yaml
    lights_workshop: !include devices/lights/workshop.yaml
    lights_xmas: !include devices/lights/xmas.yaml
    lights: !include devices/lights.yaml
    lock_front_door: !include devices/locks/front_door.yaml
    lock_porch_door: !include devices/locks/porch_door.yaml
    locks: !include devices/locks.yaml
    media_avr: !include devices/media/avr.yaml
    media_tv: !include devices/media/tv.yaml
    media_yandex_station: !include devices/media/yandex_station.yaml
    portable_fan: !include devices/portable_fan.yaml
    portable_heater: !include devices/portable_heater.yaml
    scooter: !include devices/scooter.yaml
    stove: !include devices/stove.yaml
    washing_machine: !include devices/washing_machine.yaml
    water_heater: !include devices/water_heater.yaml
  customize: !include customize.yaml
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies: 172.30.33.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 5
notify:
  - platform: telegram
    name: dextor
    chat_id: !secret telegram_chat_id
none:
logbook:
  exclude:
    entity_globs:
      - automation.*_no_occupancy
      - sensor.*_uptime
      - sensor.*_debug
logger:
  default: warning
  logs:
    custom_components.yandex_smart_home: debug
    custom_components.yandex_smart_home.notifier: info
    custom_components.yandex_station_intents: debug
    custom_components.yandex_station: debug
    zigpy: info
    zha: info
mobile_app:
my:
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 365
  include:
    domains:
      - alert
      - automation
      - binary_sensor
      - climate
      - cover
      - fan
      - humidifier
      - input_boolean
      - input_datetime
      - input_select
      - light
      - lock
      - media_player
      - person
      - sensor
      - sun
      - switch
      - weather
    entities:
      - select.intercom_mode
      - number.living_room_humidifier_fan_speed
      - switch.bedroom_moon_light_charger # обход исключения switch.*_light*
      - timer.come_back_soon
  exclude:
    entities:
      - automation.yandex_station_busy
      - sensor.alert_greeting
      - sensor.chores
      - sensor.kettle_water_temperature
      - sensor.pingzen_heartbeat
    entity_globs:
      - '*.0x*'
      - '*.*_target_*' # вычисляемые значения, которые применяются к устройствам
      - automation.*_log # логирование скучных вещей
      - automation.*_update # часто вычисление состояния (например по таймеру)
      - automation.*_timer # включение/отключение различных таймеров
      - cover.*_motor  # сырые моторы для шаблонных штор с ограничением открытия
      - binary_sensor.*_contact  # сырые герконы для шаблонов
      - binary_sensor.*presence*layma*
      - binary_sensor.*presence*misaka*
      - binary_sensor.*workday*
      - binary_sensor.workday*
      - binary_sensor.*_light_alert_available # доступность функции "уведомление через диодик"
      - input_boolean.*_airing_* # проветривания, статус отслеживается через выключатель
      - input_boolean.porch_light_dimmed
      - light.workshop_main_* # обрабатывается как единое целое
      - sensor.*_raw
      - sensor.person_pronoun_*
      - switch.*_light* # из них делается light на шаблоне
panel_custom:
  - name: config/automation
    sidebar_title: Automations
    sidebar_icon: mdi:home-automation
    module_url: internal

  - name: config/integrations
    sidebar_title: Integrations
    sidebar_icon: mdi:puzzle
    module_url: internal

  - name: developer-tools/yaml
    sidebar_title: Server Controls
    sidebar_icon: mdi:server
    module_url: internal

  - name: config/logs
    sidebar_title: Logs
    sidebar_icon: mdi:math-log
    module_url: internal
person:
stream:
sun:
system_health:
system_log:
  fire_event: true
wake_on_lan:
yandex_smart_home: !include yandex_smart_home.yaml
yandex_station_intents: !include yandex_station_intents.yaml
zha: !include zha.yaml
