packages:
  base: !include common/esp8266.yaml

esphome:
  friendly_name: Bathroom Path Light
  area: Bathroom
  name: bathroom-path-light
  model: Wemos
  name_add_mac_suffix: false

light:
  - id: light_toilet
    name: Toilet
    platform: neopixelbus
    pin: 14
    type: GRBW
    variant: SK6812
    num_leds: 27
    gamma_correct: 1
    restore_mode: ALWAYS_OFF

  - id: light_sink
    name: Sink
    platform: neopixelbus
    pin: 12
    type: GRBW
    variant: SK6812
    num_leds: 31
    gamma_correct: 1
    restore_mode: ALWAYS_OFF

script:
  - id: !extend go_offline
    then:
      - light.turn_off: light_toilet
      - light.turn_off: light_sink
