packages:
  base: !include generic/sonoff_basic_r2_light.yaml

esphome:
  friendly_name: Bathroom Bathtub Light
  area: Bathroom
  name: bathroom-bathtub-light
  name_add_mac_suffix: false

script:
  - id: !extend go_offline
    then:
      - light.turn_off: light_w
