packages:
  base: !include generic/midea_ac.yaml

substitutions:
  temperature_sensor: sensor.bedroom_temperature

esphome:
  friendly_name: Bedroom AC
  area: Bedroom
  name: bedroom-ac
  model: MSAG1-09N8C2 / ESP8266
  name_add_mac_suffix: false
