# https://aliexpress.ru/item/1005001413871316.html
packages:
  base: !include common/esp8266.yaml

esphome:
  friendly_name: Bedroom Moon Light
  area:
    id: bedroom
    name: Bedroom
  name: bedroom-moon-light
  model: Hiper IOT HI-IR1 / Relay
  name_add_mac_suffix: false
  includes:
    - lib/rgb.h

  devices:
    - id: string_light
      name: Bedroom String Light
      area_id: bedroom

logger:
  baud_rate: 0

globals:
  - id: current_ir_brightness
    type: int
    restore_value: no
    initial_value: '0'

  - id: current_ir_color
    type: int
    restore_value: no
    initial_value: '0'

remote_receiver:
  pin:
    number: 5
    inverted: true
  dump: all

remote_transmitter:
  id: ir
  pin: 14
  carrier_duty_percent: 50%

light:
  - id: light_rgb
    platform: rgb
    name: ''
    icon: mdi:lightbulb-night-outline
    red: dummy_pmw
    green: dummy_pmw
    blue: dummy_pmw
    default_transition_length: 0s
    on_state:
      - if:
          condition:
            light.is_off: light_rgb
          then:
            - remote_transmitter.transmit_nec:
                address: 0xEF00
                command: 0xFD02 # turn off

      - if:
          condition:
            light.is_on: light_rgb
          then:
            - remote_transmitter.transmit_nec:
                address: 0xEF00
                command: 0xFC03 # turn on

            - if:
                condition:
                  lambda: |-
                    auto v = id(light_rgb).remote_values;
                    int target_color = rgbToInt(int(v.get_red() * 255), int(v.get_green() * 255), int(v.get_blue() * 255));
                    return target_color != id(current_ir_color);
                then:
                  - remote_transmitter.transmit_nec:
                      address: 0xEF00
                      command: !lambda |-
                        auto v = id(light_rgb).remote_values;
                        int target_color = rgbToInt(int(v.get_red() * 255), int(v.get_green() * 255), int(v.get_blue() * 255));
                        id(current_ir_color) = target_color;
                        switch (target_color) {
                          case 16777215: return 0xF807;  // white
                          case 16714250: return 0xFB04;  // red       (R)
                          case 16727040: return 0xF708;  // orange    (R-1)
                          case 16729907: return 0xF30C;  // coral     (R-2)
                          case 13303562: return 0xEF10;  // lime      (R-3)
                          case 16740362: return 0xEB14;  // yellow    (R-4)
                          case 720711:   return 0xFA05;  // green     (G)
                          case 720813:   return 0xF609;  // emerald   (G-1)
                          case 720883:   return 0xF20D;  // turquoise (G-2)
                          case 15067647: return 0xEE11;  // moonlight (G-3)
                          case 710399:   return 0xEA15;  // cyan      (G-4)
                          case 673791:   return 0xF906;  // blue      (B)
                          case 11340543: return 0xF50A;  // violet    (B-1)
                          case 8719103:  return 0xF10E;  // lavender  (B-2)
                          case 16714393: return 0xED12;  // orchid    (B-3)
                          case 16714471: return 0xE916;  // purple    (B-4)
                          case 16722742: return 0xE916;  // mauve
                          case 16711765: return 0xE916;  // raspberry
                          default:       return 0x0000;
                        }

            - while:
                condition:
                  lambda: 'return int(id(light_rgb).remote_values.get_brightness() * 10) > id(current_ir_brightness);'
                then:
                  - lambda: 'id(current_ir_brightness)++;'
                  - remote_transmitter.transmit_nec:
                      address: 0xEF00
                      command: 0xFF00
                  - delay: 10ms

            - while:
                condition:
                  lambda: 'return int(id(light_rgb).remote_values.get_brightness() * 10) < id(current_ir_brightness);'
                then:
                  - lambda: 'id(current_ir_brightness)--;'
                  - remote_transmitter.transmit_nec:
                      address: 0xEF00
                      command: 0xFE01
                  - delay: 10ms

  - id: string_light_w
    platform: binary
    device_id: string_light
    name: ''
    icon: mdi:string-lights
    output: string_light_relay

switch:
  - id: led
    platform: gpio
    name: Status LED
    internal: true
    pin:
      number: 4

  - id: charger_relay
    platform: gpio
    name: Charger
    icon: mdi:battery-charging-wireless-outline
    pin:
      number: 0
      inverted: true
    on_turn_on:
      - light.turn_off: light_rgb

output:
  - id: dummy_pmw
    platform: template
    type: float
    write_action: []

  - id: string_light_relay
    platform: gpio
    pin:
      number: 2
      inverted: true

script:
  - id: !extend go_offline
    then:
      - switch.turn_off: charger_relay
      - light.turn_off: light_rgb
      - light.turn_off: string_light_w
