packages:
  base: !include generic/bsd33_ln882h_plug.yaml

substitutions:
  relay_restore_mode: ALWAYS_ON
  power_led: 'false'
  bl0937_current_resistor: 0.00102
  bl0937_voltage_divider: 1502.5

esphome:
  friendly_name: Bedroom Desk Plug
  area: Bedroom
  name: bedroom-desk-plug
  name_add_mac_suffix: false
