packages:
  base: !include common/base.yaml

substitutions:
  device_name: Bedroom Presence

esphome:
  name: bedroom-presence
  model: Bedroom Presence
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

uart:
  - id: ld2410_uart
    rx_pin: 13
    tx_pin: 15
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  # duration: 30
  # range: 4.5m
  # motion: 100 100 90 50 50 50 25
  # static: 100 100 15 50 20 20 20

binary_sensor:
  - platform: ld2410
    has_target:
      name: Bedroom Occupancy
      icon: ''

switch:
  - platform: ld2410
    bluetooth:
      name: Bedroom Presence LD2410 Bluetooth
      disabled_by_default: true
