packages:
  base: !include common/base.yaml
  version: !include common/esphome_2023.11.yaml

substitutions:
  device_name: Bedroom Presence

esphome:
  name: bedroom-presence
  model: Bedroom Presence
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

uart:
  - id: ld2410_uart
    rx_pin: 13
    tx_pin: 15
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
# g0: 80 100
# g1: 80 100
# g2: 35 35
# g3: 75 35
# g4: 100 45
# g5: 100 50
# g6: 100 100
# g7: 100 100
# g8: 100 100

binary_sensor:
  - platform: ld2410
    has_target:
      name: Bedroom Desk Occupancy

switch:
  - platform: ld2410
    bluetooth:
      name: Bedroom Presence LD2410 Bluetooth
      disabled_by_default: true
