packages:
  base: !include generic/midea_ac.yaml

substitutions:
  device_name: Bedroom AC
  temperature_sensor: sensor.bedroom_temperature

esphome:
  name: bedroom-ac
  model: MSAG1-09N8C2 / ESP8266
  name_add_mac_suffix: false
