packages:
  base: !include generic/hiper_iot_c1_rgb.yaml

substitutions:
  icon: mdi:lamp

esphome:
  friendly_name: Bedroom Cat Light
  area: bedroom
  name: bedroom-cat-light
  name_add_mac_suffix: false
