packages:
  base: !include generic/sonoff_dual_r3.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker.yaml

substitutions:
  relay_1_restore_mode: ALWAYS_ON
  relay_2_restore_mode: ALWAYS_ON

esphome:
  friendly_name: Comms Relay
  area:
    id: comms
    name: Comms
  name: comms-relay
  name_add_mac_suffix: false

  devices:
    - id: device_1
      name: S03 Socket
      area_id: comms

    - id: device_2
      name: Ippon Socket
      area_id: comms

    - id: presence
      name: Comms Presence
      area_id: comms

binary_sensor:
  - name: Misaka
    platform: ble_presence
    device_id: presence
    irk: !secret misaka_irk
    timeout: 30s
    device_class: presence

  - name: Layma iPhone
    platform: ble_presence
    device_id: presence
    irk: !secret layma_iphone_irk
    timeout: 30s
    device_class: presence
