packages:
  base: !include common/esp32.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker.yaml

esphome:
  friendly_name: Doorbell
  area:
    id: hallway
    name: Hallway
  name: doorbell
  model: Linptech G6LW-E
  name_add_mac_suffix: false

  devices:
    - id: hallway_presence
      name: Hallway Presence
      area_id: hallway

    - id: front_door_lock
      name: Front Door Lock
      area_id: hallway

esp32:
  board: esp32doit-devkit-v1
  framework:
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      minimum_chip_revision: '1.0'
      ignore_efuse_custom_mac: true
      ignore_efuse_mac_crc: true

external_components:
  - source: github://pauln/esphome-linp-doorbell-g04
    components:
      - linptech_g6l

  - source:
      type: git
      url: https://github.com/bazuchan/esphome-ttlock
      ref: cab83c3b4ba86b69f53c9b051976e3c78c264b90
      path: esphome-ttlock/components
    components:
      - ttlock

substitutions:
  doorbell_mode_day: Day # (0)
  doorbell_mode_night: Night # (1)

globals:
  - id: doorbell_mode
    type: int
    initial_value: '0'

  - id: front_door_lock_battery
    type: float
    restore_value: yes
    initial_value: '0'

api:
  reboot_timeout: 5min
  services:
    - service: ring
      variables:
        tune: int
        volume: int
      then:
        - remote_transmitter.transmit_szy8039b:
            tune: !lambda 'return tune;'
            volume: !lambda 'return volume;'
    - service: stop
      then:
        - remote_transmitter.transmit_szy8039b:
            command: STOP

binary_sensor:
  - id: left_button
    platform: gpio
    pin:
      number: 36
      inverted: true
    on_press:
      - script.execute: ring

  - id: right_button
    platform: gpio
    pin:
      number: 39
      inverted: true

  - name: Ringing
    platform: remote_receiver
    icon: mdi:alarm-bell
    linptech_g6l:
      address: 0x85EA01
    filters:
      delayed_off: 10s
    on_press:
      - script.execute: ring

  - name: Misaka
    platform: ble_presence
    device_id: hallway_presence
    irk: !secret misaka_irk
    timeout: 28s
    min_rssi: -88dB
    device_class: presence

  - name: Layma iPhone
    platform: ble_presence
    device_id: hallway_presence
    irk: !secret layma_iphone_irk
    timeout: 28s
    min_rssi: -88dB
    device_class: presence

  - id: front_door_lock_contact
    platform: homeassistant
    entity_id: binary_sensor.front_door_lock_contact

linptech_g6l:

output:
  - id: blue_led
    platform: gpio
    pin: 4

status_led:
  pin: 13

select:
  - id: doorbell_mode_select
    platform: template
    name: Mode
    icon: mdi:bell-cog-outline
    optimistic: true
    options:
      - ${doorbell_mode_day}
      - ${doorbell_mode_night}
    initial_option: ${doorbell_mode_day}
    on_value:
      lambda: |-
        id(doorbell_mode) = i;

sensor:
  - name: Battery
    platform: template
    device_id: front_door_lock
    state_class: measurement
    device_class: battery
    unit_of_measurement: '%'
    accuracy_decimals: 0
    lambda: |-
      return id(front_door_lock_battery);

script:
  - id: ring
    then:
      - if:
          condition:
            lambda: 'return id(doorbell_mode) == 0;'
          then:
            - remote_transmitter.transmit_szy8039b:
                tune: 3
                volume: 6

remote_receiver:
  pin: 26
  dump: linptech_g6l
  filter: 20us
  idle: 900us

remote_transmitter:
  pin: 15
  carrier_duty_percent: 100%
  non_blocking: true

lock:
  - name: ''
    platform: template
    device_id: front_door_lock
    lambda: |-
      auto state = id(lock_control).Lock::state; // TODO: временно
      if (state == LOCK_STATE_LOCKING || state == LOCK_STATE_UNLOCKING) {
        return state;
      }

      if (id(front_door_lock_contact).state) {
        return LOCK_STATE_UNLOCKED;
      } else {
        return LOCK_STATE_LOCKED;
      }
    lock_action:
      - lock.lock: lock_control
    unlock_action:
      - lock.unlock: lock_control

  - id: lock_control
    platform: ttlock
    address: ED:B1:47:D6:8F:20
    admin_ps: !secret front_door_lock_admin_ps
    unlock_key: !secret front_door_lock_unlock_key
    aes_key: !secret front_door_lock_aes_key
    polling: false

    battery_level:
      id: lock_battery_level
      on_value:
        - globals.set:
            id: front_door_lock_battery
            value: !lambda return x;
