packages:
  base: !include common/esp32.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker.yaml
  mobile_presence: !include common/mobile_presence.yaml
  restart: !include common/restart.yaml

esphome:
  friendly_name: Doorbell
  area:
    id: hallway
    name: Hallway
  name: doorbell
  model: Linptech G6LW-E
  name_add_mac_suffix: false

  devices:
    - id: mobile_presence
      name: Hallway Mobile Presence
      area_id: hallway

    - id: front_door_lock
      name: Front Door Lock
      area_id: hallway

esp32:
  board: esp32doit-devkit-v1
  framework:
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_custom_mac: true
      ignore_efuse_mac_crc: true

external_components:
  - source: github://dext0r/esphome-linp-doorbell-g04 # github://pauln/esphome-linp-doorbell-g04
    components:
      - linptech_g6l

  - source:
      type: git
      url: https://github.com/bazuchan/esphome-ttlock
      ref: b8b35231eb180aacabce773c8d64dd32961e977a
      path: esphome-ttlock/components
    components:
      - ttlock

substitutions:
  # пробивается слабый сигнал оттуда, откуда вообще не должен
  mobile_presence_min_rssi: -88dB

globals:
  - id: front_door_lock_battery
    type: float
    restore_value: yes
    initial_value: '0'

api:
  reboot_timeout: 5min
  services:
    - service: ring
      variables:
        tune: int
        volume: int
      then:
        - remote_transmitter.transmit_szy8039b:
            tune: !lambda 'return tune;'
            volume: !lambda 'return volume;'
    - service: stop
      then:
        - remote_transmitter.transmit_szy8039b:
            command: STOP

binary_sensor:
  - id: left_button
    platform: gpio
    pin:
      number: 36
      inverted: true
    on_press:
      - script.execute: ring

  - id: right_button
    platform: gpio
    pin:
      number: 39
      inverted: true

  - name: Ringing
    platform: remote_receiver
    icon: mdi:alarm-bell
    linptech_g6l:
      address: 0x85EA01
    filters:
      delayed_off: 10s
    on_press:
      - script.execute: ring

  - id: front_door_lock_contact
    platform: homeassistant
    entity_id: binary_sensor.front_door_lock_contact

linptech_g6l:

output:
  - id: blue_led
    platform: gpio
    pin: 4

status_led:
  pin: 13

sensor:
  - name: Battery
    platform: template
    device_id: front_door_lock
    state_class: measurement
    device_class: battery
    unit_of_measurement: '%'
    accuracy_decimals: 0
    lambda: |-
      return id(front_door_lock_battery);

script:
  - id: ring
    then:
      - if:
          condition:
            switch.is_off: doorbell_mute
          then:
            - remote_transmitter.transmit_szy8039b:
                tune: 3
                volume: 6

  - id: use_lock_state
    mode: restart
    then:
      - delay: 12s # иногда подключение устанавливается долго

  - id: !extend go_offline
    then:
      - switch.turn_off: doorbell_mute

switch:
  - id: doorbell_mute
    platform: template
    name: Mute
    icon: mdi:volume-off
    optimistic: true
    restore_mode: ALWAYS_OFF

remote_receiver:
  pin: 26
  dump: linptech_g6l
  filter: 20us
  idle: 900us

remote_transmitter:
  pin: 15
  carrier_duty_percent: 100%
  non_blocking: true

ble_client:
  - id: ttlock_ble_client
    mac_address: ED:B1:47:D6:8F:20
    auto_connect: false

lock:
  - name: ''
    platform: template
    device_id: front_door_lock
    lambda: |-
      auto state = id(lock_control).Lock::state; // TODO: временно
      if (state == LOCK_STATE_LOCKING || state == LOCK_STATE_UNLOCKING) {
        if (!id(use_lock_state).is_running()) {
          ESP_LOGE("lock", "run use_lock_state");
          id(use_lock_state).execute(); // lock не умеет on_state автоматизации
        }

        return state;
      }

      if (id(use_lock_state).is_running()) {
        // после закрытие статус с внешнего датчика приходит с задержкой
        // доверяем на это время статусу с замка
        return state;
      }

      if (id(front_door_lock_contact).state) {
        return LOCK_STATE_UNLOCKED;
      } else {
        return LOCK_STATE_LOCKED;
      }
    lock_action:
      - script.execute: use_lock_state
      - lock.lock: lock_control
    unlock_action:
      - script.execute: use_lock_state
      - lock.unlock: lock_control

  - id: lock_control
    platform: ttlock
    ble_client_id: ttlock_ble_client
    admin_ps: !secret front_door_lock_admin_ps
    unlock_key: !secret front_door_lock_unlock_key
    aes_key: !secret front_door_lock_aes_key

    battery_level:
      id: lock_battery_level
      on_value:
        - globals.set:
            id: front_door_lock_battery
            value: !lambda return x;
