packages:
  base: !include common/esp32.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker.yaml
  mobile_presence: !include common/mobile_presence.yaml
  wifi_e: !include common/wifi_e.yaml

esphome:
  friendly_name: Kitchen Balcony Presence
  name: kitchen-balcony-presence
  name_add_mac_suffix: false
  area:
    id: kitchen_balcony
    name: Kitchen Balcony

  devices:
    - id: mobile_presence
      name: Kitchen Balcony Mobile Presence
      area_id: kitchen_balcony

substitutions:
  mobile_presence_timeout: 35s

api:
  reboot_timeout: 10min

esp32:
  framework:
    advanced:
      minimum_chip_revision: '3.0'

switch:
  - name: LED
    platform: gpio
    pin: 2
    entity_category: diagnostic
    icon: mdi:led-outline
