packages:
  base: !include common/base.yaml

substitutions:
  device_name: Kitchen Presence

esphome:
  name: kitchen-presence
  model: Kitchen Presence
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

uart:
  - id: ld2410_uart
    rx_pin: 13
    tx_pin: 15
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  # duration: 45
  # range: 4.5m
  # motion: 90 90 90 40 40 40 100
  # static: 00 00 25 20 10 13 015

binary_sensor:
  - platform: ld2410
    has_target:
      name: Kitchen Occupancy
      icon: ''

switch:
  - platform: ld2410
    bluetooth:
      name: Kitchen Occupancy LD2410 Bluetooth
      disabled_by_default: true
