packages:
  base: !include generic/sonoff_dual_r3.yaml

substitutions:
  relay_1_restore_mode: ALWAYS_ON
  relay_2_restore_mode: ALWAYS_ON

esphome:
  friendly_name: Kitchen Overhead Relay
  area:
    id: kitchen
    name: Kitchen
  name: kitchen-overhead-relay
  name_add_mac_suffix: false

  devices:
    - id: device_1
      name: Kitchen Ovens Socket
      area_id: kitchen

    - id: device_2
      name: Kitchen Camera Socket
      area_id: kitchen
