packages:
  base: !include common/base.yaml

substitutions:
  device_name: Kitchen Worktop Light

esphome:
  name: kitchen-worktop-light
  model: H801 LED Dimmer
  name_add_mac_suffix: false
  on_boot:
    - switch.turn_off: led_green

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: !secret ssid_kitchen

light:
  - id: light_w1
    platform: monochromatic
    name: $device_name Right
    output: pwm_w1
    default_transition_length: 700ms

  - id: light_w2
    platform: monochromatic
    name: $device_name Left
    output: pwm_w2
    default_transition_length: 700ms

output:
  - id: pwm_b
    platform: esp8266_pwm
    pin: 12

  - id: pwm_g
    platform: esp8266_pwm
    pin: 13

  - id: pwm_r
    platform: esp8266_pwm
    pin: 15

  - id: pwm_w1
    platform: esp8266_pwm
    pin: 14

  - id: pwm_w2
    platform: esp8266_pwm
    pin: 04

switch:
  - id: led_green
    platform: gpio
    internal: true
    pin:
      number: 1
      inverted: true

status_led:
  pin:
    number: 5
    inverted: true
