packages:
  base: !include common/esp32.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker.yaml

esphome:
  friendly_name: Kitchen Balcony Tracker
  area: Kitchen
  name: kitchen-balcony-tracker
  name_add_mac_suffix: false

binary_sensor:
  - name: Misaka Kitchen Balcony Presence
    platform: ble_presence
    irk: !secret misaka_irk
    timeout: 30s
    device_class: presence

  - name: Layma iPhone Kitchen Balcony Presence
    platform: ble_presence
    irk: !secret layma_iphone_irk
    timeout: 30s
    device_class: presence

switch:
  - name: LED
    platform: gpio
    pin: 2
    entity_category: diagnostic
    icon: mdi:led-outline
