packages:
  base: !include common/base.yaml
  time: !include common/time.yaml
  tion_4s: !include common/tion_4s.yaml
  senseair_s8: !include common/senseair_s8.yaml
  mithermometer_ble: !include common/mithermometer_ble.yaml
  esp_idf: !include common/idf.yaml
  # debug: !include common/ld2410_debug.yaml

substitutions:
  device_name: Living Room UBox
  tion_mac_address: F2:71:3F:8E:FC:38
  tion_device_name: Living Room Intake Fan
  senseair_s8_sensor_name: Living Room CO2
  senseair_s8_tx_pin: '1'
  senseair_s8_rx_pin: '3'

esphome:
  name: living-room-ubox
  model: Universal Box (ESP32)
  name_add_mac_suffix: false

esp32:
  board: esp32dev

logger:
  baud_rate: 0
  level: INFO

uart:
  - id: ld2410_uart
    rx_pin: 17
    tx_pin: 16
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

remote_transmitter:
  id: transmitter
  pin: 25
  carrier_duty_percent: 50%

# remote_receiver:
#   pin:
#     number: 33
#     inverted: true
#   dump: all

ld2410:
  uart_id: ld2410_uart
  # timeout: 90
  # max gate: 6
  # g0: 100 100
  # g1: 100 100
  # g2: 45 30
  # g3: 100 9
  # g4: 100 9
  # g5: 100 25
  # g6: 100 100
  # g7: 100 100
  # g8: 100 100

binary_sensor:
  - platform: ld2410
    has_target:
      name: Living Room Occupancy
      icon: ''

button:
  - platform: template
    name: TV Toggle Power
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xBF00
          command: 0xF20D

  - platform: template
    name: AV Receiver Dimmer High
    on_press:
      - script.execute: av_receiver_func_menu
      - script.wait: av_receiver_func_menu
      - remote_transmitter.transmit_nec: # up
          address: 0x857A
          command: 0x629D
      - delay: 100ms
      - remote_transmitter.transmit_nec: # enter
          address: 0x857A
          command: 0x21DE
      - delay: 100ms
      - remote_transmitter.transmit_nec: # left
          address: 0x857A
          command: 0x609F
          repeat:
            times: 4
            wait_time: 100ms
      - delay: 100ms
      - remote_transmitter.transmit_nec: # right
          address: 0x857A
          command: 0x619E
          repeat:
            times: 2
            wait_time: 100ms
      - delay: 3s
      - remote_transmitter.transmit_nec: # setup
          address: 0x857A
          command: 0x7B84

  - platform: template
    name: AV Receiver Dimmer Low
    on_press:
      - script.execute: av_receiver_func_menu
      - script.wait: av_receiver_func_menu
      - remote_transmitter.transmit_nec: # up
          address: 0x857A
          command: 0x629D
      - delay: 100ms
      - remote_transmitter.transmit_nec: # enter
          address: 0x857A
          command: 0x21DE
      - delay: 100ms
      - remote_transmitter.transmit_nec: # left
          address: 0x857A
          command: 0x609F
          repeat:
            times: 4
            wait_time: 100ms
      - delay: 3s
      - remote_transmitter.transmit_nec: # setup
          address: 0x857A
          command: 0x7B84

number:
  - id: av_receiver_volume_up
    platform: template
    name: AV Receiver Volume Up
    min_value: 0
    max_value: 40
    step: 1
    icon: mdi:volume-plus
    set_action:
      - lambda: |-
          remote_base::NECAction<> *ir_action;
          ir_action = new remote_base::NECAction<>();
          ir_action->set_parent(id(transmitter));
          ir_action->set_send_times(int(x) * 2);
          ir_action->set_send_wait(30000);
          ir_action->set_address(0x857A);
          ir_action->set_command(0xE51A);
          ir_action->play();

          id(av_receiver_volume_up).publish_state(0);

  - id: av_receiver_volume_down
    platform: template
    name: AV Receiver Volume Down
    min_value: 0
    max_value: 40
    step: 1
    icon: mdi:volume-minus
    set_action:
      - lambda: |-
          remote_base::NECAction<> *ir_action;
          ir_action = new remote_base::NECAction<>();
          ir_action->set_parent(id(transmitter));
          ir_action->set_send_times(int(x) * 2);
          ir_action->set_send_wait(30000);
          ir_action->set_address(0x857A);
          ir_action->set_command(0xE41B);
          ir_action->play();

          id(av_receiver_volume_down).publish_state(0);

light:
  - name: Living Room TV Status Light Left
    platform: partition
    segments:
      - id: status_led_strip
        from: 4
        to: 7
    gamma_correct: 1

  - name: Living Room TV Status Light Right
    platform: partition
    segments:
      - id: status_led_strip
        from: 0
        to: 3
    gamma_correct: 1

  - id: status_led_strip
    platform: esp32_rmt_led_strip
    chipset: ws2812
    pin: 32
    num_leds: 8
    rmt_channel: 2
    rgb_order: GRB

sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:42:B7:5D
    temperature:
      name: Living Room Temperature
      accuracy_decimals: 1
    humidity:
      name: Living Room Humidity
      accuracy_decimals: 0
    battery_level:
      name: Living Room Meteo Battery

  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:B2:CD:CC
    temperature:
      name: Server Room Temperature
      accuracy_decimals: 1
    humidity:
      name: Server Room Humidity
      accuracy_decimals: 0
    battery_level:
      name: Server Room Meteo Battery

switch:
  - platform: ld2410
    bluetooth:
      name: Living Room LD2410 Bluetooth
      disabled_by_default: true

script:
  - id: av_receiver_func_menu
    then:
      - remote_transmitter.transmit_nec: # return
          address: 0x857A
          command: 0x55AA
          repeat:
            times: 3
      - delay: 100ms
      - remote_transmitter.transmit_nec: # setup
          address: 0x857A
          command: 0x7B84
      - delay: 100ms
      - remote_transmitter.transmit_nec: # up
          address: 0x857A
          command: 0x629D
          repeat:
            times: 3
            wait_time: 100ms
      - delay: 100ms
      - remote_transmitter.transmit_nec: # enter
          address: 0x857A
          command: 0x21DE
      - delay: 100ms
