packages:
  base: !include common/esp8266.yaml
  bl0937: !include common/bl0937.yaml

substitutions:
  bl0937_sel_pin: 13
  bl0937_sel_pin_inverted: 'true'
  bl0937_cf_pin: 12
  bl0937_cf1_pin: 14
  bl0937_current_resistor: 0.00094
  bl0937_voltage_divider: 1757.7

esphome:
  friendly_name: Living Room Media Socket
  area: Living Room
  name: living-room-media-socket
  model: Lellki WK34
  name_add_mac_suffix: false

esp8266:
  board: esp8285

logger:
  baud_rate: 0

binary_sensor:
  - id: push_button
    platform: gpio
    pin: 3

status_led:
  pin:
    number: 4
    inverted: true

switch:
  - id: relay
    platform: gpio
    pin: 5
    name: ''
    device_class: outlet
    restore_mode: ALWAYS_ON
