packages:
  base: !include generic/athom_wall_outlet.yaml

substitutions:
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  friendly_name: Living Room Heater Socket
  area: Living Room
  name: living-room-heater-socket
  name_add_mac_suffix: false
