packages:
  base: !include common/base.yaml

substitutions:
  device_name: Living Room PM25

esphome:
  name: living-room-pm25
  model: IKEA E2014 Vindriktning / ESP8266
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

uart:
  rx_pin: D4
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: Living Room PM 2.5
      filters:
        - throttle: 3s
