packages:
  base: !include common/base.yaml
  time: !include common/time.yaml
  tion_4s: !include common/tion_4s.yaml
  senseair_s8: !include common/senseair_s8.yaml
  mithermometer_ble: !include common/mithermometer_ble.yaml
  esp_idf: !include common/idf.yaml
  # debug: !include common/ld2410_debug.yaml

substitutions:
  device_name: Living Room UBox
  tion_mac_address: F2:71:3F:8E:FC:38
  tion_device_name: Living Room Intake Fan
  senseair_s8_sensor_name: Living Room CO2
  senseair_s8_tx_pin: '1'
  senseair_s8_rx_pin: '3'

esphome:
  name: living-room-ubox
  model: Universal Box (ESP32)
  name_add_mac_suffix: false

esp32:
  board: esp32dev

logger:
  baud_rate: 0
  level: INFO

uart:
  - id: ld2410_uart
    rx_pin: 17
    tx_pin: 16
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  # timeout: 90
  # max gate: 6
  # g0: 100 100
  # g1: 100 100
  # g2: 45 30
  # g3: 30 9
  # g4: 17 9
  # g5: 17 25
  # g6: 100 100
  # g7: 100 100
  # g8: 100 100

binary_sensor:
  - platform: ld2410
    has_target:
      name: Living Room Occupancy
      device_class: occupancy

sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:42:B7:5D
    temperature:
      name: Living Room Temperature
      accuracy_decimals: 1
    humidity:
      name: Living Room Humidity
      accuracy_decimals: 0
    battery_level:
      name: Living Room Meteo Battery

  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:B2:CD:CC
    temperature:
      name: Server Room Temperature
      accuracy_decimals: 1
    humidity:
      name: Server Room Humidity
      accuracy_decimals: 0
    battery_level:
      name: Server Room Meteo Battery

switch:
  - platform: ld2410
    bluetooth:
      name: Living Room LD2410 Bluetooth
      disabled_by_default: true
