packages:
  base: !include generic/bsd34_mk_plug.yaml

substitutions:
  relay_restore_mode: RESTORE_DEFAULT_ON
  power_led: 'false'
  bl0937_current_resistor: 0.001018
  bl0937_voltage_divider: 1536.5

esphome:
  friendly_name: Living Room Intake Fan Plug
  area: Living Room
  name: living-room-intake-fan-plug
  name_add_mac_suffix: false
