packages:
  base: !include common/esp8266.yaml

esphome:
  friendly_name: Living Room TV Light
  area: Living Room
  name: living-room-tv-light
  model: MagicHome LED Dimmer
  name_add_mac_suffix: false

light:
  - id: light_w
    platform: monochromatic
    name: ''
    icon: mdi:television-ambient-light
    output: pwm
    default_transition_length: 2s
    gamma_correct: 1.7

output:
  - id: pwm
    platform: esp8266_pwm
    pin: 12
