packages:
  base: !include common/esp32.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker.yaml
  tion_4s: !include common/tion_4s.yaml
  senseair_s8: !include common/senseair_s8.yaml
  restart: !include common/restart.yaml

substitutions:
  tion_device_id: intake_fan
  tion_mac_address: F2:71:3F:8E:FC:38
  senseair_s8_device_id: living_room_meteo
  senseair_s8_tx_pin: '1'
  senseair_s8_rx_pin: '3'

esphome:
  friendly_name: Living Room UBox
  area:
    id: living_room
    name: Living Room
  name: living-room-ubox
  model: Universal Box (ESP32)
  name_add_mac_suffix: false

  areas:
    - id: comms
      name: Comms

  devices:
    - id: intake_fan
      name: Living Room Intake Fan
      area_id: living_room

    - id: living_room_meteo
      name: Living Room Meteo
      area_id: living_room

    - id: comms_meteo
      name: Comms Meteo
      area_id: comms

    - id: tv_status_light
      name: Living Room TV Status Light
      area_id: living_room

    - id: presence
      name: Living Room Presence
      area_id: living_room

esp32:
  framework:
    advanced:
      minimum_chip_revision: '1.0'

logger:
  baud_rate: 0

uart:
  - id: ld2410_uart
    rx_pin: 17
    tx_pin: 16
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

  - id: pmsx003_uart
    tx_pin: 26
    rx_pin: 27
    baud_rate: 9600

ld2410:
  uart_id: ld2410_uart
  # duration: 45
  # range: 4.5m
  # motion: 100 100 90 100 100 100 100
  # static: 100 100 30 010 010 025 100

binary_sensor:
  - platform: ld2410
    has_target:
      name: Occupancy
      device_id: presence
      icon: ''

  - name: Misaka
    platform: ble_presence
    device_id: presence
    irk: !secret misaka_irk
    timeout: 30s
    device_class: presence

  - name: Layma iPhone
    platform: ble_presence
    device_id: presence
    irk: !secret layma_iphone_irk
    timeout: 30s
    device_class: presence

light:
  - name: Left
    platform: partition
    device_id: tv_status_light
    segments:
      - id: status_led_strip
        from: 0
        to: 3
    gamma_correct: 1

  - name: Right
    platform: partition
    device_id: tv_status_light
    segments:
      - id: status_led_strip
        from: 4
        to: 7
    gamma_correct: 1

  - id: status_led_strip
    platform: esp32_rmt_led_strip
    chipset: ws2812
    pin: 32
    num_leds: 8
    rgb_order: GRB

sensor:
  - platform: pmsx003
    type: PMSX003
    uart_id: pmsx003_uart
    update_interval: 3min
    pm_1_0:
      name: PM 1.0
      device_id: living_room_meteo
    pm_2_5:
      name: PM 2.5
      device_id: living_room_meteo
    pm_10_0:
      name: PM 10.0
      device_id: living_room_meteo

  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:42:B7:5D
    temperature: &temperature
      name: Temperature
      device_id: living_room_meteo
      accuracy_decimals: 1
      filters:
        - round: 1
        - or:
          - throttle: 30min
          - delta: 0.2
        - timeout: 35min

    humidity: &humidity
      name: Humidity
      device_id: living_room_meteo
      accuracy_decimals: 0
      filters:
        - round: 0
        - or:
          - throttle: 30min
          - delta: 2
        - timeout: 35min

    battery_level: &battery_level
      name: Battery
      device_id: living_room_meteo
      filters:
        - delta: 5

  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:B2:CD:CC
    temperature:
      device_id: comms_meteo
      <<: *temperature
    humidity:
      device_id: comms_meteo
      <<: *humidity
    battery_level:
      device_id: comms_meteo
      <<: *battery_level

switch:
  - platform: ld2410
    bluetooth:
      name: LD2410 Bluetooth
      device_id: presence
      disabled_by_default: true
