packages:
  base: !include generic/athom_wall_outlet.yaml

substitutions:
  device_name: Living Room Heater Socket
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: living-room-heater-socket
  name_add_mac_suffix: false
