packages:
  base: !include generic/sonoff_basic_r3.yaml
  version: !include common/esphome_2023.7.yaml

substitutions:
  device_name: Living Room Heater

esphome:
  name: living-room-heater
  name_add_mac_suffix: false
