packages:
  base: !include common/esp32.yaml
  restart: !include common/restart.yaml

substitutions:
  intercom_mode_passthrough: Passthrough  # (0) переключено на трубку
  intercom_mode_always_reject: Always reject # (1)
  intercom_mode_always_accept: Always accept # (2)
  intercom_mode_delivery: Delivery # (3)
  intercom_mode_guests: Guests # (4)

  intercom_status_incoming_call: Incoming call
  intercom_status_door_opened: Door opened
  intercom_status_call_rejected: Call rejected
  intercom_status_standby: Standby

  delay_call_end_detect: 3000ms
  delay_before_voice: 1000ms
  delay_before_open_door: 1000ms
  delay_open_on_time: 600ms
  delay_after_close_door: 1000ms

esphome:
  friendly_name: Nelma5
  area:
    id: service
    name: Service
  name: nelma5
  model: Nelma5 / SmartIntercom / ESP32
  name_add_mac_suffix: false
  libraries:
    # Форк https://github.com/earlephilhower/ESP8266Audio#2.4.1
    # Удалена часть файлов для минимизации зависимостей и ускорения сборки:
    # AudioOutputSPIFFSWAV.cpp AudioFileSourceSPIFFS.h AudioFileSourceFS.cpp
    # AudioFileSourceICYStream.cpp AudioFileSourceHTTPStream.cpp AudioFileSourceHTTPStream.h
    # AudioFileSourceICYStream.h AudioFileSourceSD.cpp AudioFileSourceSD.h
    - ESP8266Audio=file://../../../lib/ESP8266Audio

  on_boot:
    priority: -100
    then:
      - select.set:
          id: intercom_mode_select
          option: intercom_mode_passthrough

  areas:
    - id: porch
      name: Porch

  devices:
    - id: intercom
      name: Intercom
      area_id: service

    - id: power_meter
      name: Branch Circuit Meter
      area_id: service

    - id: porch_path_light
      name: Porch Path Light
      area_id: porch

    - id: porch_lock_light
      name: Porch Lock Light
      area_id: porch

esp32:
  framework:
    type: arduino # для ESP8266Audio

uart:
  rx_pin: 9
  tx_pin: 10
  baud_rate: 9600

audio:
  id: player

file:
  - id: delivery_mp3
    file: lib/intercom/delivery.mp3
  - id: guests_mp3
    file: lib/intercom/guests.mp3
  - id: reject_mp3
    file: lib/intercom/reject.mp3

modbus:

globals:
  - id: intercom_mode
    type: int
    initial_value: '0'

  - id: intercom_oncall
    type: bool
    initial_value: 'false'

light:
  - id: red_led
    platform: status_led
    pin:
      number: 16
      inverted: false

  - id: green_led
    platform: monochromatic
    output: green_led_output
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - pulse:
          name: pulse
          update_interval: 2s

      - strobe:
          name: blink
          colors:
            - state: true
              duration: 100ms
            - state: false
              duration: 1900ms

      - strobe:
          name: calling
          colors:
            - state: true
              duration: 50ms
            - state: false
              duration: 50ms

  - name: ''
    platform: partition
    device_id: porch_lock_light
    segments:
      - id: led
        from: 0
        to: 0
    gamma_correct: 1
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: pulse
          update_interval: 1s
          transition_length: 1s

  - name: ''
    platform: partition
    device_id: porch_path_light
    segments:
      - id: led
        from: 1
        to: 22
    gamma_correct: 1
    restore_mode: ALWAYS_OFF

  - id: led
    platform: esp32_rmt_led_strip
    chipset: SK6812
    pin: 27
    num_leds: 23
    rgb_order: GRB
    is_rgbw: true

select:
  - id: intercom_mode_select
    name: Mode
    platform: template
    device_id: intercom
    icon: 'mdi:deskphone'
    optimistic: true
    options:
      - ${intercom_mode_passthrough}
      - ${intercom_mode_always_accept}
      - ${intercom_mode_always_reject}
      - ${intercom_mode_delivery}
      - ${intercom_mode_guests}
    initial_option: ${intercom_mode_passthrough}
    on_value:
      lambda: |-
        id(intercom_mode) = i;
        if (i == 0) {
            id(intercom_mode_passthrough).execute();
        } else {
            id(intercom_mode_intercept).execute();
        }

script:
  - id: intercom_mode_passthrough
    then:
      - logger.log:
          format: 'Intercom: Passthrough mode'
          level: INFO
      - output.turn_off: intercept_line
      - output.turn_on: phone_hanging
      - output.turn_off: open_door

  - id: intercom_mode_intercept
    then:
      - logger.log:
          format: 'Intercom: Intercept mode'
          level: INFO
      - output.turn_on: intercept_line
      - output.turn_on: phone_hanging
      - output.turn_off: open_door

  - id: intercom_open_door
    then:
      - logger.log:
          format: 'Intercom: Open door'
          level: INFO

      - lambda: 'id(intercom_status).publish_state("${intercom_status_door_opened}");'
      - output.turn_off: phone_hanging
      - if:
          condition:
            lambda: 'return id(intercom_mode) == 3 || id(intercom_mode) == 4;'
          then:
            - delay: $delay_before_voice
            - lambda: |-
                switch (id(intercom_mode)) {
                  case 3:
                    id(player).play_mp3_data(id(delivery_mp3), sizeof(id(delivery_mp3)));
                    break;
                  case 4:
                    id(player).play_mp3_data(id(guests_mp3), sizeof(id(guests_mp3)));
                    break;
                }
            - wait_until:
                lambda: |-
                  return !id(player).is_playing();
          else:
            - delay: $delay_before_open_door
      - output.turn_on: open_door
      - delay: $delay_open_on_time
      - output.turn_off: open_door
      - delay: $delay_after_close_door
      - output.turn_on: phone_hanging

  - id: intercom_reject_call
    then:
      - logger.log:
          format: 'Intercom: Reject call'
          level: INFO

      - lambda: 'id(intercom_status).publish_state("${intercom_status_call_rejected}");'
      - output.turn_off: phone_hanging
      - delay: $delay_before_voice
      - lambda: |-
          id(player).play_mp3_data(id(reject_mp3), sizeof(id(reject_mp3)));
      - wait_until:
          lambda: |-
            return !id(player).is_playing();
      - output.turn_on: phone_hanging

sensor:
  # Розетки: Кухня
  - id: pzem5
    platform: pzemac
    address: 5
    update_interval: never

    power: &pzem_power_raw
      id: pzem5_power_raw
      filters:
        - clamp: # при старте может быть всплеск мощности
            min_value: 0
            max_value: 10000
            ignore_out_of_range: true
      on_value:
        - sensor.template.publish:
            id: pzem5_power_avg
            state: !lambda return x;

    energy: &pzem_energy
      name: Kitchen Energy
      device_id: power_meter
      accuracy_decimals: 2
      filters:
        - throttle: 2.5min

  - &pzem_power_avg
    id: pzem5_power_avg
    name: Kitchen Power
    platform: template
    device_id: power_meter
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    accuracy_decimals: 0
    filters:
      - throttle_average: 5s
      - round: 0
      - timeout: 15s

  # Розетки: Ванная / Климат Спальня-Мастерская
  - id: pzem6
    platform: pzemac
    address: 6
    update_interval: never

    power:
      id: pzem6_raw_power
      on_value:
        - sensor.template.publish:
            id: pzem6_power_avg
            state: !lambda return x;
      <<: *pzem_power_raw

    energy:
      name: CB Energy
      <<: *pzem_energy

  - <<: *pzem_power_avg
    id: pzem6_power_avg
    name: CB Power

  # Розетки: Комнаты
  - id: pzem7
    platform: pzemac
    address: 7
    update_interval: never

    power:
      id: pzem7_raw_power
      on_value:
        - sensor.template.publish:
            id: pzem7_power_avg
            state: !lambda return x;
      <<: *pzem_power_raw

    energy:
      name: Sockets Energy
      <<: *pzem_energy

  - <<: *pzem_power_avg
    id: pzem7_power_avg
    name: Sockets Power

interval:
  - interval: 1s
    then:
      - delay: 150ms
      - component.update: pzem5
      - delay: 150ms
      - component.update: pzem6
      - delay: 150ms
      - component.update: pzem7

binary_sensor:
  - id: intercom_ring
    platform: gpio
    pin:
      number: 12
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: ${delay_call_end_detect}
    on_press:
      - if:
          condition:
            lambda: 'return !id(intercom_oncall);'
          then:
            - lambda: 'id(intercom_oncall) = true;'
            - logger.log:
                format: 'Intercom: Incoming call'
                level: INFO
            - lambda: 'id(intercom_status).publish_state("${intercom_status_incoming_call}");'
            - lambda: |
                switch (id(intercom_mode)) {
                  case 1:
                  case 3:
                  case 4:
                    id(intercom_open_door).execute();
                    break;
                  case 2:
                    id(intercom_reject_call).execute();
                    break;
                }
    on_release:
      - lambda: 'id(intercom_oncall) = false;'
      - logger.log:
          format: 'Intercom: Incoming call completed'
          level: INFO
      - lambda: 'id(intercom_status).publish_state("${intercom_status_standby}");'

text_sensor:
  - id: intercom_status
    name: Status
    platform: template
    device_id: intercom
    icon: 'mdi:bell'
    lambda: |-
      return {"${intercom_status_standby}"};

output:
  - id: green_led_output
    platform: ledc
    pin: 13

  # переключатель плата/трубка (off - на трубку, on - на плату)
  - id: intercept_line
    platform: gpio
    pin: 14

  - id: open_door
    platform: gpio
    pin: 17

  # поднятие трубки (on - положена, off - поднята)
  - id: phone_hanging
    platform: gpio
    pin: 4
