[tool.poetry]
name = "hotaru-esphome"
package-mode = false

[tool.poetry.dependencies]
python = "~3.13"
esphome = "2024.11.1"
poethepoet = "0.30"

[tool.poe.tasks]
patch = "bash -c 'patch -d $(poetry env info -p)/lib/python*/site-packages -p 1 < patches/device-model-202411.patch'"
