[tool.poetry]
name = "hotaru-esphome"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
esphome = "2023.11.6"
poethepoet = "<0.28"

[tool.poe.tasks]
patch = "bash -c 'patch -d $(poetry env info -p)/lib/python*/site-packages -p 1 < patches/device-model-202302.patch'"
