packages:
  base: !include generic/t34_plug.yaml

substitutions:
  relay_restore_mode: ALWAYS_ON

esphome:
  friendly_name: Vacuum Charger
  area: Closet
  name: vacuum-charger
  name_add_mac_suffix: false
