packages:
  base: !include generic/t34_plug.yaml

substitutions:
  relay_restore_mode: ALWAYS_ON
  bl0937_current_resistor: 0.00106
  bl0937_voltage_divider: 800.9

esphome:
  friendly_name: Vacuum Charger
  area: Closet
  name: vacuum-charger
  name_add_mac_suffix: false
