packages:
  base: !include generic/cbe_socket.yaml
  wifi_signal: !include common/wifi_signal.yaml
  uptime: !include common/uptime.yaml

substitutions:
  device_name: Washing Machine Socket

esphome:
  name: washing-machine-socket-11
  name_add_mac_suffix: false

logger:
  level: INFO
