packages:
  base: !include generic/midea_ac.yaml
  energy: !include common/energy.yaml

substitutions:
  temperature_sensor: sensor.workshop_temperature

esphome:
  friendly_name: Workshop AC
  area: Workshop
  name: workshop-ac
  model: MSAG1-09N8C2 / ESP8266
  name_add_mac_suffix: false

binary_sensor:
  - id: bedroom_ac_running
    platform: homeassistant
    entity_id: binary_sensor.bedroom_ac_running

sensor:
  - id: circuit_power
    platform: homeassistant
    entity_id: sensor.cb_branch_circuit_power_for_ac

  - id: power_raw
    platform: template
    update_interval: 1s
    unit_of_measurement: W
    lambda: |-
      auto power = 2.0; // мощность в standby

      if (id(ac).mode == CLIMATE_MODE_OFF) {
        return power;
      }

      // Сломается в 2026.3+
      if (!global_api_server->is_connected(true)) {
        ESP_LOGW("power_meter", "No API connection with power state");
        return power;
      }

      if (id(bedroom_ac_running).state) {
        power += id(circuit_power).state / 2;
      } else {
        power += id(circuit_power).state;
      }

      return power;
    on_value:
      - lambda: |-
          id(power_avg).publish_state(x);
          id(power_adj).publish_state(x);
