packages:
  base: !include common/base.yaml
  time: !include common/time.yaml
  uptime: !include common/uptime.yaml
  tion_4s: !include common/tion_4s.yaml
  senseair_s8: !include common/senseair_s8.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker.yaml
  restart: !include common/restart.yaml
  esp_idf: !include common/idf.yaml

substitutions:
  device_name: Workshop UBox
  tion_mac_address: E1:73:74:77:82:1C
  tion_device_name: Workshop Intake Fan
  senseair_s8_sensor_name: Workshop CO2
  senseair_s8_tx_pin: '17'
  senseair_s8_rx_pin: '16'

esphome:
  name: workshop-ubox
  model: Universal Box (ESP32)
  name_add_mac_suffix: false

esp32:
  board: esp32dev

uart:
  - id: pm1006_uart
    rx_pin: 34
    baud_rate: 9600

sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:7D:60:67
    temperature:
      name: Workshop Temperature
      accuracy_decimals: 1
    humidity:
      name: Workshop Humidity
      accuracy_decimals: 0
    battery_level:
      name: Workshop Meteo Battery

  - platform: pm1006
    uart_id: pm1006_uart
    pm_2_5:
      name: Workshop PM 2.5
      filters:
        - throttle: 20s
