packages:
  base: !include generic/ms_105_dimmer.yaml

substitutions:
  device_name: Xmas Elka

esphome:
  name: xmas-elka
  name_add_mac_suffix: false

script:
  - id: !extend go_offline
    then:
      - light.turn_off: light_w
