automation:
  - id: front_door_lock_anyone_home
    alias: 'Front Door: Lock (anyone home)'
    mode: restart
    description: Закрытие входной двери когда её недавно закрыли и остались дома
    triggers:
      - trigger: door.closed
        target:
          entity_id: binary_sensor.front_door
        options:
          for:
            minutes: 2
    conditions:
      - condition: state
        entity_id: input_boolean.lock_control
        state: 'on'

      - condition: timer.is_idle
        target:
          entity_id: timer.come_back_soon

      - condition: lock.is_unlocked
        target:
          entity_id: lock.front_door

      - condition: door.is_closed
        target:
          entity_id: binary_sensor.front_door

      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'
    actions:
      - if:
          - condition: motion.is_detected
            target:
              area_id: porch
        then:
          - wait_for_trigger:
              - trigger: motion.cleared
                target:
                  area_id: porch
            timeout:
              minutes: 5
            continue_on_timeout: true

      - if:
          - condition: lock.is_unlocked
            target:
              entity_id: lock.front_door
        then:
          - action: lock.lock
            target:
              entity_id: lock.front_door

  - id: front_door_lock_no_one_comes_back
    alias: 'Front Door: Lock (no one comes back)'
    mode: restart
    description: Закрытие входной двери когда сказали "скоро вернусь" и не вернулись
    triggers:
      - trigger: timer.finished
        target:
          entity_id: timer.come_back_soon
    conditions:
      - condition: state
        entity_id: input_boolean.lock_control
        state: 'on'

      - condition: lock.is_unlocked
        target:
          entity_id: lock.front_door

      - condition: door.is_closed
        target:
          entity_id: binary_sensor.front_door
    actions:
      - action: lock.lock
        target:
          entity_id: lock.front_door

  - id: front_door_lock_bedtime
    alias: 'Front Door: Lock (Bedtime/Night)'
    mode: restart
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        to:
          - Bedtime
          - Night
    conditions:
      - condition: state
        entity_id: input_boolean.lock_control
        state: 'on'

      - condition: lock.is_unlocked
        target:
          entity_id: lock.front_door

      - condition: door.is_closed
        target:
          entity_id: binary_sensor.front_door
    actions:
      - action: lock.lock
        target:
          entity_id: lock.front_door

  - id: front_door_unlock
    alias: 'Front Door: Unlock'
    mode: restart
    triggers:
      - trigger: timer.started
        target:
          entity_id: timer.come_back_soon

      - trigger: state
        entity_id: input_button.entrance_panel_leaving_home
    conditions:
      - condition: state
        entity_id: input_boolean.lock_control
        state: 'on'

      - condition: lock.is_locked
        target:
          entity_id: lock.front_door
    actions:
      - action: lock.unlock
        target:
          entity_id: lock.front_door

  - id: front_door_auto_lock
    alias: 'Front Door: Auto lock'
    description: Закрытие замка входной двери при взведённом флаге автозакрытия
    max_exceeded: silent
    triggers:
      - trigger: door.closed
        target:
          entity_id: binary_sensor.front_door
        options:
          for:
            seconds: 2
    conditions:
      - condition: timer.is_active
        target:
          entity_id: timer.front_door_auto_lock

      - condition: lock.is_unlocked
        target:
          entity_id: lock.front_door
    actions:
      - action: lock.lock
        target:
          entity_id: lock.front_door

  - id: front_door_relock
    alias: 'Front Door: Relock'
    description: Закрытие замка входной двери при неудавшемся автооткрытии (никто не пришёл)
    triggers:
      - trigger: timer.finished
        target:
          entity_id: timer.front_door_auto_unlock
    conditions:
      - condition: lock.is_unlocked
        target:
          entity_id: lock.front_door

      - condition: door.is_closed
        target:
          entity_id: binary_sensor.front_door
    actions:
      - action: lock.lock
        target:
          entity_id: lock.front_door

  - id: front_door_auto_unlock
    alias: 'Front Door: Auto Unlock'
    triggers:
      - trigger: timer.started
        target:
          entity_id: timer.front_door_auto_unlock
    conditions:
      - condition: lock.is_locked
        target:
          entity_id: lock.front_door
    actions:
      - action: lock.unlock
        target:
          entity_id: lock.front_door

  - id: front_door_auto_lock_start_timer
    alias: 'Front Door Auto Lock: Start timer'
    triggers:
      - id: waking_up
        trigger: switch.turned_off
        target:
          entity_id: input_boolean.waking_up

      - trigger: state
        entity_id: input_button.entrance_panel_leaving_home
    conditions:
      - condition: state
        entity_id: input_boolean.lock_control
        state: 'on'

      - or:
          - not:
              - condition: trigger
                id: waking_up

          - and:
              - condition: trigger
                id: waking_up

              - condition: door.is_open
                note: Открытие двери -> Завершение waking_up
                target:
                  entity_id: binary_sensor.front_door
    actions:
      - action: timer.start
        entity_id: timer.front_door_auto_lock

  - id: front_door_auto_lock_cancel_timer
    alias: 'Front Door Auto Lock: Cancel timer'
    triggers:
      - trigger: lock.locked
        target:
          entity_id: lock.front_door

      - trigger: state
        entity_id: input_boolean.lock_control
        to: 'off'
    conditions:
      - condition: timer.is_active
        target:
          entity_id: timer.front_door_auto_lock
    actions:
      - action: timer.cancel
        target:
          entity_id: timer.front_door_auto_lock

  - id: front_door_auto_unlock_start_timer
    alias: 'Front Door Auto Unlock: Start timer'
    triggers:
      - trigger: state
        entity_id: sensor.intercom_status
        to: Door opened
    conditions:
      - condition: state
        entity_id: input_boolean.lock_control
        state: 'on'

      - condition: timer.is_idle
        note: Если флаг автозакрытия стоит - к нам идут навстречу из квартиры
        target:
          entity_id: timer.front_door_auto_lock

      - or:
          - condition: state
            entity_id:
              - binary_sensor.anyone_near_home
              - input_boolean.waiting_guests
            state: 'on'
            match: any
    actions:
      - action: timer.start
        entity_id: timer.front_door_auto_unlock

  - id: front_door_auto_unlock_cancel_timer
    alias: 'Front Door Auto Unlock: Cancel timer'
    triggers:
      - trigger: door.closed
        target:
          entity_id: binary_sensor.front_door

      - trigger: timer.started
        target:
          entity_id: timer.front_door_auto_lock

      - trigger: state
        entity_id: input_boolean.lock_control
        to: 'off'
    conditions:
      - condition: timer.is_active
        target:
          entity_id: timer.front_door_auto_unlock
    actions:
      - action: timer.cancel
        target:
          entity_id: timer.front_door_auto_unlock

template:
  - lock:
      - unique_id: lock.front_door_vacation
        default_entity_id: lock.front_door_vacation
        name: Front Door Vacation
        state: >
          {{ is_state('binary_sensor.front_door_vacation_lock_contact', 'off') }}
        availability: >
          {{ states('binary_sensor.front_door_vacation_lock_contact') in ['on', 'off'] }}
        lock:
          action: none.none
        unlock:
          action: none.none

timer:
  front_door_auto_unlock:
    name: 'Front Door: Auto Unlock'
    icon: mdi:lock-clock
    duration:
      minutes: 7

  front_door_auto_lock:
    name: 'Front Door: Auto Lock'
    icon: mdi:lock-open-check-outline
    duration:
      minutes: 2
