automation:
  - id: home_mode_manual_day
    alias: 'Home Mode: Manual day'
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Сейчас день
    action:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
        then:
          - service: script.yandex_station_tts
            data:
              target: >
                {{ trigger.event.data.get('entity_id', 'last') }}
              text: Действительно, сейчас день
        else:
          - service: input_select.select_option
            entity_id: input_select.home_mode
            data:
              option: Day

          - service: script.yandex_station_tts
            data:
              target: >
                {{ trigger.event.data.get('entity_id', 'last') }}
              text: Переключила дом в дневной режим
