automation:
  - id: home_mode_set_day_by_light
    alias: 'Home Mode: Set Day (by light)'
    triggers:
      - trigger: light.turned_on
        target:
          entity_id:
            - light.bedroom_main
            - light.living_room_main
            - light.kitchen_main
            - light.entrance
        options:
          for:
            seconds: 10
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state:
          - Bedtime
          - Night
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.home_mode
        data:
          option: Day

  - id: home_mode_set_day_by_voice
    alias: 'Home Mode: Set Day (by voice)'
    triggers:
      - trigger: event
        event_type: yandex_intent
        event_data:
          text: Сейчас день
    actions:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
        then:
          - action: script.yandex_station_tts
            data:
              target: >-
                {{ trigger.event.data.get('entity_id', 'last') }}
              text: Действительно, сейчас день
        else:
          - action: input_select.select_option
            target:
              entity_id: input_select.home_mode
            data:
              option: Day

          - action: script.yandex_station_tts
            data:
              target: >-
                {{ trigger.event.data.get('entity_id', 'last') }}
              text: Переключила дом в дневной режим
