automation:
  - id: bedroom_shades_close
    alias: 'Bedroom Shades: Close'
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_motion
        from: 'off'
        to: 'on'

      - platform: time_pattern
        minutes: '/20'
    condition:
      - condition: state
        entity_id: binary_sensor.bedroom_window
        state: 'off'

      - condition: state
        entity_id: cover.bedroom
        attribute: current_position
        state: 100

      - condition: numeric_state
        entity_id: sensor.illuminance_north_side
        below: 15

      - condition: state
        entity_id:
          - binary_sensor.bedroom_any_occupancy
          - binary_sensor.anyone_home
        state: 'on'
    action:
      - service: cover.close_cover
        entity_id: cover.bedroom

cover:
  - platform: template
    covers:
      bedroom:
        unique_id: bedroom_shades
        friendly_name: Bedroom Shades
        device_class: shade
        optimistic: false
        position_template: >
          {{ state_attr('cover.bedroom_shades_motor', 'current_position') }}
        availability_template: >
          {{ states('cover.bedroom_shades_motor') not in ['unknown', 'unavailable'] }}
        set_cover_position:
          if:
            - condition: state
              entity_id: binary_sensor.bedroom_window
              state: 'off'
          then:
            - service: cover.set_cover_position
              entity_id: cover.bedroom_shades_motor
              data:
                position: '{{ position }}'
        stop_cover:
          service: cover.stop_cover
          entity_id: cover.bedroom_shades_motor
