automation:
  - id: workshop_shades_close
    alias: 'Workshop Shades: Close'
    trigger:
      - id: lock_unlocked
        platform: state
        entity_id: lock.front_door
        from: locked
        to: unlocked

      - platform: state
        entity_id: binary_sensor.evening_time
        from: 'off'
        to: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: binary_sensor.evening_time
        state: 'on'

      - condition: or
        conditions:
          - condition: trigger
            id: lock_unlocked

          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'

      - condition: state
        entity_id: binary_sensor.workshop_window
        state: 'off'

      - condition: state
        entity_id: cover.workshop
        attribute: current_position
        state: 100

      - condition: template
        value_template: >
          {{ (now() - state_attr('automation.workshop_shades_close',
                                  'last_triggered')|default(now() - timedelta(days=1), true)).total_seconds() > 8 * 60 * 60 }}

    action:
      - service: cover.set_cover_position
        entity_id: cover.workshop
        data:
          position: 20

cover:
  - platform: template
    covers:
      workshop:
        unique_id: workshop_shades
        friendly_name: Workshop Shades
        device_class: shade
        optimistic: false
        position_template: >
          {{ state_attr('cover.workshop_shades_motor', 'current_position') }}
        availability_template: >
          {{ states('cover.workshop_shades_motor') not in ['unknown', 'unavailable'] }}
        set_cover_position:
          if:
            - condition: state
              entity_id: binary_sensor.workshop_window
              state: 'off'
          then:
            - service: cover.set_cover_position
              entity_id: cover.workshop_shades_motor
              data:
                position: '{{ position }}'
        stop_cover:
          service: cover.stop_cover
          entity_id: cover.workshop_shades_motor
