automation:
  - id: everybody_left_home
    alias: Everybody Left Home
    trigger:
      - platform: state
        entity_id: binary_sensor.anyone_home
        from: 'on'
        to: 'off'
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.anyone_home_last_seen
        data:
          datetime: '{{ now().strftime("%Y-%m-%d %H:%M:%S") }}'

  - id: anyone_home_last_seen_update
    alias: 'Anyone Home Last Seen: Update'
    trigger:
      - platform: time_pattern
        minutes: /4
    condition:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: 'on'

      # тайминг из scene_welcome_home_on
      - condition: template
        value_template: >
          {{ (now() - states.binary_sensor.anyone_home.last_changed).total_seconds() > 5 * 60 }}
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.anyone_home_last_seen
        data:
          datetime: '{{ now().strftime("%Y-%m-%d %H:%M:%S") }}'

  - id: anyone_near_home_detected
    alias: 'Anyone Near Home Detected'
    triggers:
      - trigger: state
        entity_id: binary_sensor.anyone_near_home
        from: 'off'
        to: 'on'
    actions:
      - action: timer.start
        entity_id: timer.anyone_near_home_recently

  - id: kitchen_balcony_tracker_led_update
    alias: 'Kitchen Balcony Tracker: LED Update'
    mode: queued
    triggers:
      - trigger: state
        entity_id: binary_sensor.anyone_near_home
        to:
          - 'on'
          - 'off'
    actions:
      - action: switch.turn_{{ trigger.to_state.state }}
        entity_id: switch.kitchen_balcony_tracker_led

device_tracker_template:
  - unique_id: device_tracker.misaka_near_home
    name: Misaka Near Home
    icon: mdi:home-floor-negative-1
    location: >
      {{ 'Near Home' if is_state('binary_sensor.misaka_kitchen_balcony_presence', 'on') else False }}
    source_type: gps

  - unique_id: device_tracker.layma_iphone_near_home
    name: Layma iPhone Near Home
    icon: mdi:home-floor-negative-1
    location: >
      {{ 'Near Home' if is_state('binary_sensor.layma_iphone_kitchen_balcony_presence', 'on') else False }}
    source_type: gps

  - unique_id: device_tracker.misaka_ble
    name: Misaka BLE
    icon: mdi:bluetooth-connect
    location: >
      {{ is_state('binary_sensor.misaka_hallway_presence', 'on') or is_state('binary_sensor.misaka_living_room_presence', 'on') }}
    source_type: bluetooth_le

  - unique_id: device_tracker.layma_iphone_ble
    name: Layma iPhone BLE
    icon: mdi:bluetooth-connect
    location: >
      {{ is_state('binary_sensor.layma_iphone_hallway_presence', 'on') or is_state('binary_sensor.layma_iphone_living_room_presence', 'on')  }}
    source_type: bluetooth_le

input_datetime:
  anyone_home_last_seen:
    name: 'Anyone Home: Last Seen'
    has_time: true
    has_date: true
    icon: mdi:exit-to-app

template:
  - binary_sensor:
      - name: Anyone Home
        state: >
          {{ states('zone.home')|int(0) > 0 }}
        device_class: presence

      - name: Anyone Near Home
        state: >
          {{ states('zone.near_home')|int(0) > 0 }}
        device_class: presence

timer:
  anyone_near_home_recently:
    name: 'Anyone Near Home: Recently'
    duration:
      minutes: 7

zone:
  - name: Dextor Work
    latitude: !secret geo_dextor_work_latitude
    longitude: !secret geo_dextor_work_longitude
    radius: 82
    icon: mdi:briefcase

  - name: rom-mak
    latitude: !secret geo_rommak_latitude
    longitude: !secret geo_rommak_longitude
    radius: 50
    icon: mdi:glass-cocktail

  - name: Near Home
    latitude: !secret geo_home_latitude
    longitude: !secret geo_home_longitude
    radius: 100
    icon: mdi:home-import-outline

  - name: Home
    latitude: !secret geo_home_latitude
    longitude: !secret geo_home_longitude
    radius: 27
    icon: mdi:home
    passive: true
