# дополнительные сервисы
version: "3.9"
name: hotaru
services:
  glances:
    image: nicolargo/glances:latest
    pid: host
    network_mode: host
    environment:
      GLANCES_OPT: -w
    volumes:
      - /:/sda:ro
    deploy:
      restart_policy:
        condition: unless-stopped
  timemachine:
    image: mbentley/timemachine:smb-20231119
    network_mode: host
    environment:
      DEBUG_LEVEL: '1'
      TM_UID: '1000'
      TM_GID: '1000'
      PASSWORD: $BACKUP_PASSWORD
    volumes:
      - /data/timemachine:/opt/timemachine
    deploy:
      restart_policy:
        condition: unless-stopped
  backup:
    image: mbentley/timemachine:smb-20231119
    environment:
      DEBUG_LEVEL: '1'
      TM_UID: '1000'
      TM_GID: '1000'
      TM_USERNAME: backup
      PASSWORD: $BACKUP_PASSWORD
      ADVERTISED_HOSTNAME: ''
      SHARE_NAME: backup
    ports:
      - 10137:137/udp
      - 10138:138/udp
      - 10139:139
      - 10445:445
    volumes:
      - /data/backup:/opt/backup
    deploy:
      restart_policy:
        condition: unless-stopped
  transmission:
    image: ghcr.io/linuxserver/transmission
    network_mode: host
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Moscow
    volumes:
      - /etc/transmission:/config
      - /data/nas:/files
    deploy:
      restart_policy:
        condition: unless-stopped
